### ISSUE TITLE
Feature Request: Add "nofollow" and "target" options to "add Link" form

### ISSUE THREAD

**Issue by Rafache** [pagekit/pagekit#114]
Add an option to choose the target of the link and the ability to add (or not) "nofollow" rel. Something like that:

![capture decran 2014-07-24 a 12 24 20](https://cloud.githubusercontent.com/assets/7793847/3686773/b482f0b8-131c-11e4-85f1-7e7c74f2efd5.png)

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
