### ISSUE TITLE
Feature Request: Multiple Page Templates

### ISSUE THREAD

**Issue by josefweibel** [pagekit/pagekit#118]
As a user I want to have the possibility to use multiple page templates for different purposes. For example a two column layout and a full-with layout. Basic functionality needed to use pagekit in a professional environment. Or is there another solution for this idea?

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
