### ISSUE TITLE
Feature Request: additional fields for search engine information in blog and page extention

### ISSUE THREAD

**Issue by josefweibel** [pagekit/pagekit#120]
As a user I want that people are able to find my page via search engines. At the moment not even a meta description is rendered in the "alpha" theme. If this is not thought to be a core feature I would like to contribute a marketplace extension.

Bonus: an autogenerated nice sitemap.xml

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
