### ISSUE TITLE
Feature Request: add "publish up" and "publish down" dates on widgets

### ISSUE THREAD

**Issue by Rafache** [pagekit/pagekit#127]
As in Joomla, dates of publications are very useful.

Something like that :

![capture decran 2014-07-25 a 18 23 30](https://cloud.githubusercontent.com/assets/7793847/3704814/10f107a8-1418-11e4-8041-d88185b46a57.png)

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
