### ISSUE TITLE
css for @editor is not loaded

### ISSUE THREAD

**Issue by michael-tourneur** [pagekit/pagekit#140]
Im writing an extension for pagekit, and would like use the powerful html/markup editor of pagekit.
will be great if we can load automatically the css of the editor.
i can make it work if i load @style('theme', 'extension://system/theme/css/theme.css').
However this is theme for the admin site and have some css conflict with alpha theme for the frontend.
Best way to do that would be to create a separated css file just for the editor.

PS: using @editor() load the js and work good

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
