### ISSUE TITLE
Feature Request: possibility to move/organize files in folders (media manager)

### ISSUE THREAD

**Issue by danielkratz** [pagekit/pagekit#153]
Currently I am only able to upload a file in the media manager, but I can't move it into another directory later. I would e.g. like to sort files into directories via drag'n'drop.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
