### ISSUE TITLE
Regular WYSIWIG editor

### ISSUE THREAD

**Issue by argosmedia** [pagekit/pagekit#174]
The current editor is very user unfriendly. Any CMS should have at least one modern WYSIWIG editor. This editor is almost unusable for regular website builders, CMS users and authors.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.

**Comment by stroborobo** [comment]
Not fixed, please reopen so we don't loose the discussion in this issue.

Otherwise could anyone give hints where to start if that could be made a module?

**Comment by MalteScharenberg** [comment]
We are already working on a extension for an WYSIWIG editor.
Here is s Pagekit feature branch which should make it easier for extensions to hook into the editor: https://github.com/pagekit/pagekit/tree/feature/editor

**Comment by stroborobo** [comment]
Great! Thank you for the info! :)
Can you update this issue once it's ready?

**Comment by bryanchalker** [comment]
The Github Editor feature page is 404.

I'm in the same camp as those wanting a full-fledged WYSIWYG editor. Has nothing to do with my wanting or fellow devs...all has to do with the user. In the vast majority of cases, a user in the Wordpress-type arena will not be happy or even use a Markdown editor. They want to access a file-explorer for image uploads, as well view formatting as they are placing content. Many will be cut/pasting content in from approved content sources (PDFs, .DOCs, etec.), which is always fun. Markup does not play well with that type of workflow.

**Comment by tobbexiv** [comment]
Check out the TinyMCE extension in the Marketplace. It brings TinyMCE as WYSIWYG editor as replacement of the default editor.

**Comment by bryanchalker** [comment]
welll now...hmmmm. Looks interesting. If it has the upload capabilities I would def be back on board. The rest of the functionality is there, though :) 

Thanks for the quick followup on this @tobbexiv
