### ISSUE TITLE
Add a settings to block google fonts

### ISSUE THREAD

**Issue by michael-tourneur** [pagekit/pagekit#178]
Im living in china and the font loaded from google are just horrible.
PageSpeed raise of 80%.

would be great if we can add a setting to load or not google fonts on the admin part.

The same case was existing on Wordpress. Many users complained about the speed to load a page since Wordpress integrate a google font on their admin part.

A nice module exists to avoid this: http://wordpress.org/plugins/disable-google-fonts/

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
