### ISSUE TITLE
Impossible to connect to the database

### ISSUE THREAD

**Issue by iDrevniy** [pagekit/pagekit#180]
Somthing strange going on. I couldn't compleet third installation of Pagekit. Previos two atempts didn't cause any problems. But now Pagekit couldn't connect to data base. can't imagine what happened.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
