### ISSUE TITLE
Clearer Navigation Menu

### ISSUE THREAD

**Issue by muffinjello** [pagekit/pagekit#184]
### The issue.
Hello, I was wondering if it would be possible to make the 'main navigation' within Pagekit more end-user friendly. I take pride in being a computer wiz for many years, however when I first launched the CMS - I had absolutely **no** idea on how to actually get to the other sections of the CMS (I did not know that a menu would come up when you hover over the pagekit icon, and this almost caused me to abandon the CMS entirely and look for another). 

### The solution
I was wondering if it would be possible to change that menu to look more like a "button" or something that should be hovered over, rather than just a logo.

I realise that the once you get into certain widgets (ie. blog) a link navigation pops up to the side of the pagekit icon, which is fine and works quite well, but I still believe there needs to be more emphasis somehow on that pagekit icon. Possibly when you first login a popup comes up, telling you to click on the icon for the menu?

Just my two cents.

**Comment by patrickmatsumura** [comment]
Felt the same way, so :+1:

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
