### ISSUE TITLE
What is wrong with cyrillic symbols?

### ISSUE THREAD

**Issue by iDrevniy** [pagekit/pagekit#191]
Trying to solve the problem:
file: \themes\alpha\css\theme.css
@import 'https://fonts.googleapis.com/css?family=Open+Sans:300,400,600';
change to this
@import url(http://fonts.googleapis.com/css?family=Open+Sans&subset=latin,cyrillic,cyrillic-ext,latin-ext);

The same for
\extensions\system\theme\css\theme.css

It loocks better but I still have problem with one symbol: ш. Interesting that uppercase Ш is wright, problem only with small ш.

Any thoughts?

PS
This problem is only in frontend.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
