### ISSUE TITLE
How to make Multi Tenant / Site?

### ISSUE THREAD

**Issue by ghprod** [pagekit/pagekit#195]
Hi, 

any idea how to make multi site with one installer of pagekit?

Thanks :)

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.

**Comment by ghprod** [comment]
:+1:
