### ISSUE TITLE
Typo: It should not be "Faeroese" but "Faroese"

### ISSUE THREAD

**Issue by denchev** [pagekit/pagekit#197]
During translation process I found out this typo. It should not be "Faeroese" (language) but "Faroese".

This is just a typo but there are lot of inconsistencies within the language files.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
