### ISSUE TITLE
Extension Elements

### ISSUE THREAD

**Issue by dwitzig** [pagekit/pagekit#198]
It would be great if the concept of zoo elements could make its way into pagekit. 
If extensions could share elements they could be developed once and reused across multiple extensions. (galley element, video player element, etc...)

Initially a UI to add and mange elements in a extension would not be needed, elements could be added in extensions views.

PS very excited about Pagekit!!

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
