### ISSUE TITLE
404 or redirect to home page if doesn't exist

### ISSUE THREAD

**Issue by rnbwwlkr** [pagekit/pagekit#204]
If a URL doesn't exist I expect the system to show a 404 error page or at least redirect to home page. It would be nice if you can configure the 404 error page in the system.

![404](https://cloud.githubusercontent.com/assets/3128003/3965327/76ce8010-2795-11e4-8926-2c5fdb0b42be.png)

**Comment by Suven** [comment]
> The default 404 can be overridden by your theme. I will add some documentation on how to do this.

Can you elaborate on this? I did not find any example of this. Is the idea to overwrite pagekits error.php inside the theme? If so, what should be you files name/path?

**Comment by tobbexiv** [comment]
General information on how to overwrite system views: https://pagekit.com/docs/developer/theme#overwrite-system-views

For error page:
Original structure: `pagekit/app/system/modules/theme/views/error.php`
Structure in your theme: `views/system/error.php`
