### ISSUE TITLE
Twitter Bootstrap support

### ISSUE THREAD

**Issue by Zyles** [pagekit/pagekit#207]
Not sure if you have anything against Bootstrap since you created your own UIkit. But I have to throw it out there anyway since Bootstrap is too big to neglect.

Is it possible, or how hard is it to utilize a Bootstrap theme with Pagekit?

Logically it should be easy since it may just be adapting HTML/CSS to a new theme and change the templates accordingly. Is this all?

Thanks.

**Comment by Fitrepreneur** [comment]
Hi Zyles - 

I know my answer is a bit late, but...

We have set up an implementation of pagekit that loads Bootstrap which works well without conflicts nor modifications.

JM

**Comment by noahfreedman** [comment]
@Fitrepreneur link?
