### ISSUE TITLE
Fallback needed for date localization

### ISSUE THREAD

**Issue by chrispecoraro** [pagekit/pagekit#208]
Line 7 of pagekit/extensions/blog/views/ post/index.razr

````php
        @trans('Written by %name% on %date%', ['%name%' => $post.user.name, '%date%' => '<time datetime="'.date($post.date, 'Y-m-d H:i:s').'">'.date($post.date).'</time>' ])
````
Prints something similar to "TuePMUTCE_AugETue01408487941" Instead of the localized date if the locale file is missing in the /extensions/system/languages.

I tested with Italian (it_IT).  When I copy the  /extensions/system/languages/fr_FR directory into the  /extensions/system/languages/it_IT directory, the problem disappears, but we should have a fallback to en_US.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
