### ISSUE TITLE
I can't edit my blog title in the admin area

### ISSUE THREAD

**Issue by PCDotFan** [pagekit/pagekit#209]
I'm sorry that I don't know where I could edit my blog title (Although in indexAction) . And in WordPress or other CMS, after some article title, we can add a blog name and customize the separator. Like this: 25 days later... - Pagekit Blog or 25 days later... | Pagekit Blog

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
