### ISSUE TITLE
Unable to delete package from Marketplace

### ISSUE THREAD

**Issue by adam-paterson** [pagekit/pagekit#220]
I know this is probably in scope, just not finished yet. However at the moment you are unable to delete a package from the PageKit marketplace. You can only unpublish.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
