### ISSUE TITLE
update error.

### ISSUE THREAD

**Issue by adambako** [pagekit/pagekit#224]
hi,
i try to update the pagekit from the backend but i get the error message @trans("Whoops, something went wrong.")
![page](https://cloud.githubusercontent.com/assets/8457004/4088783/2bba0a70-2f62-11e4-9584-2d95064af27f.jpg)

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
