### ISSUE TITLE
Page URL restrictions

### ISSUE THREAD

**Issue by muffinjello** [pagekit/pagekit#236]
Hello,

I recently created a page with url "/themes". Funnily enough, the CMS did not object to this, and when I went to that page's URL, I instead got the generic apache folder list showing all of the themes in my pagekit installation. (Slightly concerning)

Maybe it's because I'm running pagekit version 0.8.4, but two things need to happen here:
* Restrict URL names such as this which conflict with core system folders (and let the user view that folder)
* Have an empty index.php in each of these core folders to prevent outside users from seeing the goodies hidden within.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
