### ISSUE TITLE
Right mouse button click on admin links triggers click event

### ISSUE THREAD

**Issue by ste93cry** [pagekit/pagekit#237]
Hello,
when I try to open a link in the admin panel of Pagekit in a new window/tab, the page is loaded in the current tab too. It seems that pressing the right button of the mouse on a link triggers the click (not normal). This is clearly a bug. My version of Pagekit is 0.8.6 on PHP 5.6, Apache 2.4 and Windows

P.S sorry for all the title changes, didn't see that it updated the issue history

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
