### ISSUE TITLE
Allow to edit image content

### ISSUE THREAD

**Issue by smuriu** [pagekit/pagekit#238]
Hello,

I love the direction that pagekit has taken. One thing that I would like added though is a way to edit images added to the storage area (resize, crop, etc) and possibly even directly from the "Settings" dialog in a page/blog. Could make use of the awesome [Imagine](https://github.com/avalanche123/Imagine) library or perhaps allow integration with the [aviary SDK](https://developers.aviary.com/).

I think it would be especially useful to edit directly in a page/blog or othe content entry perhaps based on certain presets that can be managed in some part of the admin interface.

Regards,
Njenga

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
