### ISSUE TITLE
[Feature Request] Featured image in blog extension

### ISSUE THREAD

**Issue by ste93cry** [pagekit/pagekit#241]
Hello,
first of all thank you for this wonderful project, although it's still in its infancy I see a great potential and I like the way it's built. I would prefer to have the full Symfony features under the hood but I know it's too much for a simple blog. Anyway, this is a feature request for the featured image of a blog post. As example you can take a look at Wordpress, where each article can have it's own featured image which can then be used as thumbnail in the frontend. I think it would be a great addition, what do you think?

![featured-image](https://cloud.githubusercontent.com/assets/1770485/4240518/98769636-39eb-11e4-89cf-50385e9df398.jpg)

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
