### ISSUE TITLE
[Bug] Feed widget doesn't decode HTML entities

### ISSUE THREAD

**Issue by ste93cry** [pagekit/pagekit#242]
Hi,
the feed widget used in the dashboard doesn't property decode HTML entities resulting in a wrong text printed. Look at the image below for an example of the problem. I'm using Firefox on Windows 8.1. We can't use the triple brackets in the Handlebars template because it would decode HTML tags too and this is a potential security issue, however I found [this](http://stackoverflow.com/questions/10654234/handlebars-html-entity-decode) solution that seems to work, although I don't like it. Btw, why is the apostraphe encoded like that :open_mouth:?

![feed-entities-bug](https://cloud.githubusercontent.com/assets/1770485/4242831/ebb8797e-3a02-11e4-9a80-fd36349bbb25.png)

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
