### ISSUE TITLE
[Feature Request] Support installation of additional languages

### ISSUE THREAD

**Issue by ste93cry** [pagekit/pagekit#243]
Hi,
Pagekit supports the translation of all messages into multiple languages, and the project is already using transifex. It would be great to have a place where users can download and install additional languages, and the installer should have an additional step where the default language is chosen from the available languages. Also, I'm a newbie of transifex: do I need an account to download the translations? If not, where can I download the Italian translation?

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
