### ISSUE TITLE
Suggestions for Marketplace.

### ISSUE THREAD

**Issue by HeinZawHtet** [pagekit/pagekit#245]
In marketplace, items are one-time sell ( I mean buyer purchase existing version and won't get updates)? Or updates version are downloadable forever?

Sometime extension developer want to sell their item with advanced like lifetime upgrades or 6 month upgrades. Will Pagekit marketplace support that kind of selling?

And, when marketplace will be launch officially?

Sorry for my bad eng.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
