### ISSUE TITLE
[Feature Request] Featured post

### ISSUE THREAD

**Issue by ste93cry** [pagekit/pagekit#246]
Hi,
as a user I would like to have an option to set a post as featured, so it can be highlighted when necessary. Joomla already has this feature while Wordpress seems to need a plugin. Anyway, it's usually one of the common thing that a CMS offer and it would be nice to have it out-of-the-box in Pagekit.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
