### ISSUE TITLE
[Feature Request] Record how many times a post has been read

### ISSUE THREAD

**Issue by ste93cry** [pagekit/pagekit#247]
Hello,
sorry for opening so many issues :flushed: this feature request is about a common feature that CMS have: the ability to record how many times a post has been read. When a user opens an article page, Pagekit should just increase the views column by 1.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
