### ISSUE TITLE
[Bug] Pagekit installer crashes if tables already exists

### ISSUE THREAD

**Issue by ste93cry** [pagekit/pagekit#252]
Hello,
reinstalling Pagekit on a database where the tables already exists produces the following error after the **Setup your site** step. Tested with master version on PHP 5.5, Apache 2.4 on Windows 8.1

`Database error: An exception occurred while executing 'INSERT INTO pk_system_user (name, username, password, status, email, registered) VALUES (?, ?, ?, ?, ?, ?)' with params ["admin", "admin", "$2y$10$Y5.197EMGCX1f\/LQmJINsep.HOE\/Nmw6Y.nWht0gU7pgpqw.mOEOq", 1, "", "2014-09-17 15:14:00"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'admin' for key 'USER_USERNAME'`

To fix this problem, I have two proposals: the first (like Joomla) is to add a new input to the installer's first step to ask the user what he wants to do with existing tables, the second (like Wordpress) is to just skip the database steps and just create the configuration file. I could try to prepare a PR, if you want.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
