### ISSUE TITLE
Can't install pagekit

### ISSUE THREAD

**Issue by Unc3nZureD** [pagekit/pagekit#253]
I'd like to test this awesome looking CMS, but I've got stuck at installing.
I've got PageKit 0.8.7 & PHP v5.5
Currently I'm trying to install it on a hoster called hostinger.
My website is mmodefender.cu.cc

So, the issue is that after I press Install, I fill in all the details and I press Next. What happens? Nothing. Not even an error message, or the next step.

What did I do wrong?
If you have any special question please ask, I'll gladly answer :)

Thank you!

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
