### ISSUE TITLE
[Feature Request] Favorite Posts

### ISSUE THREAD

**Issue by leog3tz** [pagekit/pagekit#267]
Hello!
As a user I would like to have an option to set a post as **favorite**, so it can be added to my list of   *favorite posts*. It would be nice to have it out-of-the-box in Pagekit.
ex: [link to example!](https://wordpress.org/plugins/wp-favorite-posts/)
Thank's!

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
