### ISSUE TITLE
PostgreSQL compatibility

### ISSUE THREAD

**Issue by valle6** [pagekit/pagekit#271]
I'm studying PageKit and it seems excelent. I have two critics: one, I think create a new engine template isn't the best choice. But, Razr works likeTwig and it is acceptable. Second, why aren't there compatibility with PostgreSQL? If you use Doctrine this doesn't must to be an problem. Do you intend offer PostgreSQL support? When? For me, this is a limitation to adopt it.

Regards.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.

**Comment by tomick** [comment]
@saschadube: Well, bug isn't fixed. Pagekit still lacks of Postgres support.

**Comment by andreybolonin** [comment]
https://github.com/pagekit/pagekit/pull/708
