### ISSUE TITLE
Add html on menu item

### ISSUE THREAD

**Issue by raxan** [pagekit/pagekit#274]
Hi

when I try add html on menu item this is converted to htmlspeciachars.

I think that you should allow html into menu item, so is possible add font-icon or img tag.

I check navbar but is not clear where is sanitized html.

Since menu item is added only by admin, you should not sanitized it.

what do you think?

Thanks

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
