### ISSUE TITLE
Cannot Create Page while Using Subdomain

### ISSUE THREAD

**Issue by satriyowibowo** [pagekit/pagekit#285]
creating new page is easy while using main domain (mydomain.tld)
but while using subdomain (blog.mydomain.tld) , any pages created cannot be opened and returns "Whoops, looks like something went wrong"

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
