### ISSUE TITLE
Possibility to override Rarz system view with Twig custom view

### ISSUE THREAD

**Issue by nicolas-garcia** [pagekit/pagekit#304]
Hello !

This is a feature request from this discussion https://github.com/pagekit/pagekit/issues/273 

It would be great if we could override all views by a custom one in a theme, using twig extension.

Thanks !

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
