### ISSUE TITLE
Blog extension slug has problem on turkish characters

### ISSUE THREAD

**Issue by kaankilic** [pagekit/pagekit#313]
Hi there,

I've improved something to the pagekit.I found an error on turkish chars on slug.I should be convert to utf-8 chars.I think, it's because of js codes of slug conversation.Also, there must be the check same slugs on the db.Because, I tried to check 2 same slug on the different posts on blog extension.It makes complicate something.

Thanks and regards

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
