### ISSUE TITLE
How to use the editor on the frontend pages?

### ISSUE THREAD

**Issue by michael-tourneur** [pagekit/pagekit#317]
Hi pagekit team,
I'm developing a extension for pagekit https://github.com/michael-tourneur/miiQA
and i would like to use the editor use on the backend pages on the frontend pages.
if i use @editor on the razr file on frontend it seems to missing some css.
i notified this missing css is on the backend css. 
Is it possible to created a css file only for edtior.
Or maybe it exists an other way to do?

Regards,

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
