### ISSUE TITLE
Access custom user fields in template

### ISSUE THREAD

**Issue by nicolas-garcia** [pagekit/pagekit#319]
Hi !
I just modified the entity User from system for my use, but I'm stuck on some points.
In the UserController.php, I edited the getInfo() method in order to get my custom fields available in template but it doesn't seems enough.

I added a custom field 'buy_date' in the user entity. It's a datetime field, and in the getInfo(), I added this line :
'buy_date' => ($date = $user->getBuyDate()) ? $this['dates']->format($date) : null,

But, in the template extensions\system\views\admin\user\edit.razr, I'm not able to call $user.buy_date.

What am I doing wrong ?
Thanks in advance !﻿

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
