### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by PhoenixPeca** [pagekit/pagekit#323]
This bug is all bout inserting video/Image via: 

` ![](storage/image.jpg) `  and 
` (video){"src":"storage/video.mp4"  } `

Situation:
when inserting a image named with "(" and ")"  for example : 
` ![](storage/image(1).jpg) `
the (1) just destructs the external open and closing parenthesis symbol that makes the error. 

Recommendation:
I recommend the developers of this CMS to fix this problem in the next version or by renaming the file before it is stored in the storage folder....

Another bug is that I couldn't play the video using (video) ` {"src":"storage/video.mp4"} `

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
