### ISSUE TITLE
Add custom editor plugins

### ISSUE THREAD

**Issue by Rafache** [pagekit/pagekit#327]
Hi,
How to add custom plugins from an extension ? 
On Editor.php (line 116) I found the function where plugins are added.

I would like to do the same from my extension. For example, add a maps with a personalized address.
'editor.load' events does not seem possible to do so.

Thanks.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
