### ISSUE TITLE
CSS fails to load when logged in

### ISSUE THREAD

**Issue by willwac** [pagekit/pagekit#328]
When I visit my site's home page while not logged in, this shows up:
![screen shot 2014-12-16 at 9 55 43 am](https://cloud.githubusercontent.com/assets/6716801/5456534/d986189a-8509-11e4-94c1-9af853aff19f.png)

However, when I login, this shows up:
![screen shot 2014-12-16 at 9 55 02 am](https://cloud.githubusercontent.com/assets/6716801/5456543/ed5f1934-8509-11e4-8125-9386c61e0236.png)
With this error message:

```
FatalErrorException: Error: Call to a member function getIterator() on a non-object in
/home/willwac/Web/extensions/system/src/Menu/MenuProvider.php line 118
```
On top of that, the admin interface still works fine as seen here
![screen shot 2014-12-16 at 9 54 42 am](https://cloud.githubusercontent.com/assets/6716801/5456633/764b6c20-850a-11e4-89fa-0ff3b2493441.png)

Here's a few snippets of code from MenuProvider.php:
line 118: ```$iterator = $menu->getIterator();```
First mention of ```$menu``` line 20:
```PHP
/**
     * @var MenuInterface[]
*/
protected $menus = [];
```
And the entire function where the error occurs:
```PHP
public function getTree($menu, array $parameters = [])
    {
        if (!$menu instanceof MenuInterface) {
            $menu = $this->get($menu);
        }
        $iterator = $menu->getIterator();

        foreach ($this->filters as $filters) {
            foreach ($filters as $class) {
                $iterator = new $class($iterator, $parameters);
            }
        }
```

The site is running on Ubuntu 14.04 LTS hosted on a Free Koding account.
This happens in Chrome Version 39.0.2171.95 (64-bit) (Mac), Safari Version 6.2 (8537.85.10.17.1) (Mac) and Firefox Version 33.0.1 (Mac). I have not tested it on anything else at the moment.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
