### ISSUE TITLE
MySql don't install

### ISSUE THREAD

**Issue by xzynk** [pagekit/pagekit#330]
If I try to install with mysql after I fill the data by pressing the next button , nothing happens. However using SQLLite if it works.

**Comment by JoseDKZ** [comment]
Same Problem

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
