### ISSUE TITLE
Installation errorr: File(dev/urandom) ?

### ISSUE THREAD

**Issue by iDevid** [pagekit/pagekit#331]
I have php-fpm for security reasons, so i don't allow to run code out of tmp and htdocs directory...
I thinks it's necessary in this case but what's this?
PHP message: PHP Warning:  file_exists(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s):

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
