### ISSUE TITLE
RuntimeException: Failed to start the session because headers have already been sent by .../app/app.php" at line 12.

### ISSUE THREAD

**Issue by Slyzza** [pagekit/pagekit#333]
After installation I receive the following statement using php 5.5 and Apache.
Does someone know how to handle this?

I am trying to evaluate pagekit as an alternative to my wordpress photographers webpage.

RuntimeException: Failed to start the session because headers have already been sent by "/var/www/vhosts/slyzza.de/pagekit.slyzza.de/app/app.php" at line 12.

It seems there are problems with the time setting in the app.php..

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
