### ISSUE TITLE
Error Unexpected token in install

### ISSUE THREAD

**Issue by ahmadina** [pagekit/pagekit#337]
Hi
In installation page (http://localhost/installer)(MAMP PRO+PHP 5.5.10) show blank page and in inspect element show error : 

Uncaught SyntaxError: Unexpected token <
installer:1 Uncaught SyntaxError: Unexpected token <
require.min.js:1 Uncaught TypeError: Cannot read property 'normalize' of undefined
require.min.js:1 Uncaught Error: Load timeout for modules: uikit!form-password_unnormalized2
http://requirejs.org/docs/errors.html#timeout

how to fix it?

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
