### ISSUE TITLE
MethodNotAllowedHttpException in RouterListener.php line 149

### ISSUE THREAD

**Issue by wendel841** [pagekit/pagekit#339]
MethodNotAllowedHttpException in RouterListener.php line 149:
No route found for "GET /admin/login": Method Not Allowed (Allow: POST)

In class extensions/system/src/System/Controller/SystemController.php in annotaion allowed methods is set only for "POST", why? I think this is error because with it i can't log in.

    /**
     * @Route("/admin/login", methods="POST", defaults={"_maintenance"=true})
     * @Response("extension://system/theme/templates/login.razr", layout=false)
     */

**Comment by HaeckDesign** [comment]
I ran into that too. I'm sure they're working on it, but a quickfix for @olimsaidov on the bottom of https://github.com/pagekit/pagekit/issues/324 works for me.  

Certainly not the best approach, but it's running

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
