### ISSUE TITLE
Feed widget

### ISSUE THREAD

**Issue by SHL-Hosting** [pagekit/pagekit#340]
Will you create a feed widget for Pagekit, so that it will work on the front-end and not just the back-end?

**Comment by nbpalomino** [comment]
It can be easily ported to display on front-end...

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
