### ISSUE TITLE
Virtual storage support

### ISSUE THREAD

**Issue by karevn** [pagekit/pagekit#342]
It would be REALLY nice to have a "virtual storage" support instead of hardcoded /storage folder to allow sites to easily work with Amazon S3 and other cloud storage platforms. As far as I understand, there's already a Filesystem class that can be a base class for such the storage, that only works with "local" filesystem for now, and it's pretty easy to write an adapter to Flysystem project to add a "storage" service (and rewrite file manager interface to work with it).

**Comment by saschadube** [comment]
Yes, this is on our todo list. As you can see in the [develop branch](https://github.com/pagekit/pagekit/commits/develop) we are working on a lot of stuff right now. Any help is appreciated.

**Comment by karevn** [comment]
I can take care of this. I wrote a basic implementation for $app['storage'] module yesterday, and can finish it as soon as Pagekit develop will be stable enough to launch and let me test it :)

**Comment by steffans** [comment]
Basically you would only need a PHP StreamWrapper for Amazon S3 and then create a Adapter for it like the Adapter\StreamAdapter.php to get the Path resolving right. The overall structure of the Filesystem class doesnt need to be changed for this.

**Comment by karevn** [comment]
It looks like you're right and I need to refactor  the code not to introduce unnecessary subclassing. Too many years spent in WP community :)

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
