### ISSUE TITLE
Move /extensions/system to just /system

### ISSUE THREAD

**Issue by karevn** [pagekit/pagekit#344]
It will make the architecture more logical as the "system" extension is essential and can't be removed (while all the others can be). This change will also make it easier to make /system read-only at the filesystem level for security purposes.

**Comment by nbpalomino** [comment]
:+1: 

This is a nice thought, maybe the new folders structure look like this:

- /system
  - /config
  - / (*) 
  - app.php
  - autoload.php
  - config.php
  - requirements.php
- /var (**)
  - /cache
  - /database
  - /sessions
  - /logs
  - /temp
- /extensions
- /storage
- /themes
- /vendor

_(*) All folders on /extensions/system maybe need a remake for placing on /system. Any thoughts?_
_(**) Folder name is pending confirmation_

**Comment by karevn** [comment]
Hmm. I would propose something like this:
* /extensions (extensions minus "system" extension).
* /storage 
* /system
  * /boot
    * /boot.php (renamed current /app/app.php, including autoload.php)
    * /config-loader.php (renamed config.php) to avoid confusion with ./config.php
    * /config-defaults.php (renamed config/config.php to avoid confusion)
    * /requirements.php
  * /modules
  * /src
* /themes
* /vendor
* /index.php
* /pagekit.php
* /pagekit
* /var (specific name to be discussed, but /var is a standard for frequently changed folders in Unix world - so, why not, it is not Symphony anyway?)
  * /cache
  * /database
  * /sessions
  * /logs
  * /temp 
* /boot.php (optional file created by end user and used instead of /system/boot/boot.php to allow deep bootstrap customisations for, say, multisite installations - hello, WordPress);

The logic behind all the file moves / changes is to avoid confusion where possible and make it easy to learn the bootstrap process when looking at the Pagekit for the first time. With current naming, it took some time to figure out the difference between ./config.php, ./app/config.php and ./app/config/app.php - the names are pretty much equal, so one needs to read the code to figure which file does what.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
