### ISSUE TITLE
Razr templates do not render tel: links correctly

### ISSUE THREAD

**Issue by gabrielholley** [pagekit/pagekit#347]
I've put together the extension "Send" and released it in the marketplace. 

My extension allows you to list a phone number, however, when it renders on the site,

```<a href="tel:555-555-5555">Phone</a>``` becomes ```<a href="website_path/tel:555-555-5555">Phone</a>```

```<a href="tel:@($params.phone)">@trans('Phone')</a>``` becomes ```<a href="website_path/tel:555-555-5555">Phone</a>```

```<a href="@url('tel:'.$params.phone)">@trans('Phone')</a>``` becomes ```<a href="website_path/tel:555-555-5555">Phone</a>```

The tel: protocol should be rendered like mailto:

**Comment by sh0em0nkey** [comment]
I just found out that the same happens with "data"

```<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" />```

comes out

```<img src="website_path/data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" />```

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
