### ISSUE TITLE
Custom content types, fields

### ISSUE THREAD

**Issue by jeff-h** [pagekit/pagekit#348]
I just installed Pagekit and thought the UX was beautiful... nice work!

I'm wondering if there are plans for custom content types, and the ability to change the fields associated with a content type (e.g. like Drupal has)?

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
