### ISSUE TITLE
Pagekit CLI Not Working

### ISSUE THREAD

**Issue by affinitycloud** [pagekit/pagekit#349]
When you run the pagekit CLI with any command it simply outputs the HTML of a Whoops error report. No indication in the HTML what the actual error is.

**Comment by olanystrom** [comment]
I get that error when I run the pagekit cli with the wrong user.

**Comment by jesusdiez** [comment]
The problem that I experience on the `pagekit` script happens on this line (13):
```php
$console = new Console($app, 'Pagekit', $app['version']);
```
And happens because `$app['version']` is not defined.

**Comment by mr-savari** [comment]
Hi there
I'm just started using pagekit and I don't know How to run the cli command?

**Comment by sasajup** [comment]
in Windows try use C:\(pagekit root directory)\php pagekit list
You need register the php.exe directory rout file in the variable windows path. (system)

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
