### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by jixaCo** [pagekit/pagekit#350]
Get the error invalid API Key on  trying to install extensions.
I have enterned API Key in System > Settings before.

**Comment by uvlek** [comment]
I have the same problem too.

**Comment by ideaprison** [comment]
Same here (version: 0.8.8)

**Comment by mr-savari** [comment]
I have the same error too!

**Comment by mr-savari** [comment]
all the folders are writable but i'm getting the same error yet !

**Comment by hostianer** [comment]
That`s why i would never use y product off YOOtheme.
There is ZERO help and no communication between the devs and the community :(

**Comment by steffans** [comment]
The API Key is not active at the moment, can you tell me the steps how to recreate this issue.

**Comment by saschadube** [comment]
@hostianer We have a [https://gitter.im/pagekit/pagekit](community chat) for Pagekit. Just step by :wink:

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
