### ISSUE TITLE
Says installation failed

### ISSUE THREAD

**Issue by PhoenixPeca** [pagekit/pagekit#355]
Pagekit says installation failed but I can open the website and the database has contents.. It's really confusing, I wonder why it says installation failed maybe the installation is partially completed or it's just an error.... Please fix it Pagekit developers!!!!

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
