### ISSUE TITLE
Pagekit on shared server

### ISSUE THREAD

**Issue by ericvanderlinden** [pagekit/pagekit#357]
I've been trying to install pagekit on a Siteground shared server and after a couple of actions in the settings I get this error:
Fatal error: Call to undefined method Pagekit\Component\Config\Config::__set_state() in /home/lucasvan/public_html/antsent/tracent/config.php on line 12

Now Siteground does not allow the APCu extension on the shared server so I guess this has to do with the caching.

Is there a way around this. 
I would be heartbroken to have to go back to Wordpress :)

**Comment by nbpalomino** [comment]
Please post your PHP version and Pagekit version.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
