### ISSUE TITLE
PageKit Webinstaller does not load correctly

### ISSUE THREAD

**Issue by SPQRInc** [pagekit/pagekit#359]
Hello,

after my first installation-attempt failed, I tried to install pagekit from git.

So I used git clone git://github.com/pagekit/pagekit.git and ran composer install after this.

Now if I use my browser to open pagekit (mydomain.com/pagekit) I'm getting the following error: http://d.pr/i/10oQs .

There are no errors in php-errorlog.

**Comment by florianletsch** [comment]
*Please note that this is an explanation on how to get the bleeding edge develop version. And at this point, it is actually quite bleeding as the backend is being re-done completely. The frontend won't work at this point, but there's a lot being developed right now, so you might want to check in every couple of days to see what has changed.* 
 
Please make sure to get the `develop` branch.

```sh
git clone git://github.com/pagekit/pagekit.git --branch develop
composer install
```

You will also need some frontend components which are managed by bower.

```sh
bower install
```

Open in your browser and the installer should load correctly.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
