### ISSUE TITLE
Missing Settings Field

### ISSUE THREAD

**Issue by Xarcell** [pagekit/pagekit#360]
I'm testing out pagekit and I'm using the SQLite DB. I'm trying to activate the marketplace, and I got my APIKey, but I see no where to enter it. Doc says in the Setting > System, but I see no such field.

**Comment by florianletsch** [comment]
It should look like this. What does the interface look like to you?

![screen shot 2015-03-30 at 10 53 53](https://cloud.githubusercontent.com/assets/1116784/6893182/1a8fe0d8-d6cb-11e4-8660-7d78dced3bf6.png)

**Comment by Xarcell** [comment]
Ok, I found it. Your screenshot shows something completely different from what I was seeing. I was going under profile settings. I didn't not realize that there was a menu in the pagekit icon. Consider this issue closed. Thanks for your help.
