### ISSUE TITLE
Can't Install pagekit

### ISSUE THREAD

**Issue by dvlppr** [pagekit/pagekit#362]
I have installed Pagekit by using git clone and composer install
when I go to index.php i have the following error : 

`Fatal error: Can't use function return value in write context in /var/www/site/app/modules/application/src/Application/Traits/RouterTrait.php on line 47`

Apache2/PHP5.4.39 on  Debian 7

**Comment by steffans** [comment]
Can you try to update this line 47 to:

```
if (!static::request()) {
```

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
