### ISSUE TITLE
[Feature Request] Load un-minified JS and CSS in debug mode, and minfied otherwise.

### ISSUE THREAD

**Issue by AlexanderOMara** [pagekit/pagekit#364]
I'm not sure if this is being worked on or not, but presently the develop branch appears to be loading a mix of minified and non-minified JS.

It would be preferable to always load minified JS and CSS, unless debug mode is enabled. In debug mode, loading un-minified versions of the scripts would be very helpful for developers (nobody likes debugging minified JS).

Such a feature would be similar to [WordPress's `SCRIPT_DEBUG` feature](https://codex.wordpress.org/Debugging_in_WordPress#SCRIPT_DEBUG).

**Comment by Ascarius** [comment]
An other solution could be generating [sourcemaps](https://www.npmjs.com/package/gulp-sourcemaps).

**Comment by AlexanderOMara** [comment]
Eh, source maps are only half a solution. They don't map mangled variables names to their original names in the debugger.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
