### ISSUE TITLE
[Feature Request] Enqueue scripts in footer.

### ISSUE THREAD

**Issue by AlexanderOMara** [pagekit/pagekit#365]
Right now it appears that all scripts in theme and extensions are enqueued in the `head`. Generally, it's better to include scripts in the footer when possible for performance reasons.

It would be helpful if `@script` had an option to print the script in the footer, rather than in the header, perhaps by having these print in a `@section('footer')` section in themes.

**Comment by BloomBoy** [comment]
This is a really good suggestion! We would love such an option.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
