### ISSUE TITLE
Mustache mentioned on the home page

### ISSUE THREAD

**Issue by auxsoft** [pagekit/pagekit#366]
In the home page, in the graphic with the technologies utilised, there is a mention to Mustache. Is it the template engine? Shouldn't it be Razr?

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
