### ISSUE TITLE
File access permissions

### ISSUE THREAD

**Issue by daknour** [pagekit/pagekit#367]
It would be a nice feature to allow or to restrict access based on roles, to the files uploaded to the storage folder.

**Comment by karevn** [comment]
I don't think it should be a core feature. Probably, some kind of a plugin.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
