### ISSUE TITLE
add Multisite support

### ISSUE THREAD

**Issue by brody182** [pagekit/pagekit#370]
is this supported or not?

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.

**Comment by brody182** [comment]
what, no multisite functionality? Grrrrrrr

**Comment by nickdring** [comment]
yeah this would be good, gets my vote
