### ISSUE TITLE
Installer: Unexpected token <

### ISSUE THREAD

**Issue by muuknl** [pagekit/pagekit#371]
I installed the development version of pagekit, but when I load up the site, it gives me the error: `Uncaught SyntaxError: Unexpected token <`
Chrome dev tools points to the `<!DOCTYPE html>` when giving the error.

**Comment by nbpalomino** [comment]
Did you run **gulp** succesfully ?
Where URL did you visit ?

More info about your error, myself see that error too, but disappear after reload.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
