### ISSUE TITLE
Getting error on installation

### ISSUE THREAD

**Issue by agusesetiyono** [pagekit/pagekit#373]
Getting error on installation with mesaage 'Fatal error: Call to undefined method Pagekit\Kernel\Event\KernelEvent::getResponse() in /Users/agusesetiyono/Documents/pagekit-dev/pagekit/app/modules/session/module.php on line 129'

How to solve?

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
