### ISSUE TITLE
Navbar disappears randomly

### ISSUE THREAD

**Issue by florianletsch** [pagekit/pagekit#376]
The main navbar on my website is rendered correctly. 

```
<ul class="uk-navbar-nav">
  <li class="">
    <a href="/pagekit/">Blog</a>
  </li>
  <li class="">
    <a href="/pagekit/about">About</a>
  </li>
  <li class=" uk-active">
    <a href="/pagekit/demo">Demo</a>
  </li>
</ul>
```

However, every now and then (about 1 in 10 page refreshes) it disappears. The markup for the navbar then looks like this:

```
<ul class="uk-navbar-nav">
</ul>
```

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
