### ISSUE TITLE
Change htaccess to allow for slugs identical to existing folders

### ISSUE THREAD

**Issue by florianletsch** [pagekit/pagekit#377]
Right know you cannot access content with slugs that match any existing folder, i.e. you couldn't create `domain.com/themes`, because there exists a `themes` folder.

Same goes for the CLI file `pagekit`. Right know you can't create content at the location `domain.com/pagekit`

These changes should be added to the `.htaccess` file

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
