### ISSUE TITLE
Widget not shown for blog articles

### ISSUE THREAD

**Issue by nstaeger** [pagekit/pagekit#379]
Created a widget and assigned it to _blog_. But when I open an the articles overview or an article itself, it is not visible. (but is visible on other sites)

Tested with the logo-position and a text widget.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
