### ISSUE TITLE
Location Widget issues

### ISSUE THREAD

**Issue by florianletsch** [pagekit/pagekit#385]
- Search doesn't behave intuitively. Example when Searching for "San Francisco". Typed "San Francisc" results in suggestion "Boston". When typing "San Francisco", suggestion is some place in Mexico?
- Shouldn't the time be taken from the selected location? Always seems to be the current system time, no matter which location I select.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
