### ISSUE TITLE
Pagekit usernames are case-sensitive. Should they be?

### ISSUE THREAD

**Issue by florianletsch** [pagekit/pagekit#387]
I can create `admin`, `Admin`, `admIn` etc. And users can only login with the exact spelling.

Suggestion: Normalize username internally, so that case doesn't matter. Still display the original spelling to the outside. i.e. `FirstnameLastname`, but login also possible with `firstnamelastname`. Same way Twitter does it.

**Comment by florianletsch** [comment]
Seems to be related to using sqlite

**Comment by janschoenherr** [comment]
fixed
