### ISSUE TITLE
Hero image path is incorrect when current page is a submenu item

### ISSUE THREAD

**Issue by florianletsch** [pagekit/pagekit#388]
Hero image **works** on homepage. `http://localhost/pagekit`

Hero image **works** on top level page. `http://localhost/pagekit/projects`

Hero image **doesn't work** on pages which are not on top level. `http://localhost/pagekit/projects/one`

Pagekit tries to load `http://localhost/pagekit/projects/storage/green.jpg`

Pagekit should load `http://localhost/pagekit/storage/green.jpg`

**Comment by malles** [comment]
I solved this by placing a `base` link to the site's root in the head.
