### ISSUE TITLE
Error on first login

### ISSUE THREAD

**Issue by chil360** [pagekit/pagekit#394]
I have installed from the develop branch and completed the setup but when I try to log in as admin I am getting the following error:

Fatal error: Call to a member function get() on null in /mnt/data/Webserver/dev/pagekit/app/system/modules/site/index.php on line 140
Whoops, looks like something went wrong.

**Comment by malles** [comment]
I think you just jumped in some WIP with the menu's and widget. My install is broken now too, it worked this morning :)
Try this version, that might work better: https://github.com/pagekit/pagekit/archive/de61e0c2f4252a47236029dd51cb51f76b7f7fac.zip

**Comment by chil360** [comment]
Ok, thanks. I'll try it.

**Comment by malles** [comment]
https://github.com/pagekit/pagekit/commit/078f9e0163042a26bee007ac1493ddd20a568325
Looks like that one should do the trick :)

**Comment by chil360** [comment]
I've just updated to the latest version and now I'm getting:

Fatal error: Call to a member function setCookie() on null in /mnt/data/Webserver/dev/pagekit/app/modules/cookie/index.php on line 42

Must be something they are working on, I'll keep trying!

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
