### ISSUE TITLE
Clean all past issues and poor documented.

### ISSUE THREAD

**Issue by nbpalomino** [pagekit/pagekit#397]
Hello Pagekit Team,

Gratz for such an amazing job with Pagekit, Im very excited about UI/UX and codebase improvements.

Lets clean up with all issues whom were poorly described, we should reply and if the OP dont answer, just close the issue.

There are more than 100 issues and many of them are already fixed.

Best regards.

**Comment by saschadube** [comment]
Thanks! Did that today :smile:
