### ISSUE TITLE
Slugify as filter

### ISSUE THREAD

**Issue by nstaeger** [pagekit/pagekit#398]
As slugifying is a very common thing to do on a web-application, wouldn't it be great to have this as filter available in Pagekit. Could do a PR on this in the next weeks. What do you think?

**Comment by malles** [comment]
I noticed the PHP slugify function is in the blog controller. As I needed it for my form extension, I copied it. It would be nice to have that in a general helper there as well.

**Comment by steffans** [comment]
@nstaeger Sure, PR for this filter would be great :+1:
