### ISSUE TITLE
Move /app/database to /database

### ISSUE THREAD

**Issue by karevn** [pagekit/pagekit#402]
As far as I understand, `/app/database` is for sqlite database, so this folder has to be writable for server process.  But, all other files at /app are read-only (or end user may want to make them read-only for security reasons). It may create an unnecessary confusion and make site administration harder with no apparent reason. Why not to move database folder to just `/database`?  - it will be clear that only `/database`, `/storage` and `/tmp` are writable, while others are not, and make things a little bit easier for users.

**Comment by florianletsch** [comment]
This is a fair point. Not sure if @steffans and @janschoenherr had a particular reason not to do so. I'd like to here there voice on this.

**Comment by florianletsch** [comment]
We had a quick chat at the office this morning. So here is the reasoning for locating it in `/app/database`:

- There are 2 situations in which the directory is used at all: When using Sqlite or when enabling the debug toolbar. 
- In the case which we currently consider the *default setup* (Mysql, debug toolbar disabled), that folder would be empty and wouldn't need to be writable.
- Having a folder which is empty in pretty much all cases on the root level seems even more confusing to the average user ("ah, here must be my database. why is it empty?")

Still, your points are valid as well. We will keep the current situation for now. But we're open to further discussion if future experience shows this actually confuses users or causes other technical trouble.

**Comment by karevn** [comment]
Think about it this way: if you'll accept this idea now, and it will prove wrong in future - some people will just have to delete `/database`. But if my point is valid and you'll decide to move it to from `/app/database/` to `/database` somewhere past 1.0 release - the total cost of this change will be huge.
