### ISSUE TITLE
There is no option to choose different template on each page

### ISSUE THREAD

**Issue by dawidxt** [pagekit/pagekit#403]
Hi,
Iike in the title, I don't see option to choose different template for speciefic page. 
User may want to create homepage in different layout than about page or contact page. Right now it uses the same template. 

Many of CMS has such option, it gives a lot more functionality for webdesigners.

**Comment by malles** [comment]
You can't select a different _theme_ for specific pages, but the selected theme has it's options available in each page. 
A theme could implement different styles that could be assigned to different pages. That would be up to the template developers.

**Comment by dawidxt** [comment]
please forgive me my english, but I don't get it... how to do it from within the dashboard ? unless it is possible only from main theme files - which is pretty annoying and uncomfortable.

**Comment by saschadube** [comment]
We don't have that option at the moment
