### ISSUE TITLE
[Feature Request] - Calendar Events Extension

### ISSUE THREAD

**Issue by Xarcell** [pagekit/pagekit#404]
I've been looking for a CMS that uses SQLite for my clients and that is simple for them to use(I'm a web designer). Pagekit seems like a good choice thus far, even though it's still in early development.

This is my request for an events calendar. I build sites for small businesses in my local area and the most common request I get is the ability to post an event(page or blog post) and link it to a calendar. This makes it easy for their customers can track the business's upcoming events.

I think the simplest design for this would be a calendar extension that works like making posts, then attaches a link to that post in a fully fledged calendar. Alot of the code from the pages widget could be reused here? A bonus would a widget that shows a mini calendar with upcoming events.

Just an idea for design. Perhaps just adding a calendar to the blog extension would be easier. I honestly don't know. I'm not a developer.

**Comment by saschadube** [comment]
We are open for suggestions and pull requests :smile:
