### ISSUE TITLE
[Bug] Warning when installing 0.9

### ISSUE THREAD

**Issue by karevn** [pagekit/pagekit#410]
When I install 0.9 on OSX Yosemite + Apache (installed with macports), with PHP 5.6.13 instlled as Apache module I have the next response when trying to configure MySQL connection: 

```
<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
{"status":"no-connection","message":"Database connection failed!"}
```

"Connection failed" is ok, but warning probably is not :)

**Comment by karevn** [comment]
I can't install Pagekit at all with mysql (even after disabling deprecation messages) - I get "connection errors" all the time. My Mysql is set up to use Unix socket - may be it's a good idea to add this option to the installed?

**Comment by bwhitty** [comment]
You need to set the `ini` setting `display_errors=off` to get rid of the warning. It is a deprecation notice which is being sent to the output buffer, which then causes the "headers already sent" warning.

**Comment by karevn** [comment]
I know. But imagine I was not able to open browser inspector and check what happened? Being just a generic user, I would just tell "It does not even install" and delete Pagekit forever. So I think it should be fixed somehow - by sending the SQL setup form in some other way, or by checking this option at the system requirements check stage to tell user what to do explicitly. Otherwise, it just works sloppy.

**Comment by ste93cry** [comment]
:+1: I have the same problem on Windows, never had a problem with other applications

**Comment by MalteScharenberg** [comment]
`$HTTP_RAW_POST_DATA` is used if `always_populate_raw_post_data` is set to `1` in `php.ini`.

Since `$HTTP_RAW_POST_DATA` is deprecated in PHP 5.6.0 `always_populate_raw_post_data` is inactive by default in PHP 5.6.0.  I assume that you are using an `php.ini` from an older PHP version.

http://php.net/manual/en/reserved.variables.httprawpostdata.php

**Comment by ste93cry** [comment]
The `php.ini` from PHP5.6 download archive has the `always_populate_raw_post_data` commented out and the warning is shown. As no other applications that I use shown this warning message, maybe something with Pagekit is triggering it.

**Comment by MalteScharenberg** [comment]
Do you have `display_startup_errors` enabled?

**Comment by karevn** [comment]
As far as I understand, it's possible to change this option at runtime with `ini_set` somewhere at the initialisation stage. I am not sure though... But it would be a reliable and elegant solution. Otherwise, it would be better to switch to `x-form-urlencoded` for compatibility reasons. Not elegant, but I really think it will make installation much easier for those who don't have enough expertise to tweak PHP settings (or just don't have an access being on shared servers). Also, including custom `php.ini` file into distribution may be partial solution - many hosters use local php.ini copies to tweak settings per-site.

**Comment by ste93cry** [comment]
@MalteScharenberg Yes, I have `display_errors` and `display_startup_errors` both enabled. But the strange thing is that I never saw this warning before, and I'm using a lot of other PHP applications on the same environment

**Comment by MalteScharenberg** [comment]
@ste93cry check if any of them sends requests with a mime type divergent
 to `multipart/form-data` or `application/x-www-form-urlencoded`.

**Comment by MalteScharenberg** [comment]
@karevn Unfortunately this error occurs within PHPs startup sequence (i.e. the warning is already send to the output buffer when the first line of Pagekit is interpreted). Therefor `set_ini` wont have any effect.

So as you pointed out switching to `x-form-urlencoded`would be the only possible solution to suppress the warning by Pagekit. The problem with this is that Pagekit heavily relies on type-safe `application/json` requests. 

Only users who already tweaked their php.ini by enabling `display_startup_errors` (which is no good idea at a production system), have to modify `always_populate_raw_post_data`.

**Comment by karevn** [comment]
@MalteScharenberg for now, 95% of your users are web developers ("early adopters") or "developer wannabies", and many of them have display startup errors option enabled. So this error can easily ruin their initial impression. 
Regarding global switching - If the JS architecture is right, then all the AJAX requests should be sent through one "outlet" in JS. So, it should be a very easy change at the JS side. On the server side - you can add some middleware to handle it. Not one-liner change, but should not be a big pain too.

I can make some research on this area and create a pull request if you want.

**Comment by ste93cry** [comment]
I just checked WordPress which is one of the PHP scripts running on the same environment and it seems that they're sending ajax data with `application/x-www-form-urlencoded` mime type

> Only users who already tweaked their php.ini by enabling display_startup_errors (which is no good idea at a production system), have to modify always_populate_raw_post_data.
You're right in saying that enabling this option on a production server is not recommended, however at development environment that option is on by default and I don't think it's a good idea to just ignore this case.

**Comment by karevn** [comment]
@ste93cry WP is a mammoth from the old times. But it survived all these years :)

**Comment by MalteScharenberg** [comment]
@ste93cry @karevn We are not ignoring this issue. But it's clearly a PHP 5.6.* related issue. 
PHP 5.4.* and PHP 5.5.* are running fine. This issue will also be fixed in PHP 7.0.0.
So switching to `application/x-www-form-urlencoded` would only be a work-around for a very specific server configuration.
I think, if someone needs to enable startup errors and deprecated error messages it is no big deal to fix this PHP issue by setting `always_populate_raw_post_data` to `-1`, as recommend by the PHP team.

Read: 
https://wiki.php.net/rfc/slim_post_data
https://bugs.php.net/bug.php?id=67991.

**Comment by ste93cry** [comment]
I never said you're ignoring the issue, I said we should not do it :smile: Unfortunately there is still a plenty of time before PHP 7, and even when it will be released a lot of hosting providers will not upgrade to it, at least not immediatly. I don't know the reasons or security implications of using `application/json` vs `application/x-www-form-urlencoded`, but I don't see any problem in switching over the latter to fix the warning.

**Comment by MalteScharenberg** [comment]
`application/json` is type-safe. Switching to `application/x-www-form-urlencoded` would require some emulation middleware.

**Comment by ste93cry** [comment]
I'm a newbie, so please be patient: what do you mean with type-safe? What are the technical implications of using `application/x-www-form-urlencoded`, check if the json is valid on the server and ensuring that the response is always json?

**Comment by karevn** [comment]
@MalteScharenberg  taking in account now long PHP version lifecycle is, 5.6 will be here for a few years. So I think it worths investing efforts into emulation middleware to work this thing around. Backend code should not be that complex, and even if frontend will require more efforts - they'll be an investment into better architecture, not waste of time.

**Comment by MalteScharenberg** [comment]
@ste93cry With `application/json` strings, numbers, arrays, objects, boolean and null values can be transferred without conversion. With `application/x-www-form-urlencoded` everything gets casted to string. Imagine sending a boolean `false` as string...PHP would cast this to boolean `true`.
Although it is possible to transfer also arrays with `application/x-www-form-urlencoded`, there are a lot of edge cases there conversion is not done as expected.

**Comment by MalteScharenberg** [comment]
@karevn You are right, it wont be too much effort. We are using vue-resource (https://github.com/vuejs/vue-resource) for all requests. So only one change in frontend. But at the moment this seems not to be a big issue and a change like this can result in a lot of small bugs.

**Comment by ste93cry** [comment]
What about the `emulateJSON` option of `vue-resource`?

**Comment by MalteScharenberg** [comment]
@ste93cry Yes, that could be used for that.

**Comment by karevn** [comment]
@MalteScharenberg it looks like the solution was found ;)

**Comment by MalteScharenberg** [comment]
Can you check if this works for you?https://github.com/pagekit/pagekit/commit/2587622540dd766e962552c06aade7c3ab17882b

**Comment by ste93cry** [comment]
It works for me

**Comment by MalteScharenberg** [comment]
@ste93cry Thanks for testing!

**Comment by iniweb** [comment]
@MalteScharenberg ping

***Database connection failed!***

There is still issue for me.

Database with name pagekit, pagekit user and grant all privileges on database (connection works if i test throw SequelPRO)

OS: OSx Yosemite 10.10.4
PHP Version 5.6.8 ( php-osx.liip.ch by Liip )
NGINX 1.6.2 + php-fpm (php.ini configuration the same for CLI and FPM)

*php ini:*
<pre>
# php -i
display_startup_errors => Off => Off
always_populate_raw_post_data => -1 => -1
display_errors => Off => Off
</pre>

**Comment by iniweb** [comment]
hm, i used Symfony v2 vhost like config file for NGINX (just changed app.php on index.php) and has "database connection error", then i found issue https://github.com/pagekit/pagekit/issues/437 and change configuration like described in that gist https://gist.github.com/geekish/7c8963e41f1b1c20f062, it's helped ;)
