### ISSUE TITLE
How to remove Google fonts?

### ISSUE THREAD

**Issue by lupuxyz** [pagekit/pagekit#413]
I am in China,we cannot use any Google Services without VPN.So I want to remove google fonts for the better experience. thank you ;)

**Comment by leozhang2018** [comment]
If your Pagekit's theme is setting  by default, you can replace Google Fontsby following ways.
Open the `html/Pagekit/packages/pagekit/theme-one/css` folder,and find the `theme.css`.
Edit this file using your favorite text editor.
Find this line

`@import 'https://fonts.googleapis.com/css?family=Open+Sans:600, 400, 300';`

U can replace it by using Commonly used front-end public library. 
For example,

    @import 'http://fonts.useso.com/css?family=Open+Sans:300,400,600`;

**Comment by Xarcell** [comment]
@lupuxyz  if this worked for you(and it should), please close this issue. Thanks.
