### ISSUE TITLE
No gallery - portfolio plugin

### ISSUE THREAD

**Issue by dawidxt** [pagekit/pagekit#418]
Hi, I've noticed that with new version of PageKit, there is no any gallery plugin in marketplace. And I am sure it will change in the future, so my sugesttion is... two plugins with mainly same role, but

1. Simple gallery plugin
2. Gallery plugin with the pressure of portfolio pages. So list of images, after clicked it would redirect to details about each work with option to navigate them "previous work / next work". Categories would be nice as well.

BTW: thank You for the new version of PageKit CMS, it's great !

**Comment by florianletsch** [comment]
Looks like @malles has done exactly what you wanted: http://portfolio.bixie.org/

**Comment by malles** [comment]
@florianletsch This is exactly what got me started :)

**Comment by florianletsch** [comment]
Awesome!

**Comment by dawidxt** [comment]
sorry for re-opening. WOW nice and very powerful as far as I can see by now. Thank You :)
