### ISSUE TITLE
Yootheme widgetkit integration 

### ISSUE THREAD

**Issue by stecomo** [pagekit/pagekit#421]
It would be nice to see widgetkit for pagekit and more features in the page building more similar to zoo , maybe?

**Comment by saschadube** [comment]
Yes, we have plans to port Widgetkit and Warp themes for Pagekit. It's just a matter of time :wink: Custom field are also on the todo list. #119

**Comment by nickdring** [comment]
+1

**Comment by tomhaus1** [comment]
+1

**Comment by nickdring** [comment]
+1

**Comment by dmdigital** [comment]
+1

**Comment by yajata** [comment]
+1
