### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by Xarcell** [pagekit/pagekit#425]
Beta version:

I downloaded, unzipped, and uploaded, but when I visit URL, it throws a 500 error. Alpha version installs fine.

I may have overlooked it when browsing through the files, but did it not come with a web installer?

Thanks.

**Comment by Smeaven** [comment]
On a production server I get a 500 error too. But its probably caused by server misconfiguration: 
> The server encountered an internal error or misconfiguration and was unable to complete your request.
Probably I should contact the hosting support ...
On my localhost with xampp I everythings fine!

**Comment by MalteScharenberg** [comment]
There is still a web-installer :) 

It would be great if you enable Pagekit debug mode and post a more detailed error report.
For the installer debug mode can be enabled at `app/installer/config.php`.

**Comment by boerke85** [comment]
I have the same problem. 
A "500 Internal Server Error".
I have enable the debug mode, but nothing show...

**Comment by korke** [comment]
It is the same with me
When I try to reach the site, the error appears.
The update has apparently not worked, as the photo shows.
![screenshot 2015-09-14 17 21 28](https://cloud.githubusercontent.com/assets/9445371/9853691/30e3697c-5b05-11e5-84f4-440786b490b8.png)
It tells me to upgrade to 0.91, but the update is previously shown to be successful. Below appears an Error Message. I've activated the debug mode.
![screenshot 2015-09-14 17 23 51](https://cloud.githubusercontent.com/assets/9445371/9853804/d466f956-5b05-11e5-97d8-efe8b682b7c2.png)

**Comment by Xarcell** [comment]
This seems to be resolved as of 0.9.1.
