### ISSUE TITLE
Error: Whoops, something went wrong

### ISSUE THREAD

**Issue by LrMiLoef** [pagekit/pagekit#427]
At the end of installationsprocess i'll get following error message:

***Installation ist fehlgeschlagen!
Whoops, something went wrong***

How can i debug this? Or where can i find additional informations for this problem?

**Comment by MalteScharenberg** [comment]
It would be great if you could enable Pagekit debug mode and post a more detailed error report.
The installer debug mode can be enabled at `app/installer/config.php`.

**Comment by LR-Medien** [comment]
Ok... i did this. After reinstalling pagekit there are no more detailed informations about the error... :-(

**Comment by MalteScharenberg** [comment]
Can you open the console of your browser (make sure that logging of XMLHttpRequests is enabled) and post the contents of the last response before the error occurs?

You could also send me a link to your Pagekit installation.
