### ISSUE TITLE
COMPOSER_HOME installation issue

### ISSUE THREAD

**Issue by stecomo** [pagekit/pagekit#428]
Downloaded the package, uploaded, run the installation .. but, after i insert website name and description, i get this error:

"The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly"

**Comment by MalteScharenberg** [comment]
On what operating system your server is running?

**Comment by fojt-cz** [comment]
i have same problem on Linux server

**Comment by MalteScharenberg** [comment]
Are you running PHP in safe mode?

**Comment by stecomo** [comment]
Linux here too

**Comment by MalteScharenberg** [comment]
Would be great if any of you could test if this commit fixes the issue: https://github.com/pagekit/pagekit/commit/8fd50e41c1c499e3fed69f3c85e47194ee314994

**Comment by fojt-cz** [comment]
i used your code but it have same problem

maybe i see this error because i don't have Composer in my server

**Comment by MalteScharenberg** [comment]
@fojt-cz Pagekit comes bundled with Composer. So this should be no problem . :)
Can you please check ones again with https://github.com/pagekit/pagekit/commit/6148eaef7efd1eef279ae88b1bd3ad516f1d0efc ?

**Comment by stecomo** [comment]
just tried, it works

**Comment by fojt-cz** [comment]
here too
