### ISSUE TITLE
Send Testmail produce a error

### ISSUE THREAD

**Issue by blueforce** [pagekit/pagekit#429]
Hi 
I've tried to test my PHP Mailfunction on the basic settings. Email and Name are correct and well stored.
But when I click the Test-Button, so I get this error:
"Ajax request to server failed" 
But no other informations...

PHP Version: 5.6.12
Extensions: Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, gmp, SPL, iconv, pcntl, readline, Reflection, session, standard, shmop, SimpleXML, mbstring, tokenizer, xml, cgi-fcgi, PDO, bcmath, dom, fileinfo, gd, imagick, imap, json, exif, mcrypt, mysql, mysqli, mysqlnd, pdo_mysql, pdo_sqlite, Phar, posix, soap, sockets, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, mhash, ionCube Loader

**Comment by malles** [comment]
See also #416

**Comment by willwac** [comment]
Trying to use SMTP, I get the Ajax error as above.
Version	5.5.9-1ubuntu4.11
Handler	apache2handler
Built On	Linux AWS 3.13.0-57-generic #95-Ubuntu SMP Fri Jun 19 09:28:15 UTC 2015 x86_64
Extensions	Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, apache2handler, PDO, curl, gd, json, mcrypt, mysql, mysqli, pdo_mysql, readline, mhash, Zend OPcache
Pagekit Version	0.9.1
