### ISSUE TITLE
Website is insecure (pagekit.com)

### ISSUE THREAD

**Issue by bwhitty** [pagekit/pagekit#430]
1. Your website does not have a valid certificate (on Chrome 46).
2. The login page (http://pagekit.com/user/login) does not force HTTPS, and so login attempts are sent in the clear.

In summary, all of the authenticated section should be forced over HTTPS.

**Comment by saschadube** [comment]
Thanks! It's fixed. We are forcing ```https``` now

**Comment by logic-dev** [comment]
Not fixed. Uses HTTP, sends user data using GET and all inputs report that they're blank when filled in

**Comment by WolfieZero** [comment]
Page seems to use HTTPS now, but looks like it's still doing a GET request

![user_registration___pagekit](https://cloud.githubusercontent.com/assets/648761/12532865/eb4aa578-c216-11e5-8e7e-e02c289581d4.png)

**Comment by saschadube** [comment]
Thanks, we just overlooked it when we upgraded to Vue 1.0. It's fixed now.

**Comment by WolfieZero** [comment]
:smile:
