### ISSUE TITLE
There is something wrong about http://pagekit.com/docs/quickstart

### ISSUE THREAD

**Issue by leozhang2018** [pagekit/pagekit#432]
No route found for "GET /docs/quickstart"

**Comment by arthurkirkosa** [comment]
With /docs as well

**Comment by FutureMedia** [comment]
Yeah, I noticed it too. All the docs section has gone.

**Comment by MalteScharenberg** [comment]
Since Pagekit 0.9.0 is a complete rewrite, we need to create a complete new documentation as well.
