### ISSUE TITLE
Empty installer page

### ISSUE THREAD

**Issue by FutureMedia** [pagekit/pagekit#433]
On a MacBook, all dependencies installed, MAMP server with 5.6 PHP, the installer redirect works but the page does not render. For some reason the template render engine does not work.

**Comment by MalteScharenberg** [comment]
t would be great if you could enable Pagekit debug mode and post a more detailed error report.
For the installer debug mode can be enabled at `app/installer/config.php`.

**Comment by FutureMedia** [comment]
@MalteScharenberg thanks for chipping in. I followed your advice but nada, nothing, I still get an empty page. I also checked the php log for errors but I couldn't find anything. 
This is the page I get:
https://gist.github.com/FutureMedia/67ad22c44b2e3903b298

**Comment by MalteScharenberg** [comment]
You need to run `npm install` if you downloaded Pagekit directly from this repository. 

Or simply download the release version at http://pagekit.com

**Comment by FutureMedia** [comment]
@MalteScharenberg I downloaded the release version and it worked.
Thank you.
