### ISSUE TITLE
The mysql database pro Russian litteras hieroglyphs

### ISSUE THREAD

**Issue by sk-plehanovec** [pagekit/pagekit#434]
The mysql database pro Russian litteras hieroglyphs.Please fix

**Comment by sk-plehanovec** [comment]
Please fix my ticket

**Comment by steffans** [comment]
Can you explain the issue you experiencing? What needs to be changed in order to support Russian litteras hieroglyphs?

**Comment by sk-plehanovec** [comment]
The database MySQL saved RU language
![mysql](https://cloud.githubusercontent.com/assets/1770738/9956245/aeb59722-5e10-11e5-92fb-2cb68d2e684c.png)

Р’Р»РѕР¶РµРЅРёСЏ

**Comment by greenweb73** [comment]
Server gives the default encoding different from utf-8, you used localserver DENVER or OpenServer?

**Comment by sk-plehanovec** [comment]
The site on a dedicated server

**Comment by greenweb73** [comment]
http://phpfaq.ru/charset#repair
