### ISSUE TITLE
One page

### ISSUE THREAD

**Issue by prisis** [pagekit/pagekit#435]
Is it possible to make a one page theme?
Something like, if you create 3 or 4 pages on the backend so that you can call it with a id or name in the main page.

**Comment by huanga** [comment]
What is it that you're trying to achieve? You can have pages unlinked from the navigation (Check the "Hide in menu" checkbox), which should keep your menu nice and uncluttered. You can still link to the 'hidden' pages in other pages by linking to it directly.

**Comment by saschadube** [comment]
I would create multiple widgets and publish them on different positions on the same page. Now you can use the IDs (for the different positions) to navigation between them. This should already be possible with the One theme.
