### ISSUE TITLE
Market/Themes In Development Environment Un-Rendered

### ISSUE THREAD

**Issue by dpgowan** [pagekit/pagekit#436]
Seems that the Market/Themes section goes un-rendered in a development environment via the HTTPS protocol, works fine under standard HTTP/1.1.

![screen shot 2015-09-12 at 7 01 23 am](https://cloud.githubusercontent.com/assets/13948465/9831239/5bbb2148-591c-11e5-8d32-d9036d9311d4.png)

**Comment by MalteScharenberg** [comment]
SSL will be supported soon.
