### ISSUE TITLE
Site administration translation

### ISSUE THREAD

**Issue by ptitmickey** [pagekit/pagekit#438]
Hello Guys,
I'm a newbie on github, but I would like to help you to translate this very good CMS in french.
Where can I found translation files to correct "close" badge in widget edition or "visibility" tab for example...

![capture d ecran 2015-09-12 a 19 04 11](https://cloud.githubusercontent.com/assets/10517940/9832640/f2981638-5981-11e5-9b5f-13944c3c35e8.png)

Thanks in advance, I hope that I will be part of your contributors for this very good project !

Nicolas

**Comment by visualcookie** [comment]
@ptitmickey You can find them in ``` app/system/languages/fr_FR ```.

**Comment by Smeaven** [comment]
Pagekit uses Transifex: https://www.transifex.com/pagekit/pagekit-cms/

**Comment by MalteScharenberg** [comment]
Contributions at Transifex are highly appreciated.

https://www.transifex.com/pagekit/pagekit-cms/
