### ISSUE TITLE
can't install pagekit

### ISSUE THREAD

**Issue by HoshinoTouko** [pagekit/pagekit#443]
I installed pagekit according to the way in Readme.md. But when I open /installer, it appears
<code>{{ 'Choose language' | trans }}
{{ "Select your site language." | trans }}</code>
The site is blog.touko.moe.

**Comment by malles** [comment]
Did you run `npm install`? The page does show as you describe before running that.
Works fine after that.

**Comment by MalteScharenberg** [comment]
Please run `npm install` like @malles mentioned or simply download the dist files: https://github.com/pagekit/pagekit/releases

**Comment by HoshinoTouko** [comment]
Thx very much
