### ISSUE TITLE
Possibility to write and edit without HTML Tags

### ISSUE THREAD

**Issue by schadila** [pagekit/pagekit#446]
it would be great if the Editor allows to edit and write without the HTML-Tags for Authors and Users who dont have a knowledge of HTML.

**Comment by florianletsch** [comment]
You can enable Markdown mode in the editor. It's a good mix for writing without html tags.

**Comment by schadila** [comment]
So I think that doesnt work (bug?) because when i enable markdown...nothing happens..




Von meinem iPhone gesendet

**Comment by schadila** [comment]
when i will update pagekit, the following message appearse:



Von meinem iPhone gesendet

**Comment by florianletsch** [comment]
The editor will look the same (except for the toolbar switching to support Markdown). No html tags will disappear. In the frontend however, the markdown from the editor will render as HTML. You can check by clicking the "Preview" tab in the editor.
