### ISSUE TITLE
Issues with internal link syntax that doesn't render in frontend

### ISSUE THREAD

**Issue by florianletsch** [pagekit/pagekit#449]
In a page, I have the following link. The syntax is the result of using the link picker.

```html
<a href="@page/2">About Us</a>
```

In the frontend, it *should render*:

```html
<a href="">About Us</a>
```

What I *expect* it to render is more like:

```html
<a href="/pagekit/about">About Us</a>
```

**Comment by janschoenherr** [comment]
Is there a page with id `2`? If you enable the debug toolbar, do you see a route with the name `@page/2`?
