### ISSUE TITLE
Installation locks up

### ISSUE THREAD

**Issue by gabrielholley** [pagekit/pagekit#450]
After unzipping and loading pagekit in the browser, install kept hanging. I'd get database connection errors, timeouts from git commands. After struggling with it, and checking to make sure there were no write issues and MySQL was running properly - I noticed that LastPass kept injecting script onto the page to save the password.

I opened up an incognito window in Chrome with my extensions disabled, and it installed like a champ without any issues.

I am only running LastPass, and uBlock Origin. Both of which are really popular extensions, and happen to inject CSS & JavaScript.

Might be worth looking into.

**Comment by MalteScharenberg** [comment]
I tested Pagekit installation with LastPass and uBlock Origin activated and can't recreate this issue. Did you made some special settings?

**Comment by gabrielholley** [comment]
No. I'm closing this issue because I myself cannot re-duplicate it now. I'm chalking it up to local issue with either my browser or server.
