### ISSUE TITLE
ManyToMany Relation with Data

### ISSUE THREAD

**Issue by Smeaven** [pagekit/pagekit#453]
```php
class User {

// code

/** @ManyToMany(targetEntity="Item", tableTrough="Rating",keyTroughFrom="user_id", keyThroughTo="item_id")*/
public $items

//code

}
```

My rating table has more column in addition to the primary and foreign keys:
- rating
- date

If I define a ManyToMany Assoction in the User Entity I loose information of the single relations. Is there a way to fetch it in the User Entity or should I create a Entity for this User-Item-Relation?

**Comment by janschoenherr** [comment]
Yes, then you actually retrieve the User from the database, you'll add the related conditions for the subquery e.g. try:

    User::query()->related('items.rating', 'items.date')->get();
