### ISSUE TITLE
Pagekit Installer Population Issues

### ISSUE THREAD

**Issue by MBRO95** [pagekit/pagekit#454]
![image](https://cloud.githubusercontent.com/assets/9059779/9920733/c94de6f6-5ca4-11e5-8e03-70c05c6decc9.png)
The above image is the screen im staring at after configuring DigitalOcean Ubuntu 14.04 x64 VPS Droplet.

My Method:
#UPDATE & UPGRADE THE SYSTEM
apt-get -y update && apt-get -y upgrade

#INSTALL LOGISTICAL DEPENDENCIES
apt-get install -y software-properties-common python-software-properties git curl

#NGINX + PHP + EXTENSIONS
apt-get install -y nginx php5-fpm php5-cli php5-mysql php5-curl php5-json php5-apcu

#INSTALL COMPOSER
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

#INSTALL NODE + BOWER + GULP
curl -sL https://deb.nodesource.com/setup | sudo bash -
apt-get install -y nodejs
npm cache clean
npm install -g bower
npm install -g gulp

#CLONE PAGEKIT LOCALLY
mkdir -p /usr/share/nginx/pagekit/{public_html,logs}
git clone git://github.com/pagekit/pagekit.git /usr/share/nginx/pagekit/public_html
cd /usr/share/nginx/pagekit/public_html
composer install
npm install
bower install --allow-root
gulp

#CONFIGURE NGINX
cat <<'EOF' > /etc/nginx/sites-available/pagekit
server {
	server_name pagekit;
	listen 80;
	listen [::]:80;
	root /usr/share/nginx/pagekit/public_html;
	access_log /usr/share/nginx/pagekit/logs/access.log;
	error_log /usr/share/nginx/pagekit/logs/error.log;
	index index.php;
	server_name locahost;
 
	location / {
    		try_files $uri $uri/ /index.php?$args;
	}
 
	location ~* \.(?:ico|css|js|gif|jpe?g|png|ttf|woff)$ {
    		access_log off;
    		expires 30d;
        	add_header Pragma public;
        	add_header Cache-Control "public, mustrevalidate, proxy-revalidate";
	}
 
    	location ~ \.php$ {
        	fastcgi_index index.php;
        	fastcgi_split_path_info ^(.+\.php)(.*)$;
        	fastcgi_keep_conn on;
        	include /etc/nginx/fastcgi_params;
        	fastcgi_pass unix:/var/run/php5-fpm.sock;
        	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    	}
 
    	location ~ /\.ht {
       		deny all;
    	}
 
}
EOF

#INSTALL MARIADB & CREATE PAGEKIT DATABASE
apt-get install -y mariadb-server
mysql_secure_installation {n, Y, Y, Y, Y}
mysql -uroot -p
CREATE DATABASE pagekit;
GRANT ALL PRIVILEGES ON pagekit.* TO 'pagekituser'@'localhost' IDENTIFIED BY 

'pagekituser_passwd';
FLUSH PRIVILEGES;
\q

#TEST CONFIG & SYMLINK
sudo nginx -t
ln -s /etc/nginx/sites-available/pagekit /etc/nginx/sites-enabled/pagekit
rm /etc/nginx/sites-available/default -rf
rm /etc/nginx/sites-enabled/default -rf
rm /usr/share/nginx/html -rf
chown -R www-data: /usr/share/nginx/pagekit/public_html/
/etc/init.d/nginx restart

**Comment by MBRO95** [comment]
Take a look for yourself: http://45.55.135.160/index.php/installer

**Comment by steffans** [comment]
Did you run webpack to compile the Javascripts ?

**Comment by MBRO95** [comment]
@steffans where do i need to run webpack, like what directory? Sorry I am new to this but want to develop on this platform

**Comment by MBRO95** [comment]
Got it working after issuing these update commands after install:

git pull
composer update
npm install
bower update
gulp
webpack

**Comment by yangfan21** [comment]
@MBRO95  

I build gulp   but php  template can't be exec like this   

I writed a test.php  echo phpinfo()  it's ok. Please tell me how to fix this problem

![image](https://user-images.githubusercontent.com/11313960/28662164-c6c1b020-72eb-11e7-98d2-56ba0595df35.png)

**Comment by SPQRInc** [comment]
This problem has been solved. Please open another issue, if the following does not help:

- Run `git clone --branch develop https://github.com/pagekit/pagekit.git`
- Run `composer install`
- Run `npm install`
- Run `gulp`
- Run `webpack`

I'd also recommend not to install Pagekit using git. You can simply download and install it this way: https://pagekit.com/docs/getting-started/installation#step-1-download-and-open-the-installer .

If you choose to download following https://pagekit.com/docs/getting-started/installation#step-1-download-and-open-the-installer you do **not** run `gulp`, `webpack` etc.
