### ISSUE TITLE
marketplace and update broken on https

### ISSUE THREAD

**Issue by CriseX** [pagekit/pagekit#455]
#351 This is still relevant on the new version, however, I can only speak for our variant of it not necessarily the one referenced by the issue opener.

**Comment by steffans** [comment]
Yes, the new version is not released yet.You can enable https in v0.9.1 when you edit the `index.php` line 29 to use https.
```php
'system.api' => 'https://pagekit.com'
```

**Comment by CriseX** [comment]
I was talking about the beta, anyways what a strange place to put editable config stuff... have you considered moving that to either separate php or json file (would need to make sure to hide obviously).

**Comment by florianletsch** [comment]
Marketplace and update have moved to full https support, so this should work now.
