### ISSUE TITLE
Hello Installation keeps failing

### ISSUE THREAD

**Issue by pacaskurban** [pagekit/pagekit#456]
Hello everyone,

Im very eager to play with the pagekit. Now when i install it i follow all steps. In the end i get the message: Installation failed "whoops". I turned on debug mode but it doesnt show anything.
Can someone tell what im doing wrong?

**Comment by MalteScharenberg** [comment]
Can you open the console of your browser (make sure that logging of XMLHttpRequests is enabled) and post the contents of the last response before the error occurs?

You could also send me a link to your Pagekit installation.

**Comment by pacaskurban** [comment]
THE installation is on www.pascalphotography.com database name is pascal and user is also pascal psw is Enschede25 

Verstuurd vanaf mijn iPhone

**Comment by MalteScharenberg** [comment]
Can you also enable the debug mode for the installer? Just open `app/installer/config.php` and set `debug` to `true`.

By the way: I removed your login data from the comment. ;)

**Comment by pacaskurban** [comment]
Did thAt allready

Verstuurd vanaf mijn iPhone

**Comment by Xarcell** [comment]
@pacaskurban there were installer issues in 0.9.0. They seem to have been fixed in 0.9.1. Which version are you using?

**Comment by pacaskurban** [comment]
Im using 0.9.1

**Comment by Xarcell** [comment]
Apparently, this issue has returned.

**Comment by MalteScharenberg** [comment]
@Xarcell Did you test with the latest version from develop branch?

**Comment by Xarcell** [comment]
@MalteScharenberg I just tested the latest development branch just now. The 500 error still exists. When I get to my desktop, i'll try it with Firefox in debug mode to see if I can find any errors.

**Comment by Xarcell** [comment]
@MalteScharenberg I enabled debugging in the installer config and it still doesn't show any errors in FF or IE Touch. 500 error in IETouch, and blank page in FF(only html, head, and body tags).

**Comment by Xarcell** [comment]
I tried the latest rev branch today and it still doesn't work. The web installer is broken.

**Comment by Xarcell** [comment]
FYI, I tried the web installer on a domain root, sub-domain root, and a subdirectory. The results were all the same. IE throws 500 error, FF is a blank page, and Chrome is a blank page with failed to load the domain URL, and favicon. All this with the web installer debug set to true in the config file.

**Comment by MalteScharenberg** [comment]
The next Pagekit release (and current dev branch) comes with a reworked installer. 
Please open a new issue if problems occur.
