### ISSUE TITLE
Failed at the pagekit@ install script 'bower install && webpack && gulp'.

### ISSUE THREAD

**Issue by malles** [pagekit/pagekit#459]
`npm install` fails on the gulp task `cldr`: https://github.com/pagekit/pagekit/blob/develop/gulpfile.js#L30

Folder `app/system/modules/intl/data/` does not exist.

**Comment by MalteScharenberg** [comment]
Should work with this commit: https://github.com/pagekit/pagekit/commit/345ab46b3d78063f1bef82af01884396c181e5d3

**Comment by malles** [comment]
Ah, okay, yeah this was a clone I did before that. I've been away a few days ;)
