### ISSUE TITLE
Get 500 error while getting http://pagekit.loc/jquery

### ISSUE THREAD

**Issue by surgun9** [pagekit/pagekit#460]
trying to open front end home page (Hello theme) I get 500 error for: http://pagekit.loc/jquery

in error log found this:

[Sun Sep 20 17:18:22.816353 2015] [:error] [pid 11919] [client 127.0.0.1:34933] PHP Warning: array_keys() expects parameter 1 to be array, null given in /var/www/html/surgun/pagekit/app/vendor/composer/composer/src/Composer/Package/Locker.php on line 421, referer: http://pagekit.loc/admin/system/marketplace/themes

did all command for fresh install:
git pull
composer update
npm install
bower update
gulp
webpack

also my bower update logs :
bower update
bower uikit#master          not-cached git://github.com/uikit/bower-uikit.git#master
bower uikit#master             resolve git://github.com/uikit/bower-uikit.git#master
bower lodash#~3.10.1            cached git://github.com/lodash/lodash.git#3.10.1
bower lodash#~3.10.1          validate 3.10.1 against git://github.com/lodash/lodash.git#~3.10.1
bower vue#~0.12.15              cached git://github.com/yyx990803/vue.git#0.12.15
bower vue#~0.12.15            validate 0.12.15 against git://github.com/yyx990803/vue.git#~0.12.15
bower vue-resource#~0.1.16      cached git://github.com/vuejs/vue-resource.git#0.1.16
bower vue-resource#~0.1.16    validate 0.1.16 against git://github.com/vuejs/vue-resource.git#~0.1.16
bower js-md5#~1.1.0             cached git://github.com/blueimp/JavaScript-MD5.git#1.1.1
bower js-md5#~1.1.0           validate 1.1.1 against git://github.com/blueimp/JavaScript-MD5.git#~1.1.0
bower uikit#master            checkout master
bower uikit#master            resolved git://github.com/uikit/bower-uikit.git#481def45af
bower jquery#>= 1.9.0           cached git://github.com/jquery/jquery.git#2.1.4
bower jquery#>= 1.9.0         validate 2.1.4 against git://github.com/jquery/jquery.git#>= 1.9.0

**Comment by surgun9** [comment]
in hello-theme  you use <?php $view->script('theme:js/theme.js', 'jquery') ?> to get jquery
but this leads to 500 error, the correct code should be
<?php $view->script('theme', 'theme:js/theme.js', 'jquery') ?>

**Comment by MalteScharenberg** [comment]
You are right, this line is wrong. We will update the hello-theme.
But I'm not getting a 500 error because of this. JS is just not included.
Would be great if you can provide more informations about your server.

Thank you!

**Comment by surgun9** [comment]
Ubuntu 14.04, php 5.5

My apache virtual host settings
<VirtualHost *:80>
        ServerAdmin xxx
        ServerName pagekit.loc
        ServerAlias www.pagekit.loc
         
        DocumentRoot /var/www/html/surgun/pagekit
        ErrorLog ${APACHE_LOG_DIR}/pagekit-error.log
        CustomLog ${APACHE_LOG_DIR}/pagekit-access.log combined

        <Directory /var/www/html/surgun/pagekit>
            Options Indexes FollowSymLinks
            AllowOverride all
            Order Deny,Allow
            Allow from all
        </Directory>       
</VirtualHost>
