### ISSUE TITLE
Comments not showing up on administration side to approve

### ISSUE THREAD

**Issue by designer230** [pagekit/pagekit#461]
When I am logged into my site on the front side I can see that there are comments that are needing approval. See image below:
<img width="1202" alt="screenshot 2015-09-23 20 20 05" src="https://cloud.githubusercontent.com/assets/14814568/10064041/99896804-6231-11e5-981a-5b669d73a5ed.png">

But when I am logged into my site on the administration back end there are no comments listed to approve. See image below:
<img width="1298" alt="screenshot 2015-09-23 20 20 19" src="https://cloud.githubusercontent.com/assets/14814568/10064045/b43029b8-6231-11e5-9b02-452ec6245fde.png">

**Comment by MalteScharenberg** [comment]
I can't reproduce this behavior. Did you test with latest develop versions (Pagekit and Blog)?

**Comment by designer230** [comment]
Running the latest version you can download from the official site:

<img width="962" alt="screenshot 2015-09-24 08 06 08" src="https://cloud.githubusercontent.com/assets/14814568/10075498/48fba868-6293-11e5-8c35-1ab9877bb008.png">

**Comment by janschoenherr** [comment]
There seems to be a Javascript error on your site. Could you open the Developer Toolbar in your browser and check for the error? Thanks.

**Comment by designer230** [comment]
Ok in the browser console these are the errors I'm seeing on the front end where I can see the comments pending:

2 JavaScript Errors
Failed to load resource: the server responded with a status of 404 (Not Found)
http://gravatar.com/avatar/b642b4217b34b1e8d3bd915fc65c4452?r=g&d=mm&s=80&d=404 

http://gravatar.com/avatar/e381ed136985e4ccb529182fb88b421b?r=g&d=mm&s=80&d=404 
Failed to load resource: the server responded with a status of 404 (Not Found)

On the backend where I cannot see the pending comments to approve there are a few errors as well they are:

http://randomdrive.com/api/blog/comment?filter%5Bfilter%5D%5Bsearch%5D=&filter%5Bfilter%5D%5Bstatus%5D=&post=0&page=0&limit=20 Failed to load resource: the server responded with a status of 403 (Forbidden)

Uncaught (in promise) XMLHttpRequestdata: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">↵<html><head>↵<title>403 Forbidden</title>↵</head><body>↵<h1>Forbidden</h1>↵<p>You don't have permission to access /api/blog/comment↵on this server.</p>↵</body></html>↵"ok: falseonabort: nullonerror: nullonload: nullonloadend: nullonloadstart: nullonprogress: nullonreadystatechange: ()ontimeout: nullreadyState: 4response: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">↵<html><head>↵<title>403 Forbidden</title>↵</head><body>↵<h1>Forbidden</h1>↵<p>You don't have permission to access /api/blog/comment↵on this server.</p>↵</body></html>↵"responseText: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">↵<html><head>↵<title>403 Forbidden</title>↵</head><body>↵<h1>Forbidden</h1>↵<p>You don't have permission to access /api/blog/comment↵on this server.</p>↵</body></html>↵"responseType: ""responseURL: "http://randomdrive.com/api/blog/comment?filter%5Bfilter%5D%5Bsearch%5D=&filter%5Bfilter%5D%5Bstatus%5D=&post=0&page=0&limit=20"responseXML: nullstatus: 403statusText: "Forbidden"timeout: 0upload: XMLHttpRequestUploadwithCredentials: false__proto__: XMLHttpRequest

If i'm reading this right is it my webserver cannot access the folder and that is causing the issue?

**Comment by designer230** [comment]
Ok I figured it out it was a mod security issue.
