### ISSUE TITLE
No CLI command for themes:generate

### ISSUE THREAD

**Issue by ajwhite** [pagekit/pagekit#462]
The docs describe [creating the theme boilerplate](https://github.com/pagekit/docs/blob/master/themes.md#basic-structure) from command line, but there [doesn't appear to be any actual theme command](https://github.com/pagekit/pagekit/tree/0.9.1/app/console/src/Commands). Are the docs just ahead of the development?

<img width="1004" alt="screen shot 2015-09-23 at 11 20 32 pm" src="https://cloud.githubusercontent.com/assets/656630/10064735/b7e7fb68-6249-11e5-98c2-955474813644.png">

Also a note that it doesn't appear that extensions can be generated at this time either

**Comment by MalteScharenberg** [comment]
The docs are outdated. We are currently reworking them at the develop branch.

The theme/extension commands are temporarily removed.

**Comment by ajwhite** [comment]
Oh man, didn't even think to check the branches since I was in a wiki-mindset. Thank you!
