### ISSUE TITLE
Location widget clock type settings

### ISSUE THREAD

**Issue by csakiistvan** [pagekit/pagekit#463]
Hello Guys,

I see on dasboard the location widget and I think many country don't use AP/PM clock type. I think the best way if you enable the set this clock type to the users, same like weather units value.

BR

**Comment by janschoenherr** [comment]
Currently the clock type is determined by the _Admin Locale_. If you want an English Admin area, you could switch to British English. That will give you the 24h clock.

**Comment by csakiistvan** [comment]
I think it is an other use case. If you add a settings possibility to Unit, I think you need to it to the clock type too.
