### ISSUE TITLE
Weather location district is not correct on Hungarian language

### ISSUE THREAD

**Issue by csakiistvan** [pagekit/pagekit#464]
Hello Guys,

I set Budapest to the location widget, the service offer to me so I can select my district too. But the translated string is not right. 

Not right: keruelet
Right: kerület

You can check this tring on Google Translate too https://translate.google.com/#hu/en/ker%C3%BClet 

![kerület](https://www.evernote.com/l/AA0v9o4RC8lNE4TG3UG7gCsm6lDrGW347EkB/image.png)

**Comment by MalteScharenberg** [comment]
Since these data originates from openweathermap.com, we can't change it. 

By the way, in german 'ü' and 'ue' means the same.

**Comment by csakiistvan** [comment]
OK, thanks I send this to openweathermap.com
