### ISSUE TITLE
Problem with non-latin symbols

### ISSUE THREAD

**Issue by Vslow** [pagekit/pagekit#465]
upd. There is a problem with a lot of non-latin symbols, including emoji, Chinese and other.

It seems, there is a problem with cyrillic text in current release (0.9.1). If u put a lowercase! letter "ш" as a part of page title or content (and in blog posts too) u will get following:
1. In frontend u will see "�?" instead of letter "ш"
2. In backend if u will return to page edit u will get completely empty header and content
3. In phpMyAdmin u will see symbols like "Р“Р»Р°РІРЅР°СЏ" instead of any cyrillic text.

I believe that in server's settings everything set right, charset "UTF-8".

System info:
> Web Server:	Apache/2.4.12 (FreeBSD) PHP/5.6.11
> Database: Driver	- mysql, Version - 5.1.41-log

**Comment by Vslow** [comment]
Just tested Chinese, got same result:
> Should be: "Page is under development 我是男人".
> In frontend: "Page is under development �?��?�男人".
> In backend: after returning to page-editing there is nothing in title and content.
> In phpMyAdmin: "Page is under development ж?‘ж?Їз”·дєє".

**Comment by b2z** [comment]
I can not replicate and have a correct Cyrillic display in the URLs and on the website. Check you server settings and DB settings for correct encoding.

**Comment by Vslow** [comment]
@b2z, Thank you for your reply.

Ok, I dont have enough knowledge to fully understand this problem, but this is how I see it.

I am not the only one who gets this kind of problem, #434 looks like the same problem, in Gitter @surgun9 and @4nxiety seem to succeed to replicate the problem.

I have a virtual hosting and in my MySQL settings as my "character_set_server" and "collation_server" I have "cp1251". As I understand my hosting provider will not change this variable cause I have virtual hosting. They think everything works perfectly with using query "SET NAMES utf8" immediately after connection. But as I understand this is not working since PHP 5.5.0 because it is old and we are using PDO. Am I right about this and is there some decision for this situation?

**Comment by b2z** [comment]
Well you have a bad provider :( Consider to read [this article](http://phpfaq.ru/charset#repair) - not everything can be solved using `SET NAMES`.

cp1251 is bad, it is narrowing the usage drastically. I advice you to move to another provider who supports UTF8 normally. There is nothing Pagekit can do about it (any CMS will have such problems).

**Comment by janschoenherr** [comment]
For testing, could you try to edit _/app/modules/database/index.php_

and add to the $default array like this:

    $default = [
        'wrapperClass' => 'Pagekit\Database\Connection',
        'driverOptions' => [PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'UTF8'"]
    ];

**Comment by Vslow** [comment]
@janschoenherr didn't see your reply and I added a line to /pagekit/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php

```php
            $conn = new PDOConnection(
                $this->constructPdoDsn($params),
                $username,
                $password,
                $driverOptions
            );
            $conn->query("SET NAMES utf8");
```

And it seems to work fine.

And now I reverted my changes and tried your solution and it worked too. Thank u.
Will u consider adding this into further releases?

**Comment by b2z** [comment]
@Vslow as I referenced earlier `SET NAMES` does not solve all the problems, so it's not a complete solution. My advice is still valid - use UTF8 encoding for smooth performance and stability :wink:

**Comment by Vslow** [comment]
@b2z thank u. I understand it. I hope my provider will change server encoding someday and everything will be perfect. I am not yet ready to change provider because of it's convenience and stability (comparing to other providers I used).
