### ISSUE TITLE
Backend - wrong non-Latin symbols in URL display

### ISSUE THREAD

**Issue by b2z** [pagekit/pagekit#467]
1. Proceed to Pages -> Add Page -> choose some non-Latin URL for page (for example - `документация`) -> Save.

2. In the list of pages the URL will be displayed as `/%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F`.

3. Unpublish this page. The URL will be displayed as `документация`.

The same problem applies to Blog extension - it will always display URL like `/%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F` (publish/unpublish does not affect the display like for Page).

**Comment by janschoenherr** [comment]
Fixed with 80aff088b48500f82c0a5480789e428e46d5727d
