### ISSUE TITLE
Login not working in PHP7

### ISSUE THREAD

**Issue by luismaster** [pagekit/pagekit#469]
Hello!
Pagekit, I installed on a local server using Bitnami MAMP Stack - 7.0 0RC3, this Stack runs under php7.

The installation was a success, the problem arises when I try to log in the administrator for some reason won't let me log in and does not report any error to me.

**Comment by janschoenherr** [comment]
We have reworked the authentication process in Pagekit. If you are still experiencing this issue after the next update, please reopen this issue. Thanks.
