### ISSUE TITLE
Cannot install on IPv6 only host

### ISSUE THREAD

**Issue by xmob** [pagekit/pagekit#470]
The installer pulls certain files from www.pagekit.com during installation (e.g. http://pagekit.com/packages.json).

Because www.pagekit.com only resolves to IPv4 this fails on IPv6 hosts.  Any chance of getting IPv6 support for www.pagekit.com?

**Comment by janschoenherr** [comment]
Sorry, it seems that this seems to be a limitation of our hosting provider.
