### ISSUE TITLE
Fatal error when updating theme (One)

### ISSUE THREAD

**Issue by bwhitty** [pagekit/pagekit#472]
I tried updating the One theme to 0.9.1 and I get the following in the ajax response.
```
Fatal error:  Call to a member function getName() on null in /home/user/domain/app/installer/src/Controller/PackageController.php on line 157
```

I'm running PK 0.9.1 on SQLite w/ Apache, fastcgi, PHP 5.6.10

**Comment by MalteScharenberg** [comment]
Thanks for reporting!
https://github.com/pagekit/pagekit/commit/febb968be9c148f97cbb8040fef81161c358b932 addresses this issue.
