### ISSUE TITLE
Updating and installing some packages fails

### ISSUE THREAD

**Issue by bwhitty** [pagekit/pagekit#473]
When I try to update or install some extensions/themes, the network request seemingly stalls. What I see is a the white box (which usually starts to stream information like "Loading composer repositories with package information"), but no data ever comes back. It then seems to time out and the following is displayed: ```Invalid parameters. Status = error```

One interesting note is that this works in my local environment running the built-in php web server, but does not work on my host running PHP 5.6.10 on Apache in fastcgi mode. 

I've seen this behavior with the Pagekit Analytics plugin and the Formmaker plugin, both before and after updating to 9.3. I was able to update the Blog extension and One theme fine, though. I did a full sweep of my directory structure's permissions and they're in check. All permissions are green from the system tab.

**Comment by MalteScharenberg** [comment]
Can you check the request payload? What is the contents of `package`?

**Comment by bwhitty** [comment]
For Analytics extension installation:

```javascript
package: {
    author: {name: "Pagekit", email: "info@pagekit.com", homepage: "http://pagekit.com"},
    email: "info@pagekit.com",
    homepage: "http://pagekit.com",
    name: "Pagekit",
    created: "2015-09-07T17:17:48+0000",
    description: "An analytics extension for your dashboard.",
    extra: {image: "http://downloads-pagekit.storage.googleapis.com/pagekit/analytics/image.jpeg"},
    image: "http://downloads-pagekit.storage.googleapis.com/pagekit/analytics/image.jpeg",
    name: "pagekit/analytics",
    title: "Analytics",
    type: "pagekit-extension",
    updated: null,
    version: "0.9.0",
    version_normalized: "0.9.0.0"
}
````

For Formmaker extension update:

```javascript
package: {
    author: {name: "Bixie", email: "info@bixie.org", homepage: "http://formmaker.bixie.org"}
    created: "2015-09-09T12:26:45+0000",
    description: "Create forms in your Pagekit site. Build forms and manage the submissions.",
    extra: {image: "http://downloads-pagekit.storage.googleapis.com/bixie/formmaker/image.jpeg"},
    name: "bixie/formmaker",
    title: "Formmaker",
    type: "pagekit-extension",
    updated: "2015-09-09T18:09:22+0000",
    version: "1.2.2",
    version_normalized: "1.2.2.0"    
}
```

**Comment by MalteScharenberg** [comment]
Looks good...Can you provide access to your site and `var_dump` `$package` in `app/installer/src/controller/PackageController.php` at line 164?

**Comment by bwhitty** [comment]
Interesting, dumping `$package` directly before and after the call to `App::package()->load()` yield this in the ajax response:

```
array(0) {
}
NULL
Invalid parameters.
status=error
```
So somehow the information is being dropped before even getting there.

**Comment by bwhitty** [comment]
Well, some new information. Maybe this can help someone else along the way.

I found some vague errors in the server's error log:
```
Premature end of script headers: index.php, referrer: http://www.domain.com/admin/system/package/extensions
```

I did some google'ing and found that it is sometimes an error thrown in fastcgi mode when the script does not return any output within a given time window: http://stackoverflow.com/questions/4336757/500-server-error-premature-end-of-script-headers

So, I updated the server config to be non-fastcgi. I get some response data:
```
Loading composer repositories with package information
```

Request still never completes. I did a `chmod -R 755` on every file associated to the app. This allowed me to be able to update/install the Pagekit Google Analytics plugin and the blog extension, but `bixie/formmaker` still fails:

I get some more data back
```
Loading composer repositories with package information
Updating dependencies
Updating dependencies
```
but it still never completes.

**Comment by dungphanxuan** [comment]
i have error when install 
Installation failed!

The contents of http://pagekit.com/package/pagekit/blog%247e3ec449993dac0122a6f3ea19865798652f7c7897b2f497f90e43d5aa832be7.json do not match its signature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.

that what error? so can i fix it?

**Comment by MalteScharenberg** [comment]
We reworked package installation and the installer for the next release. Please reopen if the issue still exists.
