### ISSUE TITLE
disqus support

### ISSUE THREAD

**Issue by HoshinoTouko** [pagekit/pagekit#475]
Excuse me. I try to add disqus comment to my site, but I couldn't find which file I can modify to change the number of comments.

**Comment by florianletsch** [comment]
How did you add the disqus comments exactly?

**Comment by HoshinoTouko** [comment]
@florianletsch Just replace the comments.php by Disqus universal code. All things goes well expect what I refered.

**Comment by florianletsch** [comment]
Shouldn't this be a setting on the Disqus side of things? So either configure it in their web interface or set a specific parameter when including the universal code. 

Sorry, I haven't used Disqus before, but I can't imagine how Pagekit should be able to determine what the included third party JS renders on the page.

Correct me if I'm missing something.

**Comment by HoshinoTouko** [comment]
@florianletsch The thing need to do is to register an account and do some adjustment at its dashboard. Then repalce comment.php. It works well thanks to responsive design. The only problem is to show {num}Comments.

**Comment by alomvar** [comment]
Following [in DISQUS documentation](https://help.disqus.com/customer/portal/articles/472097-universal-embed-code) I would suspect @HoshinoTouko means [integrating the comment count of DISQUS comments](https://help.disqus.com/customer/portal/articles/565624-tightening-your-disqus-integration) into the template.
