### ISSUE TITLE
autosave 

### ISSUE THREAD

**Issue by satriyowibowo** [pagekit/pagekit#482]
please add auto save feature to pagekit
hate losing long written ideas just by accidentaly closing browser tab

**Comment by florianletsch** [comment]
I think I'd prefer blocking the close action with the common message "you have unsaved changes, do you really want to exit"?

Note: While your cursor is in the editor, you can just to CTRL+S to save without having to move your mouse. Makes it easy to save your draft frequently. :)

**Comment by satriyowibowo** [comment]
nope, i tried ctrl + s and the result is i got a blank page
the url still displaying the post's url
e.g. http://mydomain.com/admin/blog/post/edit?title=mypostname
but it just looks like a new blank post
![blank](http://i.imgur.com/dLkBhaY.png)

**Comment by satriyowibowo** [comment]
still cannot save draft with Ctrl + S

**Comment by janschoenherr** [comment]
Are you running the latest Pagekit version?

**Comment by florianletsch** [comment]
In the last release, we have included a detection for timed out sessions. Instead of losing your work, you will now be prompted to enter your credentials. Afterwards, the editor saves as usual.
