### ISSUE TITLE
mounting error

### ISSUE THREAD

**Issue by wantline** [pagekit/pagekit#483]
安装失败
The "https://pagekit.com/package/pagekit/blog/0.9.2.zip" file could not be downloaded: failed to open stream: Connection timed out

**Comment by florianletsch** [comment]
1. When does this happen? Can you specify what steps you were going through? 
2. Are you able to download the zip manually from where you are located? Maybe a firewall is preventing the download?

**Comment by wantline** [comment]
The last step in the installation

**Comment by wantline** [comment]
I made it, thank you very much
