### ISSUE TITLE
Updating to 0.9.5 breaks admin

### ISSUE THREAD

**Issue by bwhitty** [pagekit/pagekit#485]
Just updated to 0.9.5 from 0.9.3 (running the built-in PHP web server) and the admin interface is now completely hosed:

<img width="1440" alt="screen shot 2015-10-31 at 9 55 15 am" src="https://cloud.githubusercontent.com/assets/1571966/10864002/8eb641da-7fb5-11e5-9e3d-1bc3aed55ec7.png">

It appears `view-form` is not loading correctly:

```
 Error: Cannot find module "vue-form" at http://localhost:9000/app/system/app/bundle/vue.js:1:273
```

Second error:
```
TypeError: this.$resource is not a function at i.window.Dashboard.t.exports.created (http://localhost:9000/app/system/modules/dashboard/app/bundle/index.js:1:364)
```

Looking deeper into the code, if I go to `app/assets/vue-form`, there is only a `bower.json` file. There were no errors during update.

**Comment by feamor84** [comment]
Same errors during clean installation, in second step there is empty dialog box for language and next button doesn't respond

**Comment by b2z** [comment]
Same problem...

**Comment by ecmel** [comment]
+1

**Comment by janschoenherr** [comment]
Sorry for the trouble, we had trouble with the build. We've reuploaded the install package now. Thanks.

**Comment by b2z** [comment]
@janschoenherr how to update existing 0.9.5? Just unzip?

**Comment by janschoenherr** [comment]
Yes, just copy it over your existing installation.

**Comment by Jonathlee** [comment]
I'm stuck on new installation, during installation, after filled the Site title, username, password, the page stuck on preloader screen. I tried re-install but no avail...
