### ISSUE TITLE
Can't install 0.9.5, empty language list

### ISSUE THREAD

**Issue by tranduyhung** [pagekit/pagekit#486]
I can't install 0.9.5, there is no languages listed in the first step "Choose language". There are 2 errors in the browser's console:

    Error: Cannot find module "vue-form"
    app/system/app/bundle/vue.js
    Line 1

    TypeError: this.$resource is not a function
    app/installer/app/views/installer.js
    Line 16

**Comment by ecmel** [comment]
+1

**Comment by hodatovich** [comment]
+1

**Comment by ecmel** [comment]
Just cleared the saved password from the previous install and now it works.

**Comment by ooploopl-** [comment]
+1

**Comment by laxtiz** [comment]
+1

**Comment by Pazys** [comment]
+1

**Comment by janschoenherr** [comment]
Sorry for the trouble, we've reuploaded the install package. Thanks.

**Comment by tranduyhung** [comment]
Thank you! Love it!
