### ISSUE TITLE
Type not found Error - Adding New Page

### ISSUE THREAD

**Issue by edgr** [pagekit/pagekit#489]
Hello,

I am getting the following error whenever I try to edit/add a page or link. 

"Type not found."

I'm using Nginx 1.6/HHVM.

Thanks

**Comment by janschoenherr** [comment]
Not sure about the "Type not found." error. But it would be great to take a look at your Nginx config. Maybe we can add this to Pagekit as a default config. Thanks.

**Comment by MalteScharenberg** [comment]
Please reopen if the issue still exists.
