### ISSUE TITLE
Users with roles except administrator are not able to login

### ISSUE THREAD

**Issue by chagamkamalakar** [pagekit/pagekit#491]
I created one user and created new role Editor & activated (status  is blue for new user .) and given permissions as well.
now user has 2 roles (Authenticated & Editor) 
now i am trying to login , it is not letting me login saying you need to have admin rights.

Am i doing wrong ?

**Comment by chagamkamalakar** [comment]
sorry the problem was i didn't assign 'Access admin area' to the role.

**Comment by janschoenherr** [comment]
It is still in beta and it might change a bit until its final release. Can't promise right now as to what those changes will be.

**Comment by chagamkamalakar** [comment]
thanks @janschoenherr 
are those going to breaking  changes  or insignificant ? 
i am really excited to use this CMS for my work. as  it's simple.. giving me meaningful & powerful user management system .. it's needed for my work.
