### ISSUE TITLE
Favicon doesn't show correctly.

### ISSUE THREAD

**Issue by kengone** [pagekit/pagekit#492]
I uploaded and set favicon and logo, frontend continues to show me pagekit default favicon icon.

**Comment by florianletsch** [comment]
Most browsers do pretty heavy caching on favicons. Can you try with a fresh browser session (i.e. different browser, test on different device?)

**Comment by florianletsch** [comment]
I have tried with the current version and it works for me (tested with Firefox and Chrome). If this stilll doesn't work for you, please provide more details about your browser or provide a link to your site where this is happening.
