### ISSUE TITLE
Media files missing in repo

### ISSUE THREAD

**Issue by tranduyhung** [pagekit/pagekit#494]
I  installed Pagekit from source and found out that the following files didn't exist in the develop and master branches:

storage/pagekit-logo-contrast.svg
storage/pagekit-logo.svg
storage/home-hero.jpg
storage/pagekit-logo.svg
storage/pagekit-logo-contrast.svg

Is there any reason why they are not stored on the repo? Or did I miss any step in installation?

**Comment by florianletsch** [comment]
Thanks for your feedback.

The logo files have been added to the storage folder in the mean time. We prefer not to add the home-hero.jpg to the repo, as we'd like to limit the binary blobs we have included. Instead, we are adding this file to every build file before uploading it.
