### ISSUE TITLE
Pagekit wont load on my wamp 2.5 testing / development server and displays error!!

### ISSUE THREAD

**Issue by wmfx** [pagekit/pagekit#495]
. During the install I get error message The "https://pagekit/packages.jason" file could not be downloaded: php_network_getaddress: getaddress: getaddrinfo failed: no such host is known. failed to open stream: php_network_getaddress:getaddrinfo failed: no such host is known.

**Comment by janschoenherr** [comment]
Did you try another browser?

**Comment by xorinzor** [comment]
did you manually type the url in your post or did you copy it?
if you copied it, did you set "pagekit" in your hosts file to point to your localhost and did you create a vhost for wamp?

Usually you should just leave the url at localhost, unless you have a dedicated development environment running multiple applications, in which case using multiple vhosts is recommended.

**Comment by Auserus** [comment]
Similar problem, installation by default on a hosting (in different browsers: Firefox, Chrome) - 
The "https://pagekit.com/packages.json" file could not be downloaded: failed to open stream: Connection refused

**Comment by MalteScharenberg** [comment]
The next Pagekit release (and current dev branch) will install without external connections. So this issue is circumvented for the installer, but in certain circumstances not for the marketplace. 
If the issue persists, please open a new issue.
