### ISSUE TITLE
Installation failed caused of packages.json could not be downloaded

### ISSUE THREAD

**Issue by masteryega** [pagekit/pagekit#501]
Hi,

I have getting an error while trying installation "packages.json could not be downloaded : allow_url_fopen must be enabled in php.ini"... . I don't have server permisions and i try to add ini_set('allow_url_fopen',1); function in index.php. But it didn't help. How can i solve this issue ?

Kind Regards
Omer

**Comment by janschoenherr** [comment]
Currently that seems to be a requirement for Composer. Your host might be preventing you from setting _ini_set('allow_url_fopen',1); _ at runtime.

http://php.net/manual/en/filesystem.configuration.php

**Comment by armandzwan** [comment]
Same here. :-( Host won't allow allow_url_fopen because it's insecure.
