### ISSUE TITLE
Error on installation - Process.php on line 283

### ISSUE THREAD

**Issue by an0nym** [pagekit/pagekit#506]
Hello all, 
I'm trying to install Pagekit on my server and Im getting this error when I change the debugger to true on config.php on the last step of installation as below

<br />
<b>Warning</b>:  proc_open(): CreateProcess failed, error code - 5 in <b>E:\HostingSpaces\badjian\armanpaya
.net\wwwroot\pagekit\app\vendor\symfony\process\Process.php</b> on line <b>283</b><br />
{"status":"no-tables","message":"Unable to launch a new process."}

I really appreciate if you can help me solve this issue. 

Thanks.

**Comment by SAFAD** [comment]
Please apply this Patch and report back 
https://github.com/symfony/symfony/commit/e76561dbc0e9a93f38455a76603b1fa881edbbbb

**Comment by MalteScharenberg** [comment]
The next Pagekit release (and current dev branch) comes with a reworked installer. 
Please open a new issue if problems occur.
