### ISSUE TITLE
Session timeout resulting in lost work

### ISSUE THREAD

**Issue by mattwoolnough** [pagekit/pagekit#508]
I'm having issues with sessions expiring.  I save the work, then come back to the page to find the work missing. I presume this is due to session timeouts & will modify locally.
   
It appears as though the session is set to 900 (15 mins) in  /app/system/config.php.

A mechanism to reconfigure the timeout would be good.
A more noticable alert when the ui can't save would also be good.

**Comment by florianletsch** [comment]
Thanks for your suggestions. Yes, we will need to make the session time configurable, I agree.

In the meantime, if it's your own machine you are working on, you can enable "Stay logged in" in the login interface and it won't log you out automatically.

**Comment by florianletsch** [comment]
The new release 0.10.2 will fix this. We've included a check to see if the session has expired. If that is the case, a modal window will pop up that asks you to login in. Your changes will then be saved without losing them.
