### ISSUE TITLE
[bug] Can't connect as administrator

### ISSUE THREAD

**Issue by unpeudetout** [pagekit/pagekit#510]
Hi !
I can't connect as administrator, I am blocked on the page user / authentication.
I have en blank page, without redirection.
But if I log with a wrong password, i'm not blocked and a error message (invalid password) appears !
My website with Pagekit : https://astucesweb.fr
Noam

**Comment by unpeudetout** [comment]
I really need this access, please help me.

**Comment by aqnouch** [comment]
@unpeudetout, Do you have access to you website database?

**Comment by unpeudetout** [comment]
Yes, of course !

**Comment by aqnouch** [comment]
Good, try to verify if the admin has the correct roles and permission,
and try to manually activate the debug mode, to be able to have more details about the problem

**Comment by unpeudetout** [comment]
I don't find the option debug mode in my database. Where is it ?
Thanks,
Noam

**Comment by aqnouch** [comment]
to activate the debug mode, you need to edit the config.php (in the root of your project) 
you have to change two values from false to true:

debug' => false,

and

  'debug' => 
  array (
    'enabled' => false,
  ),

**Comment by unpeudetout** [comment]
I have activated the debug mode, and it's... the end of the world.
![screenshot_159](https://cloud.githubusercontent.com/assets/13904910/12074825/6dca35b2-b16a-11e5-92d8-bf290b44e9b5.png
![screenshot_160](https://cloud.githubusercontent.com/assets/13904910/12074841/10732b20-b16b-11e5-8b66-cc1734bcd601.png)
)

**Comment by aqnouch** [comment]
:disappointed: 
I have a proposition:
try to add 
$platform->registerDoctrineTypeMapping('enum', 'string');

under         $platform = $this->connection->getDatabasePlatform(); (line 140) on 
app/modules/session/src/Handler/DatabaseSessionHandler.php

**Comment by unpeudetout** [comment]
Hi !
Thanks, it's working and I erase trycial_annotations table and all it's working.
Thanks a lot,
Noam

**Comment by aqnouch** [comment]
:smile: you're welcome
