### ISSUE TITLE
Installer not finishing...Help needed newbie here

### ISSUE THREAD

**Issue by j2d555** [pagekit/pagekit#511]
Hi,

I was installing pagekit on my shared hosting. I have uploaded pagekit using filezilla and started the installation.

I have connected to database, filled site details and click on installer. Everything was smooth till this step. Then the installer is not finishing the installation
![capture](https://cloud.githubusercontent.com/assets/16387155/11934822/5f97de98-a82a-11e5-81db-5e9159142646.PNG)
. it's been 1 hour now the process is still  going on see the screenshot (my domain name is masked and edited by me).

I was confused, so I loged into my database. Shockingly there is no tables created by pagekit installer, even after 1 hour.

Please help me.
J2D555

**Comment by nakamuraagatha** [comment]
i have same problem

**Comment by j2d555** [comment]
@nakamura, sadly no one found a solution yet... Lets find a solution together.

**Comment by gOzaru** [comment]
I think it is installing the php extension as the requirement those have to exist to be installed.
I have installed for 24 hours and still not finishing, accessing joomla is forbidden.
damn. this take a very long time.

**Comment by janschoenherr** [comment]
Did you guys notice any javascript error in the debug console?

**Comment by davidgorges** [comment]
Don't know if it is related, I got the following error:

> #### Installation failed!
>
> The contents of     http://pagekit.com/package/pagekit/blog%247e3ec449993dac0122a6f3ea19865798652f7c7897b2f497f90e43d5aa832be7.json do not match its signature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.

<img width="496" alt="screenshot-pagekit" src="https://cloud.githubusercontent.com/assets/3885619/12229222/614bb838-b7fa-11e5-90e4-203955dd0e92.png">

**Comment by floriansemm** [comment]
I had a similar problem in, see #523

Was fixed in https://github.com/pagekit/pagekit/commit/674a8411df2853b3d960794ba87c66e4a8f92ddc

**Comment by leefouce** [comment]
i have same problem,and Warning: zlib_decode(): data error

**Comment by MalteScharenberg** [comment]
@leefouce please clear the composer cache (`tmp/temp/composer`) and try again.

**Comment by MalteScharenberg** [comment]
The next Pagekit release (and current dev branch) comes with a reworked installer. 
Please open a new issue if problems occur.
