### ISSUE TITLE
Username validation in installer

### ISSUE THREAD

**Issue by KevinSupertramp** [pagekit/pagekit#513]
Hello,

I think there's no username validation in the installer because I could use my email address as username but it's said in the documentation that only alphanumeric characters, numbers, dot and underscore are allowed.

I checked in the source but couldn't find anything about it. I'm hope I'm not wrong !

Best regards

**Comment by florianletsch** [comment]
Fixed via https://github.com/pagekit/pagekit/commit/7d06acf6771d8be1a71f9f67e95d99e41ffd8498
