### ISSUE TITLE
Internal server error caused by `MYSQL_ATTR_INIT_COMMAND`

### ISSUE THREAD

**Issue by sasindumendis** [pagekit/pagekit#516]
I was trying to install the latest Pagekit (0.10.1) with PHP built-in web server and SQLite on Ubuntu. 

STEPS I FOLLOWED:

1. Extracted Pagekit archive into  `/.../pagekit/`directory.
2. Launched PHP dev server. `cd /.../pagekit/ && php -S localhost:8000`
3. Visited `http://localhost:8000` on browser.

WHAT I SAW:

- `http://localhost:8000` gave a blank screen instead of the installation wizard.
- PHP dev server gave `Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /.../pagekit/app/modules/database/index.php on line 85`.

```php
// app/modules/database/index.php line 85

'driverOptions' => [
     PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8 COLLATE utf8_unicode_ci'
]
```
Obviously I didn't have MySQL installed and configured but ideally that shouldn't be a problem because I was going to use SQLite. Commenting out `PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8 COLLATE utf8_unicode_ci'` fixed the problem and I was able to complete the installation. However uncommenting it after the installation caused 500 error again.

SYSTEM:
- PHP 5.6.10
- SQLite 3.8.2
- Required PHP modules installed: JSON, Session, ctype, Tokenizer, SimpleXML, DOM, mbstring, PCRE 8.0+, ZIP, PDO, pdo_sqlite, sqlite3, cURL, iconv.

**Comment by YChebotaev** [comment]
Just note that i have same issue except i downloaded and extracted [latest](http://pagekit.com/api/download/latest) archive from an official site and use php-fpm module on nginx.
Here's my [phpinfo](http://pastebin.com/dhNY8uLb).
