### ISSUE TITLE
Anonymous Comment Posting

### ISSUE THREAD

**Issue by NetOperatorWibby** [pagekit/pagekit#518]
It would be incredibly helpful for new users if the checkbox for "Post comments" in the Anonymous section of User Roles, was checked by default. I searched Gitter, this Issue tracker, and the blog for answers to this issue, before figuring it out for myself.

It seems really silly to see "Leave a comment" or "Please login to comment" after a post, only to find that there isn't a login link or a comment form.

—

I'm working on transferring my girlfriend's Wordpress blog over to PageKit and am quite pleased with how lightweight it is. This comment posting issue and some grammatical errors in the documentation show that there is still a lot to do, but I hope for quick progress.

I intend to keep using PageKit for client projects and possible creating my own plugins for the community in 2016.

**Comment by MalteScharenberg** [comment]
The next blog version will also provide a link to the login page for non authenticated users (https://github.com/pagekit/extension-blog/commit/030cc7fcbddfdcaaaadaebbb08c7ce7892fc5fa7).

**Comment by NetOperatorWibby** [comment]
Nice! Do you have an ETA for the next version?

**Comment by MalteScharenberg** [comment]
Next minor release should be at the end of this week or early next week.
