### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Smeaven** [pagekit/pagekit#520]
* Cannot add/save roles `Uncaught TypeError: Cannot read property 'save' of undefined`
* Blog - Placeholder not replaced
   * *Geschrieben von %Name% am %Date%* oder *% Num % Kommentare*
* Editor - no markdown inside html5-tags

**Comment by KevinSupertramp** [comment]
Hi,

For adding new roles, it's fixed in the "develop branch" : https://github.com/pagekit/pagekit/commit/ec2650e78ccbe17b3ed1f09c04f62a9d6fbdaabe

**Comment by MalteScharenberg** [comment]
Thanks for reporting!

Placeholders in german language strings are now fixed as well and as far as I know it is correct not to parse markdown inside of html tags.

Best regards
