### ISSUE TITLE
On nginx, php7, sqlite got db error.

### ISSUE THREAD

**Issue by quaritexa** [pagekit/pagekit#522]
Database error: An exception occurred while executing 'CREATE UNIQUE INDEX SYSTEM_CONFIG_NAME ON test_system_config (name)': SQLSTATE[HY000]: General error: 1 index SYSTEM_CONFIG_NAME already exists

**Comment by florianletsch** [comment]
Is it possible you are trying to install a second Pagekit instance in the SQLite database? Can you try to remove the `*.db` file and re-run the installation please?

**Comment by MalteScharenberg** [comment]
Fixed with latest release.
