### ISSUE TITLE
Select sqlite, press install, got error «man-in-the-middle attack»

### ISSUE THREAD

**Issue by quaritexa** [pagekit/pagekit#523]
The contents of pagekit.com/package/pagekit/blog%247e3ec449993dac0122a6f3ea19865798652f7c7897b2f497f90e43d5aa832be7.json do not match its signature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake

**Comment by floriansemm** [comment]
same issue here with php 5.6.9 and mysql 5.5

**Comment by floriansemm** [comment]
@quaritexa After I created a pagekit account the installation was successful, see http://pagekit.com/user/login

**Comment by MalteScharenberg** [comment]
Please try with my referenced commit. Delete `tmp/temp/composer` before installing.

**Comment by floriansemm** [comment]
@MalteScharenberg works fine! +1

**Comment by quaritexa** [comment]
Good.
