### ISSUE TITLE
webpack error during installation about "vue-intl" and "vue-resource"

### ISSUE THREAD

**Issue by hanlan** [pagekit/pagekit#525]
I am installing pagekit on my local, git clone -> success, after running npm and bower, I got 2 error msgs when run webpack, which said the vue-intl and vue-resource is not found, I checked the files, the "src" folder is missing under /app/assets/vue-intl and /app/assets/vue-resource

I solved the problem temporary by add the src folder which I copied from dist package.

Is there anything to do about this issue?

Thanks.

**Comment by MalteScharenberg** [comment]
Try to delete both folders and run `bower install`. Source folders should be available then.

**Comment by hanlan** [comment]
@MalteScharenberg thanks, but I tried, still only these 2 don't have the src folders installed by bower, the others like vue-form is ok.

**Comment by janschoenherr** [comment]
Please make sure you have the latest releases of Npm and Bower installed.

**Comment by MalteScharenberg** [comment]
If the issue still exits, please reopen.

**Comment by hanlan** [comment]
@MalteScharenberg sure will do

**Comment by hanlan** [comment]
the issue is still there, bower install vue-intl, the src folder is ignored, but vue.js is requiring from src/

**Comment by MalteScharenberg** [comment]
Use a clean clone from the repository and run `npm install` or just download the [latest release](https://github.com/pagekit/pagekit/releases).
