### ISSUE TITLE
Request: Commit `composer.lock` File

### ISSUE THREAD

**Issue by adamgoose** [pagekit/pagekit#528]
Excited to try your app! However, during install, I noticed that you do not commit the `composer.lock` file in your repository. In my experience, committing this file allows better control over which versions of libraries should be installed on a person's machine. Thus, you have a more consistent tagged release.

Just a suggestion. :)

**Comment by nbpalomino** [comment]
+1 Agree.

Sometimes on a small VPS, composer install with a composer.lock is faster.

Refer to this issue on composer:
https://github.com/composer/composer/issues/1898#issuecomment-25632080
