### ISSUE TITLE
Youtube video url adding Error

### ISSUE THREAD

**Issue by labasus** [pagekit/pagekit#533]
Latest  0.10.2 version

I'm trying to insert to the page just a youtube URL and if the "loop" does not checked - I've got an error

ContextErrorException in VideoPlugin.php line 50: Notice: Undefined index: loop

**Comment by labasus** [comment]
Video format dimensions are missed as also...

**Comment by MalteScharenberg** [comment]
Added width and height options (https://github.com/pagekit/pagekit/commit/63082fb93ae79311ded867d505de0e95fd15f615).
