### ISSUE TITLE
SASS support

### ISSUE THREAD

**Issue by ardoramor** [pagekit/pagekit#538]
Is there any plan of adding SASS support for stylesheet generation?

**Comment by florianletsch** [comment]
What exactly do you have in mind? Any theme could be built using SASS. The rendering would work via some Gulp task or similar.

**Comment by ardoramor** [comment]
You are right, I think I didn't wrap my mind around it... I think I was thinking of providing something like .vue file that has sass style definitions... I'll close this and more to gitter with questions to hopefully better wrap my mind around it.
