### ISSUE TITLE
model relation returns NULL

### ISSUE THREAD

**Issue by xorinzor** [pagekit/pagekit#539]
I have a model class called `Server` in which I have the property `modpack_id` that returns int(1) as provided in the mysql table, next, in the same class I have this property:

(targetEntity use-statement is provided at the top of the class, also tried writing the full namespace in targetEntity)

```
/**
 * @BelongsTo(targetEntity="Modpack", keyFrom="modpack_id")
 */
public $modpack;
```

and I also tried:

```
/**
 * @OneToOne(targetEntity="Modpack")
 * @JoinColumn(name="modpack_id", referencedColumnName="id")
 */
public $modpack;
```

both keep returning NULL.

**EDIT:**
```
/**
 * @BelongsTo(targetEntity="Pagekit\User\Model\User", keyFrom="owner_id")
 */
public $owner;
```
returns NULL too
**End-of-edit**

When I use `Modpack::find(1)` in the controller however it does return the instance of the Modpack class with the expected contents, what's odd though is that when I use `Server::find(1)` it returns int(1) instead of the instance of `Server`, even though code-wise the `Server` and `Modpack` class (apart from their properties) are identical (currently fetching `Server` instances using `Server::query()->limit(10)->get()`).

Am I overlooking something?

This class (`Server`) is in the relationship a parent of the `Modpack` class and as such I don't think `@BelongsTo` applies, but `@OneToOne` as found in the Doctrine documentation doesn't seem to work either.

Examples of classes that I work with as templates can be found [here](https://github.com/xorinzor/pagekit-shoutzor-module/blob/master/xorinzor/shoutzor/src/Model/Music.php), I also work with examples from the pagekit-blog extension

**Comment by florianletsch** [comment]
I think the problem with `Server::find(1)` is that the query is not told to expand the user relation by default. You can do so on  `Pagekit\Database\ORM\QueryBuilder` object with the `related($entity)` method. You can get said QueryBuilder object with the call `Server::query()`. 

In your example, can you try a query like the following please:

```
$id = 1;
$result = Server::query()->related('user')->where('id = ?', [$id])->first();
```

(or, in your first example it would be `->related('modpack')` I think)

And you should also use the full namespace in the `targetEntity`attribute. 

Does this work?

**Comment by xorinzor** [comment]
Ah yes! I completely forgot about `->related()`. Thanks!

Getting the error now that it didn't find a mapping for class X
Using
```
/**
 * @HasMany(targetEntity="Me\ExtName\Model\X", keyFrom="id", keyTo="server_id")
 * @OrderBy({"time" = "DESC"})
 */
```

Is only `@BelongsTo` a valid mapper? The blog extension [uses this too](https://github.com/pagekit/extension-blog/blob/master/src/Model/Post.php#L68) though.

**Comment by MalteScharenberg** [comment]
Can you give a code example?

Just a guess: We had some issues with ORM metadata cache breaking (https://github.com/pagekit/pagekit/commit/522bec16159e787d25cb8fd765cb620f1d0e5b45).

**Comment by xorinzor** [comment]
A code example of what? the original cause of the issue has already been solved, I forgot about `->related()`.

As for the mappers, I can't make it any more clear then what I provided in the previous comment I'm afraid

**Comment by MalteScharenberg** [comment]
I can confirm this behavior and agree with you that it is odd. Also the code of the AnnotationParser looks not like it is intended. I will investigate on this. Thanks for reporting!
