### ISSUE TITLE
Installation Failed : SSL operation failed with code 1

### ISSUE THREAD

**Issue by armadafm** [pagekit/pagekit#542]
I am trying to do a fresh installation of Pagekit on a shared web environment:

Apache Version: 2.4.18
PHP Version: 5.6.18
MySQL Version: 5.6.29

After completing the first 3 setup screens, the installer fails with the following message:

Installation failed!
The "https://pagekit.com/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed Failed to enable crypto failed to open stream: operation failed

I am not able to ssh into the server to make configuration changes, I am able to ftp files to the server.

Any suggestions?

**Comment by MalteScharenberg** [comment]
The next Pagekit release (and current dev branch) will install without external connections. So the SSL issue is circumvented for the installer, but not for the marketplace.

Can you check if your server has problems with SSL connections via `file_get_contens()` in general or if it is pagekit.com specific?

```php
<?php

echo file_get_contents('https://google.com');

```

and 

```php
<?php

echo file_get_contents('https://pagekit.com');

```

**Comment by datdevs** [comment]
When i tried install extension on marketplace, it's return this error?
How to fixed, please help me!
