### ISSUE TITLE
Dynamic selector for Vue directive check-all.js

### ISSUE THREAD

**Issue by gabe-nr** [pagekit/pagekit#544]
The v-check-all directive in ./app/system/app/directives/check-all.js only really supports a string value for the selector, making it impossible to build a dynamic check box group that can use it

```
v-check-all:selector.literal="object.key"

<input type="checkbox" :class="object.key" />
```

Within a v-for loop would never work.

**Comment by MalteScharenberg** [comment]
What specific use case you have in mind where you need dynamic checkboxes?

**Comment by gabe-nr** [comment]
Being able to control different groups of checkboxes, where the selector can not be pre-determined before runtime, such as in a Vue component vs. a PHP layout.

For instance, on my custom extension, I cannot use v-check-all per checkbox group, because the only way to generate a selector for each group is via an array/object, in which the check-all.js directive doesn't accept values from (it only accepts strings, and not values from an array/object).

![capture2](https://cloud.githubusercontent.com/assets/16615491/13257145/d969ce72-da0a-11e5-9835-d79dbd6bfa04.PNG)
![capture](https://cloud.githubusercontent.com/assets/16615491/13257132/c7f36a40-da0a-11e5-8a59-f1b1e06e29f4.PNG)
![capture3](https://cloud.githubusercontent.com/assets/16615491/13257298/6ff14df2-da0b-11e5-84a2-09845f45c863.PNG)

This is my current implementation, but it does not use v-check-all. Instead, I have to use this crude method to group checkboxes:

```
toggle: function (master,group) {

    var cbarray = document.getElementsByClassName(group),
        cbmaster = document.getElementById(master);

    for(var i = 0; i < cbarray.length; i++){
        var cb = document.getElementById(cbarray[i].id);
        cb.checked = cbmaster.checked;
        if(cb.checked) {
            this.account.capabilities.push(cb.value);
        } else {
            _.pull(this.account.capabilities, cb.value);
        }
    }

}
```
```
<input type="checkbox" @click="toggle(api.name, api.name)" number>
```

And it doesn't play all that nice with the vue.js model

**Comment by MalteScharenberg** [comment]
Did you take a look at Site->Widget->All check box groups? They are dynamic using a new `group` param (https://github.com/pagekit/pagekit/blob/develop/app/system/modules/widget/views/index.php#L104). 
Does this help you?

**Comment by gabe-nr** [comment]
I did not check out the develop branch, just master. But, yes, that would help immensely, and wouldn't be dependent on a pre-processor.

**Comment by MalteScharenberg** [comment]
So, if this works for your use case than we can close this issue?

**Comment by gabe-nr** [comment]
Yes. My bad.
