### ISSUE TITLE
Pagekit and corporate firewal

### ISSUE THREAD

**Issue by gbrault** [pagekit/pagekit#545]
I want to test pageKit on a corporate env and for the testing phase, local, it seems the installer access outside files (from pagekit.com) and as I am behind a corporate firewall, it fails.

What can be done?

Any ideas? Thx

**Comment by MalteScharenberg** [comment]
The installer downloads the latest versions of the default theme and our blog extension from pagekit.com. But we are planning to distribute a bundled version of Pagekit in the future, so it is possible to install Pagekit offline.

**Comment by gbrault** [comment]
thx
