### ISSUE TITLE
Error with comment count in blog extenstion

### ISSUE THREAD

**Issue by amaierm** [pagekit/pagekit#546]
"Num % Comments" is displayed instead of real comment count. Pagekit Version 0.10.3

**Comment by MalteScharenberg** [comment]
Are you using german translations? The latest Blog version has an error in the German language strings.

**Comment by florianletsch** [comment]
Is it displayed on the site or in the admin area? And please specify which locale you have enabled. Thanks! @amaierm

**Comment by amaierm** [comment]
@MalteScharenberg I'm using german translations. @florianletsch it is on the site.

**Comment by MalteScharenberg** [comment]
Corrected german translations will be included within the next Blog release (https://github.com/pagekit/extension-blog/commit/865d2d87b2434194b1620c4690ecede2d1e4b5dc).
Thanks for reporting!
