### ISSUE TITLE
 [Feature Request] Enqueue scripts in footer.

### ISSUE THREAD

**Issue by AlexanderOMara** [pagekit/pagekit#550]
Re-creating [old issue from pre-beta](https://github.com/pagekit/pagekit/issues/365) as it seems to still be applicable.

> Right now it appears that all scripts in theme and extensions are enqueued in the head. Generally, it's better to include scripts in the footer when possible for performance reasons.

> It would be helpful if @script had an option to print the script in the footer, rather than in the header, perhaps by having these print in a @section('footer') section in themes.

**Comment by MalteScharenberg** [comment]
I added support for the script tag attributes 'defer' and 'async' (https://github.com/pagekit/pagekit/commit/2081cc113e7b471accc472f99752640f4d096fa6).
 The option can be set on registering the script with:
```php
 $app['scripts']->register('some-script', 'script.js', [], ['async' => true]);
 $app['scripts']->register('some-script', 'script.js', [], ['defer' => true]);
```
I think this should bring apart from IE < 10 the same performance gains as enqueueing scripts in the footer. What do you think?

**Comment by florianletsch** [comment]
Some background on why we prefer this over rendering in the footer: http://www.growingwiththeweb.com/2014/02/async-vs-defer-attributes.html

Browser support looks good: https://caniuse.com/#feat=script-defer

**Comment by AlexanderOMara** [comment]
That's pretty good too, probably good enough for my purposes.

The [IE <= 9 bug](https://github.com/h5bp/lazyweb-requests/issues/42) is pretty nasty though, especially is jQuery is affected by it.

On this new feature, is there any way to make the PageKit provided scripts like jQuery use the `defer` attribute?

**Comment by MalteScharenberg** [comment]
Since the IE <= 9 bug only occurs if scripts depend on each other, I think it is manageable. If you need IE 9 support and depending script with the defer attribute, you can employ for example some kind of browser detection and remove the attribute for IE <= 9.

An other option is to load scripts async with [Pagekits Asset Mananger](https://github.com/pagekit/pagekit/blob/develop/app/system/app/lib/asset.js).

**Comment by AlexanderOMara** [comment]
Was there a way to get existing scripts to load in a non-blocking fashion? For example, the default theme has 10 blocking script tags in the header.


Also, for future visitors, outputting different HTML based on user-agent can cause problems with some reverse-proxies or CDN's, if they do not also serve different HTML for that user-agent.

**Comment by jdegger** [comment]
Just a heads up the current documentation for the `defer` and `async` options are incorrect. At least for php5 (haven't tested with 7).

https://pagekit.com/docs/developer/views-templating#working-with-assets
```
<?php $view->script('theme', 'theme:js/theme.js', [], ['defer']) ?>
```

Does not work even though:
```
<?php $view->script('theme', 'theme:js/theme.js', [], ['defer' => true]) ?>
```

works fine.
