### ISSUE TITLE
Editor dissapears

### ISSUE THREAD

**Issue by Eichi** [pagekit/pagekit#551]
Hi,

today I got a new interesting bug, when adding following valid html code in a page or widget
`<p>
    <a href='/impressum'>Impressum & Datenschutz</a> - <a href='/kontakt'>Kontakt</a>
</p>`
the editing page dosn't load after reloading the site so I had to remove the content in the db to get access to the editor again. The site ist empty only the menubar is shown.

Even with debugging enabled I got no error, only a white page came up. But after some trying I found out, that the single quotes `'` are not escaped well by pagekit, after inserting double quotes `"` it worked again as expected.

https://www.w3.org/TR/html4/intro/sgmltut.html#h-3.2.2
https://xkcd.com/327/

**Comment by florianletsch** [comment]
I looked into this. The editor now no longer disappears. https://github.com/pagekit/pagekit/commit/49b68d2676561f60ebae9ed6b5942d7dd14e1ae3

However, the URLs in single quotes are rewritten incorrectly when the editor is loaded (they should not be rewritten at all in this case). So this issue needs some more work.

**Comment by florianletsch** [comment]
URL rewriting is now limited to body content which ensures that the JSON in the head section no longer breaks. https://github.com/pagekit/pagekit/commit/84d9a3a51c13f7e50ddbb0c3c5a7953c11e7d032

**Comment by MalteScharenberg** [comment]
I think the main problem was that JSON embedded inside script tags was not RFC4627-compliant, therefor rewriting was possible.
I changed the JSON encoding options according to the encoding options of Symfonys JSONResponse 
(https://github.com/pagekit/pagekit/commit/f2849e71af74ed92b29baad4d15178e386f2eabe).
