### ISSUE TITLE
Scrolling on mobile (Dashboard) moves the widgets around

### ISSUE THREAD

**Issue by iamswain** [pagekit/pagekit#552]
Due to the touch event, the widgets get moved, making scrolling on the dashboard kind of tough.

**Comment by MalteScharenberg** [comment]
We are thinking about adding a drag handle to the widgets to avoid this issue.
Thanks for reporting!

**Comment by iamswain** [comment]
Sweet! That would definitely help!

**Comment by MalteScharenberg** [comment]
Duplicate of #497.
