### ISSUE TITLE
Installation failed cause of failed to open stream

### ISSUE THREAD

**Issue by benedu** [pagekit/pagekit#553]
Hey,

I don't know if its just me. But I got this little error when setting up my Vagrant maschine (was running fine the last 2 weeks). But now I got this error:

![auswahl_054](https://cloud.githubusercontent.com/assets/14878247/13464772/fd3980c0-e092-11e5-9467-3af95e15c8e0.png)

Did I failed the installation? Inserting the database credentials etc. were fine.

**Comment by MalteScharenberg** [comment]
Which Pagekit version are you using? Please check with 0.10.4. This issue should be avoided there.

**Comment by benedu** [comment]
Can confirm with version 0.10.4 there isn't any issue anymore. Thanks for your fast feedback.

**Comment by MalteScharenberg** [comment]
We removed Composer in 0.10.4 from the installer, so this error can not occur anymore. But at the marketplace Composer is still used and some reporting the same error there (https://github.com/pagekit/pagekit/issues/554). Would be interesting to know if installing extension from the marketplace works with your installation.
