### ISSUE TITLE
Fail to upgrade extensions on 0.10.4

### ISSUE THREAD

**Issue by rogeriomarques** [pagekit/pagekit#554]
0.10.4 upgraded just fine but outdated extensions fail to upgrade, erasing all the old versions but leaving `packages/packages.php` untouched.

Tried to reinstall through the Marketplace to no avail:

`/package/pagekit/analytics/0.10.1.zip file could not be downloaded: failed to open stream: No such file or directory`

`/package/pagekit/blog/0.10.2.zip" file could not be downloaded: failed to open stream: No such file or directory`

`/package/vision/recent-blog-posts/0.0.2.zip" file could not be downloaded: failed to open stream: No such file or directory`

`/package/bixie/formmaker/1.4.0.zip" file could not be downloaded: failed to open stream: No such file or directory`

`/package/bixie/portfolio/1.1.3.zip" file could not be downloaded: failed to open stream: No such file or directory`

**Comment by rogeriomarques** [comment]
Adding to the above, same happens when upgrading theme-one.

**Comment by MalteScharenberg** [comment]
Can you empty your Composer cache and try again? It is located at `tmp/temp/composer`.

**Comment by teclliure** [comment]
Same error after cache empty.

**Comment by MalteScharenberg** [comment]
Squeezed a bug in our API which was responsible for this issue and present since yesterday. 
Thanks for reporting!
