### ISSUE TITLE
Cant install extension

### ISSUE THREAD

**Issue by Nyno-Kun** [pagekit/pagekit#557]
Hello there o/ 
I cant install any new extension and im getting this error code:
`Loading composer repositories with package information
Updating dependencies
*pagekit/packages/google/recaptcha does not exist and could not be created.`

*hidden

Edit:

Now i can Install it but i have to manualy aktivate some base Extensions.

**Comment by furouco** [comment]
Same issue here. Happens with all extensions available.

**Comment by MalteScharenberg** [comment]
Please report issues with third party extensions directly to the developer of that extension. In this case I assume, because of the error message, that it is Bixie (https://github.com/Bixie).
