### ISSUE TITLE
Marketplace isn't working both on local and remote servers (Access-Control-Allow-Origin Error)

### ISSUE THREAD

**Issue by awinogrodzki** [pagekit/pagekit#560]
When trying to access marketplace, the first group of elements fetches without problems. After we use search input to filter contents, we get error 500 in console, telling us: 
<img width="1543" alt="screen shot 2016-03-08 at 19 22 54" src="https://cloud.githubusercontent.com/assets/12574743/13611501/35c316d4-e563-11e5-89bb-c56849e4186e.png">
We get the same issue both with http and https system.api setting.

**Comment by MalteScharenberg** [comment]
Please provide more detailed informations about the request (header, parameters, etc) and which Pagekit version you are using.

**Comment by awinogrodzki** [comment]
I am using latest version of Pagekit (0.10.4), but this issue also occurs on older versions (tested 0.8 and 0.9).

I attach below headers of the response and console output. Response returns no data besides error 500

![zrzut ekranu 2016-03-09 o 11 38 11](https://cloud.githubusercontent.com/assets/12574743/13632790/c6439386-e5eb-11e5-8cba-b2ddb0d75e5c.png)
![zrzut ekranu 2016-03-09 o 11 39 16](https://cloud.githubusercontent.com/assets/12574743/13632789/c6416c6e-e5eb-11e5-802e-d4ef88254144.png)

**Comment by MalteScharenberg** [comment]
You are filtering for 'trans' with this request. Thats why the API returns no packages. Please try to clean the search bar. But anyway it is false that CORS headers are missing.

**Comment by MalteScharenberg** [comment]
We updated the Pagekit API. Thanks for reporting this!
