### ISSUE TITLE
Finder and Node packages throws errors

### ISSUE THREAD

**Issue by gabe-nr** [pagekit/pagekit#561]
After upgrading to 0.10.4, having node installed in an extension will throw an error in the Symfony finder on a Windows machine.

The NPM package manager is known to cause issues on Windows because of super long file paths in node_modules (greater than 256 chars)

The following two errors are thrown, halting Pagekit:

`UnexpectedValueException in RecursiveDirectoryIterator.php line 54: RecursiveDirectoryIterator::__construct(<super_long_path_in_node_modules>): The system cannot find the path specified. (code: 3)`

`AccessDeniedException in RecursiveDirectoryIterator.php line 107: RecursiveDirectoryIterator::__construct(<super_long_path_in_node_modules>): The system cannot find the path specified. (code: 3)`

After commenting out `$info['directories']   = $this->getDirectories();` in /app/system/info/src/InfoHelper.php (line 35), no more errors.

It appears that some sort of "exclude" option needs to be set for App::finder() to skip node_modules (VCS files such as .git are already ignored in the Symfony finder)

**Comment by MalteScharenberg** [comment]
Thanks for reporting! This should be fixed with https://github.com/pagekit/pagekit/commit/52339429208aa55f043ae3aefcc3780755e094d5. Would be great if you could check if it works for you.

**Comment by gabe-nr** [comment]
Yes, 5233942 works for me. I can close this.
