### ISSUE TITLE
Error on installation of Pagekit

### ISSUE THREAD

**Issue by alpuen** [pagekit/pagekit#563]
Hi guys,

please check your latest version of the PackageInterface in the installer package, as the current version throws errors during installation process. The code is incomplete:

`<?php

namespace Pagekit\Installer\Package;

interface PackageInterface extends \JsonSerializable
{
    /**
     * Gets a package value.
     *
     * @param  string $key
     * @param  mixed  $default
     * @return mixed
     */
    public function get($`

Thanks :-)

**Comment by MalteScharenberg** [comment]
Would be great if you could provide the exact errors thrown during installation and specify what is missing in [PackageInterface](https://github.com/pagekit/pagekit/blob/develop/app/installer/src/Package/PackageInterface.php).

Best Regards
Malte

**Comment by MalteScharenberg** [comment]
Please reopen if the issue persists.
