### ISSUE TITLE
JavaScript Code Breaks everything in Editor in admin area

### ISSUE THREAD

**Issue by PhoenixPeca** [pagekit/pagekit#566]
Whenever I paste this code into the wysiwyg editor, (if thats what you call it) 

"<script>document.write(new Date().getFullYear())</script>"

Specifically in the site widget area in the Admin area... The JavaScript tends to overwrite all HTML codes within that page... It prints 2016 instead.. Another thing, what is the short code for showing the current date from the server? Like "© Copyright 2000-[date: year] Company Name."

**Comment by PhoenixPeca** [comment]
`    <script>document.write(new Date().getFullYear())</script>

**Comment by PhoenixPeca** [comment]
```
<script>document.write(new Date().getFullYear())</script>
```

**Comment by MalteScharenberg** [comment]
Pagekit comes with an Markdown Editior. WYSIWYG-Editors can be installed as extensions.

Pagekits editor preview is inserted into the page document. Thats why `document.write` will overwrite the complete page (see first note at https://developer.mozilla.org/en-US/docs/Web/API/Document/write).

I'm thinking about stop scripts from running at all in the editor preview.
