### ISSUE TITLE
.htaccess rewrite issue

### ISSUE THREAD

**Issue by cdarlens** [pagekit/pagekit#567]
I have HTTP_MOD_REWRITE enabled on my server but the following code is causing issue. 

I'M only able to accces my the home page and cannnot access other page. 

When I remove the following block I can navgate to other pages but index.php is added to my url

`   <IfModule mod_env.c>
       SetEnv HTTP_MOD_REWRITE On
   </IfModule>

   <IfModule mod_headers.c>
       RequestHeader set MOD_REWRITE "On"
   </IfModule>
`
- PHP Version: 5.4

- [] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
Which Pagekit version are you using? PHP 5.4 is no longer supported by the latest version.
