### ISSUE TITLE
Upgrade does not check PHP versions prior to performing the upgrade.

### ISSUE THREAD

**Issue by Ricapar** [pagekit/pagekit#568]
## Problem

Upgrade does not check PHP versions prior to performing the upgrade.

## Technical Details

The version of PageKit I was running prior to upgrading was compatible with the PHP version I am running (5.4.13).

I upgraded Pagekit via the admin panel. After the upgrade completed, there was a line saying "undefined".

On loading up the site next, I was presented with this message:

> You are running PHP 5.4.13, but Pagekit needs at least PHP 5.5.9 to run.

I would expect the upgrade to check and ensure that the version of PHP (or any other dependencies it doesn't have control over) are compatible prior to committing to the upgrade.

Additionally, the documentation presented on the PageKit site states that PHP 5.4+ is required.

https://pagekit.com/docs/getting-started/requirements

**Comment by MalteScharenberg** [comment]
Actually it is necessary to check the complete [requirements lists](https://github.com/pagekit/pagekit/blob/develop/app/installer/requirements.php). This will be employed before the final release.
