### ISSUE TITLE
Installation error via console (installer page without assets) and ftp (500 error)

### ISSUE THREAD

**Issue by valle6** [pagekit/pagekit#570]
## Resume

Installation error via console (installer page without assets) and ftp (500 error).

## Problem

I tried install via console and i got installer page incomplete. The rendering isn't ok:

{{ 'Choose language' | trans }}
{{ "Select your site language." | trans }}
...
{{ 'Connect database' | trans }}
It isn't permission error, because it repeats with chmod 777.
...

Lack these files in the subfolders:
- pagekit/app/installer/assets/css/installer.css
- pagekit/app/assets/vue/dist/vue.js
- pagekit/app/assets/jquery/dist/jquery.min.js
- pagekit/app/assets/lodash/lodash.min.js
- pagekit/app/assets/uikit/js/uikit.min.js
- pagekit/app/assets/uikit/js/components/form-password.min.js

So, i tried install via FTP.
I descompacted, adjusted Apache2 configuration and permissions. I got 500 error.

I actived debug mode in app/installer/config.php, but no information is showed.  

Error 500 is recurrent, having appeared in others issues. Solutions for issues with 500 error in GitHub  are: the new version resolve the problem. So, we stay lost when this error repeats.

## Technical Details

- Pagekit version: 0.10.4
- Webserver: Debian ( in DigitalOcean)
- Database: MariaDB
- PHP Version: PHP 5.6.17-0+deb8u1

## Troubleshooting

- [ x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [ x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [ ] I have tried disabling all installed extensions   [Installation've  failled.]
- [x ] I have checked the browser developer console for JavaScript errors

Regards.

**Comment by MalteScharenberg** [comment]
Please follow the steps described in our [README](https://github.com/pagekit/pagekit/blob/develop/README.md). You can either download a complete release packages at https://github.com/pagekit/pagekit/releases or use the develop branch from this repository and compile the sources on your own (see README).

**Comment by Madeorsk** [comment]
I have the exact same issue and followed README.
