### ISSUE TITLE
error page after saving content with ctrl+s

### ISSUE THREAD

**Issue by Eichi** [pagekit/pagekit#571]
Hi, 

while editing a site I accidentally hit ctrl+s for saving the new written content of the page, well, it worked (so you are catching it what is nice), but after saving the page I was redirected to a non valid url and got an 404 error message.

`NotFoundException in HttpKernel.php line 108: Type not found.`
`HttpKernel->abort('404', 'Type not found.', array()) in RouterTrait.php line 16`
...

**Comment by MalteScharenberg** [comment]
I can't reproduce this issue. Which Pagekit version are you using?

**Comment by Eichi** [comment]
Hi, current stable release (0.10.4). 
Additionally I found out, that this error appears only with firefox.
