### ISSUE TITLE
Active menu item not properly marked

### ISSUE THREAD

**Issue by gabe-nr** [pagekit/pagekit#572]
## Problem

Active menu item not properly marked as active. For example, if you put @blog link in navbar, and then put @blog/id (post link) - the active menu item will always be @blog regardless if you're at @blog or @blog/id

The functionality to mark menu items active or not exists in /app/system/modules/site/src/MenuHelper.php

This is problem because if you would like to have multiple pages in your extension besides an index, e.g. @extension/time || @extension/place || @extension/thing, only @extension/index would be marked active.
## Technical Details
- Pagekit version: 0.10.4
- Webserver: Apache 2.4.9
- Database: MySQL 5.6.17
- PHP Version: 5.5.12
## Troubleshooting
- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
Should be fixed in 1.0.12 (if not please reopen).
