### ISSUE TITLE
Suggestion: improve readme for 1st timer

### ISSUE THREAD

**Issue by hanlan** [pagekit/pagekit#574]
The new version readme is confusing people at my perspective, like rookies, while you guys ignored to run bower to install some dependencies, and to run gulp and webpack to compile them.

After all these steps, then "continue to point to the url on your browser", none of those steps could be missing before the installer could run.

P.S.: the vue-intl which should be installed by bower, it just ignored the src folder, which is required.

**Comment by MalteScharenberg** [comment]
I would suggest to download the latest release at the [releases section](https://github.com/pagekit/pagekit/releases). These packages work out of the box (no need to gulp and webpack). Cloning the repository and compiling Pagekit yourself is only required if you want to develop at the Pagekit core.
