### ISSUE TITLE
20 Second Load Time With Debug Tool Bar Enabled

### ISSUE THREAD

**Issue by crwgregory** [pagekit/pagekit#576]
## Problem

Initial request and requesting the file "en_US" takes upwards of 20 seconds.

There are two parts that I am aware of to this problem:

1. Having debug toolbar enabled
2. Using node modules inside of Extensions and Themes

When I delete the large node_modules inside the Extensions and Theme, the browser has no problem making the request. The same goes for when I turn off the Debug Toolbar.

Maybe the dbug toolbar is scanning all files inside of extensions and themes everytime a request is made...

## Technical Details

- Pagekit version: 0.10.4
- Webserver: Apache 2.4.9
- Database: MySQL 5.6.17
- PHP Version: 5.5.12

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
Please try with this commit https://github.com/pagekit/pagekit/commit/52339429208aa55f043ae3aefcc3780755e094d5.

**Comment by crwgregory** [comment]
@gabe-nr suggested that. Changing that at first didn't have any effect. I just tried it again, and something must have changed because now performance is not being affected. 

Closing the issue. 
Thanks @MalteScharenberg !
