### ISSUE TITLE
Sqlite is not available

### ISSUE THREAD

**Issue by ecmel** [pagekit/pagekit#578]
Make sure to provide the following details when submitting your issue. Remove anything that doesn't apply for your scenario. Thanks!

## Problem

On a clean install sqlite is not present from driver combobox. I did a commandline install specifiying sqlite as db driver which worked but default theme and blog extension are not enabled. I enabled them manually but this time version seems to stuck at 0.10 so system update continues to offer the 0.11.2 update.

## Technical Details

- Pagekit version: 0.11.2
- Webserver: Apache 2.4.7-1ubuntu4.9
- Database: sqlite
- PHP Version: 5.5.9-1ubuntu4.14

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
Pagekits installer tries to detect if SQLite is available. Maybe this check results at your system in a falsely false.

Please execute the following code at your server:
```php
var_dump (class_exists('SQLite3') || (class_exists('PDO') && in_array('sqlite', PDO::getAvailableDrivers(), true)));
```
If this returns `false`, the contents of your `phpinfo` would be interesting.

@florianletsch: I can confirm that the theme and blog are not enabled probably after CLI setup.

Best Regards
Malte

**Comment by ecmel** [comment]
Have installed my ubuntu server from scratch, now it works!

Only missing marketplace icons.

**Comment by MalteScharenberg** [comment]
Thanks for pointing out the missing marketplace icons. This was caused by wrong uglifying of our build task.
