### ISSUE TITLE
No images in marketplace

### ISSUE THREAD

**Issue by thany** [pagekit/pagekit#579]
## Problem

In the marketplace, it doesn't show any images for extensions or themes. The only clue is a 404 in my network log for `/admin/system/marketplace/+pkg.extra.image+` but the images themselves are never requested.

Additionally, in the browser console, I get two messages:
```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create vue.js:2167:5
[Vue warn]: Error when evaluating expression "!packages.length". Turn on debug mode to see stack trace. vue.js:990:11
```
(yes, I have turned on debug mode, but I'm not sure where the stack trace should appear, and I'm not seeing it)

However, it doesn't look like these messages are related, but I thought I'd post them just in case.

## Technical Details

- Windows 10 x64
- Pagekit version: 0.11.2
- Webserver: XAMPP Apache 2.1.17
- Database: XAMPP MariaDB 10.1.10
- PHP Version: 5.6.19

## Troubleshooting

- [ ✓ ] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [ ✓ ] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [ ✓ ] I have tried disabling all installed extensions *(which are none)*
- [ ✓ ] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
Thanks for reporting. This issue is caused by a faulty build which had some problems with the vue-loader and uglify. This commit https://github.com/pagekit/pagekit/commit/440c1feed659503ab37e1832092ed2c262887159 should fix the issue.

Best Regards
Malte
