### ISSUE TITLE
No content in "Widgets" Tab on Firefox and mobile scrolling in Internet Explorer

### ISSUE THREAD

**Issue by furouco** [pagekit/pagekit#581]
## Problem

1. Opening the Widgets Tab on Pages with Firefox only shows me an empty screen... With other browsers it works perfectly.
2. Trying to mark some text in any form inputs on admin interface with Internet Explorer scrolls through the Tabs (for example on Widgets or Sites, pulling to the left or right with dragged mouse button on any form inputs). For me it looks like some mobile functions are activated for desktop browser.

## Technical Details

- Pagekit version: 0.11.2
- Webserver: Apache/2.4.7 (Ubuntu)
- Database: MySQL
- PHP Version: 5.5.9-1ubuntu4.14

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by xmob** [comment]
I can confirm that I'm am also not seeing the widgets page in Firefox.  It works okay in Safari, however.

**Comment by nicolas-pecher** [comment]
I got the same problem. Firefox console reports an error in widget's index.js:
TypeError: t is undefined index.js:1:3643

**Comment by MalteScharenberg** [comment]
It seems like this has to do with the latest Vue.js version 1.0.20. For some reason a function argument is missing only in Firefox. 

To downgrade Vue open `bower.json`, change `"vue": "~1.0.14",` to `"vue": "1.0.14",`, and run `bower install`.

**Comment by MalteScharenberg** [comment]
This issue is fixed in the vue dev branch (https://github.com/vuejs/vue/issues/2592#issuecomment-204819916).
