### ISSUE TITLE
Minor Setup Problem

### ISSUE THREAD

**Issue by ecmel** [pagekit/pagekit#582]
## Problem

I got a "Whoops, looks like something went wrong." error at the end of both graphical and command line setup but everything seems to set up normally.
## Technical Details
- Pagekit version: 0.11.3
- Webserver: Apache/2.4.7 (Ubuntu)
- Database: sqlite 3.8.2
- PHP Version: 5.5.9-1ubuntu4.14
## Troubleshooting
- [X] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [X] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [X] I have tried disabling all installed extensions
- [X] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
Do you have other extensions than Blog and Theme-One located inside your `packages` folder?

For debugging it would be helpful if you could install Pagekit again from a fresh extracted zip archive with debug mode turned on (`debug => true` in `app/installer/config.php`) and past the contents of the last request made during installation.

**Comment by ecmel** [comment]
WEB SETUP

Request:

{"config":{"database":{"default":"sqlite","connections":{"sqlite":{"prefix":"pk_"}}}},"option":{"system":{"admin":{"locale":"en_US"},"site":{"locale":"en_US"}},"system/site":{"title":"TEST"}},"user":{"username":"admin","password":"password","email":"ecmel@example.com"},"locale":"en_US"}

Response:

{"status":"success","message":""}<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <style>
            /* Copyright (c) 2010, Yahoo! Inc. All rights reserved. Code licensed under the BSD License: http://developer.yahoo.com/yui/license.html */
            html{color:#000;background:#FFF;}body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,textarea,p,blockquote,th,td{margin:0;padding:0;}table{border-collapse:collapse;border-spacing:0;}fieldset,img{border:0;}address,caption,cite,code,dfn,em,strong,th,var{font-style:normal;font-weight:normal;}li{list-style:none;}caption,th{text-align:left;}h1,h2,h3,h4,h5,h6{font-size:100%;font-weight:normal;}q:before,q:after{content:'';}abbr,acronym{border:0;font-variant:normal;}sup{vertical-align:text-top;}sub{vertical-align:text-bottom;}input,textarea,select{font-family:inherit;font-size:inherit;font-weight:inherit;}input,textarea,select{*font-size:100%;}legend{color:#000;}

            html { background: #eee; padding: 10px }
            img { border: 0; }
            #sf-resetcontent { width:970px; margin:0 auto; }
                        .sf-reset { font: 11px Verdana, Arial, sans-serif; color: #333 }
            .sf-reset .clear { clear:both; height:0; font-size:0; line-height:0; }
            .sf-reset .clear_fix:after { display:block; height:0; clear:both; visibility:hidden; }
            .sf-reset .clear_fix { display:inline-block; }
            .sf-reset * html .clear_fix { height:1%; }
            .sf-reset .clear_fix { display:block; }
            .sf-reset, .sf-reset .block { margin: auto }
            .sf-reset abbr { border-bottom: 1px dotted #000; cursor: help; }
            .sf-reset p { font-size:14px; line-height:20px; color:#868686; padding-bottom:20px }
            .sf-reset strong { font-weight:bold; }
            .sf-reset a { color:#6c6159; cursor: default; }
            .sf-reset a img { border:none; }
            .sf-reset a:hover { text-decoration:underline; }
            .sf-reset em { font-style:italic; }
            .sf-reset h1, .sf-reset h2 { font: 20px Georgia, "Times New Roman", Times, serif }
            .sf-reset .exception_counter { background-color: #fff; color: #333; padding: 6px; float: left; margin-right: 10px; float: left; display: block; }
            .sf-reset .exception_title { margin-left: 3em; margin-bottom: 0.7em; display: block; }
            .sf-reset .exception_message { margin-left: 3em; display: block; }
            .sf-reset .traces li { font-size:12px; padding: 2px 4px; list-style-type:decimal; margin-left:20px; }
            .sf-reset .block { background-color:#FFFFFF; padding:10px 28px; margin-bottom:20px;
                -webkit-border-bottom-right-radius: 16px;
                -webkit-border-bottom-left-radius: 16px;
                -moz-border-radius-bottomright: 16px;
                -moz-border-radius-bottomleft: 16px;
                border-bottom-right-radius: 16px;
                border-bottom-left-radius: 16px;
                border-bottom:1px solid #ccc;
                border-right:1px solid #ccc;
                border-left:1px solid #ccc;
            }
            .sf-reset .block_exception { background-color:#ddd; color: #333; padding:20px;
                -webkit-border-top-left-radius: 16px;
                -webkit-border-top-right-radius: 16px;
                -moz-border-radius-topleft: 16px;
                -moz-border-radius-topright: 16px;
                border-top-left-radius: 16px;
                border-top-right-radius: 16px;
                border-top:1px solid #ccc;
                border-right:1px solid #ccc;
                border-left:1px solid #ccc;
                overflow: hidden;
                word-wrap: break-word;
            }
            .sf-reset a { background:none; color:#868686; text-decoration:none; }
            .sf-reset a:hover { background:none; color:#313131; text-decoration:underline; }
            .sf-reset ol { padding: 10px 0; }
            .sf-reset h1 { background-color:#FFFFFF; padding: 15px 28px; margin-bottom: 20px;
                -webkit-border-radius: 10px;
                -moz-border-radius: 10px;
                border-radius: 10px;
                border: 1px solid #ccc;
            }
        </style>
    </head>
    <body>
                    <div id="sf-resetcontent" class="sf-reset">
                <h1>Whoops, looks like something went wrong.</h1>
                                        <h2 class="block_exception clear_fix">
                            <span class="exception_counter">1/1</span>
                            <span class="exception_title"><abbr title="BadMethodCallException">BadMethodCallException</abbr> in <a title="/var/www/bakanlar.info/html/app/vendor/doctrine/cache/lib/Doctrine/Common/Cache/XcacheCache.php line 89" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">XcacheCache.php line 89</a>:</span>
                            <span class="exception_message">To use all features of \Doctrine\Common\Cache\XcacheCache, you must set &quot;xcache.admin.enable_auth&quot; to &quot;Off&quot; in your php.ini.</span>
                        </h2>
                        <div class="block">
                            <ol class="traces list_exception">
       <li> in <a title="/var/www/bakanlar.info/html/app/vendor/doctrine/cache/lib/Doctrine/Common/Cache/XcacheCache.php line 89" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">XcacheCache.php line 89</a></li>
       <li>at <abbr title="Doctrine\Common\Cache\XcacheCache">XcacheCache</abbr>->checkAuthorization() in <a title="/var/www/bakanlar.info/html/app/vendor/doctrine/cache/lib/Doctrine/Common/Cache/XcacheCache.php line 72" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">XcacheCache.php line 72</a></li>
       <li>at <abbr title="Doctrine\Common\Cache\XcacheCache">XcacheCache</abbr>->doFlush() in <a title="/var/www/bakanlar.info/html/app/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php line 156" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">CacheProvider.php line 156</a></li>
       <li>at <abbr title="Doctrine\Common\Cache\CacheProvider">CacheProvider</abbr>->flushAll() in <a title="/var/www/default/html/app/system/modules/cache/src/CacheModule.php line 109" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">CacheModule.php line 109</a></li>
       <li>at <abbr title="Pagekit\Cache\CacheModule">CacheModule</abbr>->doClearCache(<em>array</em>()) in <a title="/var/www/default/html/app/system/modules/cache/src/CacheModule.php line 98" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">CacheModule.php line 98</a></li>
       <li>at <abbr title="Pagekit\Cache\CacheModule">CacheModule</abbr>->Pagekit\Cache\{closure}(<em>object</em>(<abbr title="Pagekit\Kernel\Event\KernelEvent">KernelEvent</abbr>), <em>object</em>(<abbr title="Symfony\Component\HttpFoundation\Request">Request</abbr>), <em>object</em>(<abbr title="Symfony\Component\HttpFoundation\JsonResponse">JsonResponse</abbr>))</li>
       <li>at <abbr title=""></abbr>call_user_func_array(<em>object</em>(<abbr title="Closure">Closure</abbr>), <em>array</em>(<em>object</em>(<abbr title="Pagekit\Kernel\Event\KernelEvent">KernelEvent</abbr>), <em>object</em>(<abbr title="Symfony\Component\HttpFoundation\Request">Request</abbr>), <em>object</em>(<abbr title="Symfony\Component\HttpFoundation\JsonResponse">JsonResponse</abbr>))) in <a title="/var/www/bakanlar.info/html/app/modules/application/src/Event/EventDispatcher.php line 123" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">EventDispatcher.php line 123</a></li>
       <li>at <abbr title="Pagekit\Event\EventDispatcher">EventDispatcher</abbr>->trigger(<em>object</em>(<abbr title="Pagekit\Kernel\Event\KernelEvent">KernelEvent</abbr>), <em>array</em>(<em>object</em>(<abbr title="Symfony\Component\HttpFoundation\Request">Request</abbr>), <em>object</em>(<abbr title="Symfony\Component\HttpFoundation\JsonResponse">JsonResponse</abbr>))) in <a title="/var/www/default/html/app/modules/kernel/src/HttpKernel.php line 137" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">HttpKernel.php line 137</a></li>
       <li>at <abbr title="Pagekit\Kernel\HttpKernel">HttpKernel</abbr>->terminate(<em>object</em>(<abbr title="Symfony\Component\HttpFoundation\Request">Request</abbr>), <em>object</em>(<abbr title="Symfony\Component\HttpFoundation\JsonResponse">JsonResponse</abbr>)) in <a title="/var/www/bakanlar.info/html/app/modules/application/src/Application.php line 70" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">Application.php line 70</a></li>
       <li>at <abbr title="Pagekit\Application">Application</abbr>->run() in <a title="/var/www/default/html/app/installer/app.php line 29" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">app.php line 29</a></li>
       <li>at <abbr title=""></abbr>require_once('/var/www/default/html/app/installer/app.php') in <a title="/var/www/default/html/index.php line 40" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">index.php line 40</a></li>
    </ol>
</div>

            </div>
    </body>
</html>


COMMAND LINE SETUP:

sudo php pagekit setup --adminpass=pass --adminmail=ecmel@example.com --dbdriver=sqlite
Setting up Pagekit installation...
Done
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <style>
            /* Copyright (c) 2010, Yahoo! Inc. All rights reserved. Code licensed under the BSD License: http://developer.yahoo.com/yui/license.html */
            html{color:#000;background:#FFF;}body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,textarea,p,blockquote,th,td{margin:0;padding:0;}table{border-collapse:collapse;border-spacing:0;}fieldset,img{border:0;}address,caption,cite,code,dfn,em,strong,th,var{font-style:normal;font-weight:normal;}li{list-style:none;}caption,th{text-align:left;}h1,h2,h3,h4,h5,h6{font-size:100%;font-weight:normal;}q:before,q:after{content:'';}abbr,acronym{border:0;font-variant:normal;}sup{vertical-align:text-top;}sub{vertical-align:text-bottom;}input,textarea,select{font-family:inherit;font-size:inherit;font-weight:inherit;}input,textarea,select{*font-size:100%;}legend{color:#000;}

            html { background: #eee; padding: 10px }
            img { border: 0; }
            #sf-resetcontent { width:970px; margin:0 auto; }
                        .sf-reset { font: 11px Verdana, Arial, sans-serif; color: #333 }
            .sf-reset .clear { clear:both; height:0; font-size:0; line-height:0; }
            .sf-reset .clear_fix:after { display:block; height:0; clear:both; visibility:hidden; }
            .sf-reset .clear_fix { display:inline-block; }
            .sf-reset * html .clear_fix { height:1%; }
            .sf-reset .clear_fix { display:block; }
            .sf-reset, .sf-reset .block { margin: auto }
            .sf-reset abbr { border-bottom: 1px dotted #000; cursor: help; }
            .sf-reset p { font-size:14px; line-height:20px; color:#868686; padding-bottom:20px }
            .sf-reset strong { font-weight:bold; }
            .sf-reset a { color:#6c6159; cursor: default; }
            .sf-reset a img { border:none; }
            .sf-reset a:hover { text-decoration:underline; }
            .sf-reset em { font-style:italic; }
            .sf-reset h1, .sf-reset h2 { font: 20px Georgia, "Times New Roman", Times, serif }
            .sf-reset .exception_counter { background-color: #fff; color: #333; padding: 6px; float: left; margin-right: 10px; float: left; display: block; }
            .sf-reset .exception_title { margin-left: 3em; margin-bottom: 0.7em; display: block; }
            .sf-reset .exception_message { margin-left: 3em; display: block; }
            .sf-reset .traces li { font-size:12px; padding: 2px 4px; list-style-type:decimal; margin-left:20px; }
            .sf-reset .block { background-color:#FFFFFF; padding:10px 28px; margin-bottom:20px;
                -webkit-border-bottom-right-radius: 16px;
                -webkit-border-bottom-left-radius: 16px;
                -moz-border-radius-bottomright: 16px;
                -moz-border-radius-bottomleft: 16px;
                border-bottom-right-radius: 16px;
                border-bottom-left-radius: 16px;
                border-bottom:1px solid #ccc;
                border-right:1px solid #ccc;
                border-left:1px solid #ccc;
            }
            .sf-reset .block_exception { background-color:#ddd; color: #333; padding:20px;
                -webkit-border-top-left-radius: 16px;
                -webkit-border-top-right-radius: 16px;
                -moz-border-radius-topleft: 16px;
                -moz-border-radius-topright: 16px;
                border-top-left-radius: 16px;
                border-top-right-radius: 16px;
                border-top:1px solid #ccc;
                border-right:1px solid #ccc;
                border-left:1px solid #ccc;
                overflow: hidden;
                word-wrap: break-word;
            }
            .sf-reset a { background:none; color:#868686; text-decoration:none; }
            .sf-reset a:hover { background:none; color:#313131; text-decoration:underline; }
            .sf-reset ol { padding: 10px 0; }
            .sf-reset h1 { background-color:#FFFFFF; padding: 15px 28px; margin-bottom: 20px;
                -webkit-border-radius: 10px;
                -moz-border-radius: 10px;
                border-radius: 10px;
                border: 1px solid #ccc;
            }
        </style>
    </head>
    <body>
                    <div id="sf-resetcontent" class="sf-reset">
                <h1>Whoops, looks like something went wrong.</h1>

            </div>
    </body>

**Comment by MalteScharenberg** [comment]
This one is difficult to reproduce. Is it possible for you to use a PHP debugger and find the exact position there the error occurs?

**Comment by MalteScharenberg** [comment]
Please reopen if the issue still persists.
