### ISSUE TITLE
PDO must be available

### ISSUE THREAD

**Issue by ewok1986** [pagekit/pagekit#599]
Hi All,

Fresh install on my web hosting account.

First screen when trying to run installer

http://postimg.org/image/cxig2yu4r/

## Technical Details

- Pagekit version: 1.0.0
- Apache Version	2.2.29
- MySQL Version	5.6.26-cll-lve
- Current PHP version: 5.6.10

Treid turning on debug mode but no joy, any help appreciated.

**Comment by RickBakkr** [comment]
Well, isn't it as simple as it seems? The PDO extension in PHP is missing. You could run phpinfo() to see whether the PDO extension is installed.

**Comment by MalteScharenberg** [comment]
This is not an issue, but a requirement. Nevertheless missing PDO is uncommon since it is shipped with PHP core (http://php.net/manual/en/intro.pdo.php). I would suggest, like @RickBakkr mentioned, to check with `phpinfo()`, if the PDO extension is really missing on your system.

**Comment by ewok1986** [comment]
Hi Guys thanks for the info. i have done this and it looks like its enabled... i think!

http://brassyfish.co.uk/phpinfo.php

Thanks for the help!

**Comment by MalteScharenberg** [comment]
Looks like your PDO drivers are not loaded probably. Your phpinfo should look similar to this:
![phpinfo__](https://cloud.githubusercontent.com/assets/3236302/14599204/516d5954-0556-11e6-9ec4-e93560e98188.png)

**Comment by ewok1986** [comment]
Thanks Malte, sorry for posting in the issues section, i will close this ticket now as its looking like an environment issue
