### ISSUE TITLE
Scrolling bug in mobile

### ISSUE THREAD

**Issue by andrewbanchich** [pagekit/pagekit#601]
I noticed that on my Nexus 5X on Chrome that scrolling relatively fast to the bottom of a PageKit site makes it snap up a little. Here are screen capture videos of the issue both on my personal site and on the official PageKit homepage.

https://goo.gl/photos/ej3x6MKqMTmT5HVt5

**Comment by peterbrinck** [comment]
I think it has something to do with Uikit (the CSS framework), rather than Pagekit itself

**Comment by aesahaettr** [comment]
@peterbrinck So should I post to their GitHub issues page?
