### ISSUE TITLE
Older safari edit body text problem

### ISSUE THREAD

**Issue by chompersawtooth** [pagekit/pagekit#602]
Make sure to provide the following details when submitting your issue. Remove anything that doesn't apply for your scenario. Thanks!

## Technical Details
In Older safari browser 5.1.10 edit content in page (bodytext is not possible)

- Pagekit version:1.0.0
- Webserver:mamp
- Database:litesql
- PHP Version:?

## Troubleshooting

- [ ] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [ ] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [ ] I have tried disabling all installed extensions
- [ ] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
Safari 5 is unfortunately not supported.

Best Regards
Malte
