### ISSUE TITLE
Plugin code in php

### ISSUE THREAD

**Issue by alekseykurylev** [pagekit/pagekit#603]
hi, how can I embed this code   " (formmaker){"id":"1"} "   in php files ???

**Comment by benedu** [comment]
Don't know if this Pagekit related or maybe @malles can say something about it aswell. He is the creator of the awesome [formmaker extension](https://github.com/Bixie/pagekit-formmaker).

**Comment by malles** [comment]
See https://github.com/Bixie/pagekit-formmaker/issues/38

**Comment by MalteScharenberg** [comment]
Please use the issue tracker only for bugs or feature requests related to Pagekit. 
[Here](https://github.com/pagekit/pagekit/blob/develop/.github/CONTRIBUTING.md) you can find other other sources to get help.

Best Regards
Malte
