### ISSUE TITLE
Some plan to API documentation ?

### ISSUE THREAD

**Issue by wensonsmith** [pagekit/pagekit#608]
I'm really love this CMS, but as a developer, the present documentation is hard to learn . I can't find how to use functions of this CMS,  such as `$view` ，what dose it's params and functions mean ?

Hope to see some plan to CMS API documentation!

Yii2 documentation is very good!

By the way , how can i put js files at the bottom of body ?

**Comment by peterbrinck** [comment]
I can't answer on the documentation part, but you can, if you go to `Site -> Settings -> Code` you can insert code, it can be HTML and in this case a script tag, that then gets rendered/put on your site.
Just as long as you have this line `<?= $view->render('footer') ?>` in your template, at the bottom.

This is the only way I know

**Comment by MalteScharenberg** [comment]
See https://github.com/pagekit/pagekit/issues/550 and https://github.com/pagekit/pagekit/issues/609.
