### ISSUE TITLE
Asset pipeline

### ISSUE THREAD

**Issue by benedu** [pagekit/pagekit#609]
Hey Guys,

first of all I want to say that your doing a great job with Pagekit! Keep up your good work.

I would like to know if there are any thoughts about enhancing the current state with handling assets like css or js. Currently everything will be written into the head section of the document. As the theme grows there will be plenty of scripts. Which result in many requests the user has to do in order to load the page.

What I would love to see is that everything will be automatically concatenated and minified. But at least some option to load scripts at the end of the document or further asynchronous loading of third party scripts like so: `<script async src="/js/libs.js"></script>`

Maybe just enhance the `$view->script()` function with a boolean parameter.

**Comment by MalteScharenberg** [comment]
https://github.com/pagekit/pagekit/commit/655bb84a5a6e666e2185c0c5d3135b39ae2ff777
