### ISSUE TITLE
Custom font files

### ISSUE THREAD

**Issue by PSkaggs** [pagekit/pagekit#612]
Is there any reason why I can't upload custom font files to Storage?  I keep getting "Invalid File Name" alert when I try to upload files with extensions .ttf, .eot, and .woff.  The .svg extension seems to work.

Thanks

**Comment by MalteScharenberg** [comment]
We implemented a file extension filter with the latest version. You can specify allowed extension types at `System->Settings'.

**Comment by PSkaggs** [comment]
Thanks
