### ISSUE TITLE
I can not run the installation: "500 Error"

### ISSUE THREAD

**Issue by VadymVolos** [pagekit/pagekit#615]
pagekit-1.0.2.zip

I can not run the installation: "500 Internal Server Error"
I added .htaccess

Maybe I need to delete this file?

Log server:
`/pagekit/.htaccess: Option MultiViews not allowed here, referer: www.mysite.com`

Maybe PHP 5.4. I did PHP 5.6.
Error is still there. I'll wait an hour.

**Comment by VadymVolos** [comment]
.htaccess 
I add #
`# Options -MultiViews`

Installation Run!!!

**Comment by MalteScharenberg** [comment]
Dose this [commit](https://github.com/pagekit/pagekit/commit/95bafba1ce3370123a9a41e093f1f153cebe1d7e) fixes your issue?

**Comment by VadymVolos** [comment]
I dont know. I disabled
`# Options -MultiViews`
And I launched the installation. Work.

Reinstall To checkI dont have an opportunity.

**Comment by MalteScharenberg** [comment]
You don't need to reinstall to check if its working. Just place the code and see if the page is accessible.

**Comment by VadymVolos** [comment]
I add </IfModule>
```
<IfModule mod_rewrite.c>
    Options -MultiViews
</IfModule>
```

No work! "500 Internal Server Error"

**Comment by mateomrqz** [comment]
I can't seem to be able to get past the 500 Installer Error. Any updates on this? MAMP / Mac Os Capitan / Php 7

**Comment by vizcoop** [comment]
I had a local install that was working fine, now i'm trying to install on the server and I'm stuck at the 500 error... I tried modifying the ht.access with no luck...

**Comment by damienfaivre** [comment]
Hi,

Same here, works fine with MAMP but, not online.
I tried to add `# Options -MultiViews` and `<IfModule mod_negotiation.c>Options -MultiViews</IfModule>`, even changed files permission. Still the same error.

my website host is **OVH**.

I was having so much fun with my local Pagekit, I'm kind of disappointed right now.
are we close to a solution ? Looks like this is not a minor issue

Apart from that, your tool is amazing ;)

**Comment by vizcoop** [comment]
It would be nice to get feedback on that matter... the post got bump twice but nothing...

**Comment by damienfaivre** [comment]
I found a solution :
It is simple yet it was so time consuming… You need to download your Pagekit copy here : https://pagekit.com/download

`/Vendor/` folder is included in this one and it worked, no more error.
This difference between Github and the Pagekit website's archive is confusing.

**Comment by florianletsch** [comment]
@damienfaivre Yes, you should always* use a release package, i.e. from pagekit.com/dowload or from the releases page on github. 

To make sure the Github version runs, you would need additional steps: https://pagekit.com/docs/developer-basics/source ... so in general, just download a release package file!

I am not sure, if this is the issue of the original poster. Can someone confirm?

* except maybe if you are submitting pull-requests to the Pagekit core

**Comment by damienfaivre** [comment]
Yes, sorry about that, it's a bad habit… it always worked for me until now, and here is the result !

I just want to say that Pagekit is a really friendly and simple CMS ( which can be used by _everyone_ ) but downloading the Github source once can turns out to be painful for non-professionnal-dev guys.

I'm picky, I know… but I learned something today, thank you for that
