### ISSUE TITLE
PageKit Update Theme and Extension Error

### ISSUE THREAD

**Issue by mattherndon** [pagekit/pagekit#617]
## Can not update themes or extensions in PageKit.

When clicking the update button for a theme or extension within the Admin area, the install loading bar is displayed blank and the loading icon spins and seems to timeout. 

I do get an XHR Error in Chrome but have tested FF as well and cannot update.
## Technical Details
- Pagekit version: 1.0.2
- Webserver: Apache
- Database: MySQL
- PHP Version: 5.5.31
## Troubleshooting
- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
Please provide the contents of the failed XHR.

**Comment by matthewherndon** [comment]
![image](https://cloud.githubusercontent.com/assets/13767683/14917242/b5819a32-0de3-11e6-91dc-525b1059bbcb.png)

![image](https://cloud.githubusercontent.com/assets/13767683/14917278/db3a462a-0de3-11e6-895e-0b21e946738b.png)

**Comment by mattherndon** [comment]
![image](https://cloud.githubusercontent.com/assets/13767683/14917242/b5819a32-0de3-11e6-91dc-525b1059bbcb.png)

![image](https://cloud.githubusercontent.com/assets/13767683/14917278/db3a462a-0de3-11e6-895e-0b21e946738b.png)

**Comment by MalteScharenberg** [comment]
This request is still pending. Please wait until it's finished and provide the response (not request).

**Comment by MalteScharenberg** [comment]
Please reopen if the issue still persists.
