### ISSUE TITLE
Vagrant ubuntu 14.04 admin panel not working

### ISSUE THREAD

**Issue by chagamkamalakar** [pagekit/pagekit#618]
## installation worked, but admin panel not  working ( whoops something went wrong)

I am trying to run pagekit using vagrant ( host: virtualbox 5 & ubuntu 14.04, guest : 14.04) . 
problem 1) 
initially installation was not successful error message in browser was "Whoops something went wrong" .  

**Solution** : i checked in apache logs ( /var/log/apache2/error.log ) ,  permission denied to tmp folder , I run " sudo chmod 777 -R /var/www/pagekit/tmo "  .. it worked.
installation created database successfully.

Problem 2: when i tried to open admin panel after installation,   now the same problem again "Whoops something went wrong " , i couldn't see anything now in error log (/var/log/apache2/error.log). 

Any help please?

## Technical Details

- Pagekit version: 1.0.1
- Webserver: apache 2.4.7
- Database: mysql
- PHP Version: 5.5.9

## Troubleshooting

- [x] I have enabled debug mode: /etc/php/apache/php.ini
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for http errors ( 500 )

**Comment by MalteScharenberg** [comment]
Please enable Pagekits debug manually in the `/config.php`file like described [here](https://pagekit.com/docs/getting-started/configuration-file).

**Comment by chagamkamalakar** [comment]
thank you @MalteScharenberg 
i could see file_put_contentns failing while writing cache data 

![pagekit_error](https://cloud.githubusercontent.com/assets/6966631/14840193/6cbce030-0c4f-11e6-8922-9f8612e78d34.png)

**Comment by chagamkamalakar** [comment]
Fixed

If you're running apache, then you can update the user to 'vagrant' by editing the following file (/etc/apache2/envvars) like below:

Find this section

export APACHE_RUN_USER=www-data
export APACHE_RUN_GROUP=www-data

And change it to

export APACHE_RUN_USER=vagrant
export APACHE_RUN_GROUP=vagrant

the following helped me to sort out this.
[http://stackoverflow.com/questions/30854013/vagrant-file-put-contents-permission-denied](url)
