### ISSUE TITLE
Url Rewrite not working on IIS / Windows Server

### ISSUE THREAD

**Issue by ynalbantoglu** [pagekit/pagekit#622]
Url Rewrite not working on IIS 7.5 / Windows Server 2012
It will be published when the offical web.config file or updated .htacces file?
Thanks.

**Comment by MalteScharenberg** [comment]
IIS is not officially supported by Pagekit. I think to make URL rewriting working, you have to translate the `.htaccess` file into a `web.config` file (http://www.iis.net/learn/application-frameworks/install-and-configure-php-applications-on-iis/translate-htaccess-content-to-iis-webconfig).
