### ISSUE TITLE
Impossible to set database port

### ISSUE THREAD

**Issue by Addvilz** [pagekit/pagekit#623]
## Problem

Installation script does not provide possibility to set port for the database.
Also, "Database connection failed!" is not a very helpful error message. Is it Login that failed? Host not reachable? What exactly?

## Technical Details

- Pagekit version: 1.0.2
- Webserver: built-in
- Database: MySQL

**Comment by baskettcase** [comment]
Im getting the same "Database connection failed!" on installation. Im currently trying to figure out how to debug to see what the real problem is. Im using the same credentials for magento and phpMyAdmin, so I know that the credentials are correct.
