### ISSUE TITLE
Can not install Analytics 1.0.0 on Pagekit 1.0.2

### ISSUE THREAD

**Issue by fhouenou** [pagekit/pagekit#625]
## Problem

Can not install Analytics 1.0.0 on Pagekit 1.0.2

## Technical Details

- Pagekit version: 1.0.2
- Webserver: Apache
- Database: mysql
- PHP Version: 5.6.15

## Troubleshooting

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create vue.js:2150:5
[VueResource warn]: The `:name` parameter syntax has been deprecated. Use the `{name}` syntax instead. vue.js:1:2138
[Vue warn]: Error when evaluating expression "package.extra.icon": TypeError: scope.package.extra is undefined (found in component: <package-details>) vue.js:991:11

[Vue warn]: Avoid using reserved keywords in expression: package.authors[0].homepage vue.js:991:11

[Vue warn]: Error when evaluating expression "package.authors[0].homepage": TypeError: scope.package.authors is undefined (found in component: <package-details>) vue.js:991:11

[Vue warn]: Avoid using reserved keywords in expression: package.authors[0].email vue.js:991:11

[Vue warn]: Error when evaluating expression "package.authors[0].email": TypeError: scope.package.authors is undefined (found in component: <package-details>) vue.js:991:11

[Vue warn]: Error when evaluating expression "package.extra.image": TypeError: scope.package.extra is undefined (found in component: <package-details>) vue.js:991:11

[Vue warn]: Avoid using reserved keywords in expression: package.authors[0].name vue.js:991:11

[Vue warn]: Error when evaluating expression "package.authors[0].name": TypeError: scope.package.authors is undefined (found in component: <package-details>)

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [ ] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by fhouenou** [comment]
Fixed!!!

**Comment by MalteScharenberg** [comment]
What was the problem?
