### ISSUE TITLE
How to use $view->style(....) in .twig  template file ?

### ISSUE THREAD

**Issue by wensonsmith** [pagekit/pagekit#626]
## Problem

If use `.php` template file, we can easy to use it 

```php
<?php $view->style('theme', 'theme:css/theme.css') ?>
```

How to use it in a `.twig` template file ?

I have tried 

```php
 {{ view.style('theme','theme:css/theme.css') }}
```

It report a error

> An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class Pagekit\View\Asset\FileLocatorAsset could not be converted to string") in "navigation.twig" at line 2.

And I also tried 

```php
{{ attribute(view, style, ['theme', 'theme:css/theme.css']) }}
```

Error:

> An exception has been thrown during the rendering of a template ("Undefined helper """) in "navigation.twig" at line 2.

How to do ?  Thanks very much !!

## Technical Details

- Pagekit version: 1.0.0
- Webserver: nginx
- Database: mysql
- PHP Version: 5.6.18

**Comment by florianletsch** [comment]
I have fixed the underlying issue, the change will go out with the next release. 
Commit https://github.com/pagekit/pagekit/commit/9e650b30b33c9d3a6858574b81c5dafb25e2cbe9 (you can apply the change manually to make it work for you in the meantime)

You will then be able to use it as intended: `{{ view.style('theme','theme:css/theme.css') }}`

**Comment by overtrue** [comment]
:+1:

**Comment by wensonsmith** [comment]
Great!!  Thank you very very much ! @florianletsch
