### ISSUE TITLE
Will not install, constant "Database connection failed!"

### ISSUE THREAD

**Issue by baskettcase** [pagekit/pagekit#627]
## Problem

I enter in the correct credentials for MySQL, copy and pasted from my magento local.xml file and tested in phpMyAdmin also, both works, but PageKit does not work and I get the "Database connection failed!" error. I've deleted everything and tried installing again, still the same error.
## Technical Details
- Pagekit version: 1.0.2
- Webserver: Apache with Nginx 
- Database: MySQL
- PHP Version: 5.5.34
## Troubleshooting
- [X] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [X] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [X] I have tried disabling all installed extensions
- [X] I have checked the browser developer console for JavaScript errors

**Comment by xhs345** [comment]
well.. can you post some of those details you entered? For example, I had to replace 'localhost' with '127.0.0.1' on a server to get it to work.

P.S.: "Apache with Nginx" which one is it?

**Comment by baskettcase** [comment]
details that I entered? Im pretty sure you're not asking me for the database credentials ;) I tried localhost and 127.0.0.1 but neither works. I am currently trying to install it locally to see if it works.

apache 2.4
nginx 1.9.14

I am using serverpilot.io
https://serverpilot.io/features
"Nginx in front of Apache. PHP-FPM and MySQL."

**Comment by baskettcase** [comment]
It installed on my local machine just fine, so Ill keep trying to trace down the problem on the server. If you have any ideas I would love to hear them :)

**Comment by xhs345** [comment]
Not the password, but other details could be relevant. See also: https://github.com/pagekit/pagekit/issues/619

And thanks for the info about your webserver. The setup with both is a bit more uncommon, so I wasn't sure if it was just a typo

**Comment by baskettcase** [comment]
Ah no it's an already existing database that is running magento. It's just letters in its name. No numbers, no special characters, etc.

**Comment by MalteScharenberg** [comment]
Is your database listening at MySQLs default port `3306`?  Unfortunately the installer has currently no option to change the database port.

**Comment by baskettcase** [comment]
Yes default port. Is there a way to be able to log the connection problem or debug? Point me to the right file?

**Comment by MalteScharenberg** [comment]
The database connection is tested here: https://github.com/pagekit/pagekit/blob/develop/app/installer/src/Installer.php#L63

**Comment by baskettcase** [comment]
Ok yeah I had tracked that down, but that was as far as I got, it returns a 0 for the error code, so I was hoping to find that method to debug it further, but Im not sure where that method connect() is.. Im leaning towards the vendor directory?

**Comment by MalteScharenberg** [comment]
Yes we are using Doctrine DBAL for database connections. The MySQL driver is located at `app/vendor/doctrine/DBAL/Driver/PDOMySql/Driver.php` which tries to create `app/vendor/doctrine/DBAL/Driver/PDOConnection.php`.

**Comment by baskettcase** [comment]
Ok so I think I found the problem, after tracing the problem.. there has got to be an easier way than doing what I am doing :( 

In the vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php file, the listTables() method. It is taking all the tables.. and this is a magento database, so it has _a lot_ of tables, 489 to be exact, and then getting information about each one, it's possible that it's just running out of memory as it puts everything about each table into one array. It only gets through two tables before it fails though. The third table is about 1.3GB, although since it is just getting info about a table, Im not sure why it would fail due to size.

or.. I just traced it a bit further.. and maybe it's because in that second table I have a column called "enabled" and it doesn't like that when it calls:

abstract protected function _getPortableTableColumnDefinition($tableColumn);

Im not exactly sure what that does.. so I can't tell if that's why it is failing.. I just know as it's grabbing the table info and gets to my second table, and the column "enabled" that's when it fails.

**Comment by baskettcase** [comment]
I just posted a bug report here for Doctrine here:
https://github.com/doctrine/dbal/issues/2377

**Comment by baskettcase** [comment]
Ok so after talking to the Doctrine people and some serious troubleshooting and debugging, I found that if your database contains any tables that have an ENUM field type, then Doctrine is going to fail and PageKit will not install. There needs to be some kind of documentation on that, and some kind of check, etc.. this would have saved me a whole lot of troubleshooting :(
