### ISSUE TITLE
Wont show custom theme

### ISSUE THREAD

**Issue by sondregi** [pagekit/pagekit#629]
## Problem

My custom theme wont show up in System->Theme on my webserver.
Same thing if I clone the hello theme to packages/sondreg/theme-hello and change the path from     "name": "pagekit/theme-hello", to     "name": "sondreg/theme-hello", in the composer.json file

No problem locally.

## Technical Details

- Pagekit version:  1.0.2
- Webserver: Apache
- Database: mysql - version 5.6.30
- PHP Version: 5.5.32

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by sondregi** [comment]
Here is my composer.json file

https://gist.github.com/sondregi/29517d72f3c8a4d698bf62504e5563b0

still wont show custom theme

**Comment by sondregi** [comment]
Okay. Somehow my " " marks got changed to «» which seemed to not showing my theme

**Comment by overtrue** [comment]
@sondregi You composer.json is invalid, you can use command `composer validate` to validate.

```
 [Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 2:
  {    "name": «sondreg/theme-hell
  ------------^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['
```
