### ISSUE TITLE
Feature Request: Custom Layout via GUI

### ISSUE THREAD

**Issue by YoKoGFX** [pagekit/pagekit#633]
## FEATURE REQUEST

If you know the Gantry Framework for Joomla, you know that they have a GUI to change the Layout of the Website. Because this is such a great way to change the whole look of the Website, why we don't add this to Pagekit?
- **GUI OF THE FRAMEWORK**:

![image](https://cloud.githubusercontent.com/assets/18743976/14938233/7ab20a28-0f1d-11e6-9785-78106a763340.gif)
## TECHNICAL DETAILS
- Pagekit version: 1.0.2
- Webserver: Apache
- PHP Version: 7.0.4
## TROUBLESHOOTING
- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
This is a feature that will come with Yootheme Pro to Pagekit.
