### ISSUE TITLE
Updating from 1.0.0 to 1.0.2 not working

### ISSUE THREAD

**Issue by andrewbanchich** [pagekit/pagekit#634]
Make sure to provide the following details when submitting your issue. Remove anything that doesn't apply for your scenario. Thanks!
## Problem

When I auto update from 1.0.0 to 1.0.2 it has no errors and says the database upgrade is successful, but after it finishes it still says the 1.0.2 update is available and that I'm running 1.0.0.
## Technical Details
- Pagekit version: 1.0.0
- Webserver: Apache
- Database: MariaDB - sqlite 3.8.5
- PHP Version: 5.6.20
## Troubleshooting
- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
Please check with the network inspector of your browser the content of all requests made during the update routine. Are there any errors?

**Comment by arisbanach** [comment]
Nope, none that I can see. I'm new to checking this, though. I am in Chrome, and went to Developer Tools > Network and then clicked the Update button. I didn't see anything that looked like an error at all.

**Comment by MalteScharenberg** [comment]
Can you check the content of the last 2 requests made. In Chrome you can to this by clicking on at the request and then on preview.

**Comment by arisbanach** [comment]
There are three requests I see after clicking Update: Download, Update, and Migrate.

When I click Migrate and then Preview, I just see a blank white screen and the text "Preparing update..."

When I click Migrate, I see:

`{message: "Your database is up to date."}
message
:
"Your database is up to date."`

**Comment by arisbanach** [comment]
I'm not sure if this would affect upgrades, but I asked my hosting provider to modify the .htaccess file so that it forces SSL on every page. Would that have caused this issue?

**Comment by MalteScharenberg** [comment]
SSL should not cause any trouble. Can you send me login credentials for your Pagekit installation via a private Gitter message, so I can investigate?

**Comment by arisbanach** [comment]
All set. I messaged you on Gitter.

**Comment by arisbanach** [comment]
@MalteScharenberg Did you get the info? I'd like to delete the message as soon as you're done so I don't have admin credentials floating around out there.
