### ISSUE TITLE
Ignore local files

### ISSUE THREAD

**Issue by PremadeGames** [pagekit/pagekit#638]
## Problem

I have my pagekit installation on the root and a development folder with php files inside /data/myapp/. When I want to access my files with /data/myapp/ or even /data/myapp/index.php I get to the pagekit error page saying "No route found for "GET /data/myapp"

EDIT: This appearently only happens when you activate Error Reporting via .htaccess
## Technical Details
- Pagekit version: 1.0.2
- Webserver: Apache/2.4.18
- Database: mysql 5.5.45
- PHP Version: 5.5.33
## Troubleshooting
- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
This has to do with the way mod_rewrite is implemented in Pagekit and is hard to solve differently.
