### ISSUE TITLE
Can configure Storage Path

### ISSUE THREAD

**Issue by neicv** [pagekit/pagekit#639]
## Problem

Go:
System->Settings->Storage:

Change dir -> "\storage" - "\mystorage"   next press ->  "Save"

Go next -> "Site->Storage :
               Trow Exception - "Unable Found Patch"

simple derivation :   Path not makes when aply changes.

where " mkdir ('mystorage', 0777, true);" or some  elase?
## Technical Details
- Pagekit version: 1.02
- Webserver: OpenServer 5.2.4
- Database:
- PHP Version: 5.6 x64
## Troubleshooting
- [ x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x ] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements

**Comment by MalteScharenberg** [comment]
Pagekit dose not automatically creates folders.
