### ISSUE TITLE
Can not use admin-quicklinks on iPad

### ISSUE THREAD

**Issue by ehrenwert-it** [pagekit/pagekit#641]
## Problem

i can not use the quicklinks in /admin on iPad. E.g. If I touch "marketplace" nothing happens 

## Technical Details

- Pagekit version: 1.0.2
- Webserver: Apache 2.4
- Database: MySQL
- PHP Version: 5.6

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [ ] I have checked the browser developer console for JavaScript errors

**Comment by florianletsch** [comment]
This has been fixed in the 1.0.3 release.
