### ISSUE TITLE
Pretty url's not working

### ISSUE THREAD

**Issue by sondregi** [pagekit/pagekit#642]
## Problem
Having issues with pretty url's not working
mod_rewrite is enabled. have access to .htaccess file.
Using this .htaccess file https://github.com/pagekit/pagekit/blob/develop/.htaccess

pretty url's are working if i type them in the browser, but pagekit keeps generating http://url.com/index.php/url

I've tried to reinstall Pagekit a couple of times. Tried installing it in a subfolder. - Still the same

Also tried installing wordpress, and was no problem with pretty urls.

You can look here http://sondre.me

If i type http://sondre.me/admin I get redirected to http://sondre.me/index.php/admin/login

## Technical Details

- Pagekit version: 1.0.2
- Webserver: Apache 2.4
- Database: mysql
- PHP Version: 5.5.35

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by florianletsch** [comment]
Can you please create a php file on the same server with the following content:

```
<?php phpinfo();
```

When you access that file in the browser, please search for _mod_rewrite_ and see if it is included in the _Loaded Modules_.

Also, please check if anything in issue #607 is of help to you.

**Comment by sondregi** [comment]
Here is my php info http://sondre.me/Phpinfo.php

My host says there servers all have the same configuration. 

I have a site on a different server from the same host. With a fresh installation of pagekit. Everything working fine there.

**Comment by florianletsch** [comment]
Okay, there is no mod_rewrite listed in the output. But that is probably because your PHP is running as FastCGI, not as an Apache module, so ist just doesn't list the loaded apache modules.

And actually, the url rewrite is working properly (i.e. http://sondre.me/blog works properly, just the generated url isn't pretty because it contains the index.php prefix).

This looks like Pagekit doesn't detect that mod_rewrite is available in your environment. This has been an issue with nginx before. So either we need to improve the detection to work for more environments or at least include a manual config setting to force pretty url generation.

**Comment by sondregi** [comment]
So there is a fix for this issue? :)

**Comment by MalteScharenberg** [comment]
For mod_rewrite detection with Apache you need either mod_env or mod_header. Can you check if one of them is enabled at your system? Further make sure that the latest version of Pagekits `.htaccess` file is used (it is not updated automatically).

https://github.com/pagekit/pagekit/blob/1.0.2/.htaccess (line 48 - line 54 is the important part for the detection)

**Comment by sondregi** [comment]
Florian gave me a fix for this issue.

**Comment by sondregi** [comment]
![](http://i.imgur.com/TZiQR93.jpg)

**Comment by kehugter** [comment]
@sondregi you should remove http://sondre.me/Phpinfo.php

**Comment by pixelbart** [comment]
Still open...

**Comment by tobbexiv** [comment]
See also #505: If you can access your page without the index.php, you can try my plugin to avoid changes of files after every update.
