### ISSUE TITLE
site > storage : Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by wensonsmith** [pagekit/pagekit#643]
## Problem

In `site > storage` ,  after upload image successfully,  it still show no file . 

The image is upload to /storage indeed, but dev tool console report

```
Uncaught TypeError: Cannot read property 'replace' of undefined
```
![image](https://cloud.githubusercontent.com/assets/2544185/15099278/ae2943c8-1583-11e6-99e7-20660cbbe83c.png)

Sorry for my poor english ,thanks !

## Technical Details

- Pagekit version: 1.0.2
- Webserver: nginx/1.8.1
- Database: Mysql 5.7.11
- PHP Version: 5.6.18

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by overtrue** [comment]
@wensonsmith maybe it fixed at https://github.com/pagekit/vue-intl/issues/1 but not release.

**Comment by wensonsmith** [comment]
@overtrue Thanks very much !  Pagekit looks beautiful, but it's hard to develop for me . And it‘s 不太成熟不太稳定。。  so.. i decide to use October CMS.

**Comment by overtrue** [comment]
@wensonsmith 我现在感觉他们的开发计划不够稳定，已经很久不曾review issue 与 PR 了。再观望一段时间，不行我就 fork 一个分支来维护。

**Comment by wensonsmith** [comment]
@overtrue  是呀，好多零回复 issues。这个框架和Vue搅在一起让我很头大，出错都不知道怎么调试。 我先去尝试一下October， 继续观望

**Comment by MalteScharenberg** [comment]
Please speak English, otherwise it is hard for us to manage the issues.

Is this fixed like @overtrue indicated?

**Comment by overtrue** [comment]
@MalteScharenberg I think the answer is yes.
