### ISSUE TITLE
Incorrect view of Install page

### ISSUE THREAD

**Issue by 2beFlo** [pagekit/pagekit#645]
Make sure to provide the following details when submitting your issue. Remove anything that doesn't apply for your scenario. Thanks!

## Problem

I've tried to install pagekit on my server behind an nginx as reverseproxy and an nginx as actual webserver. Wehnever I open the install page on the subdomain I created I'll get the page shown like this: {{ 'Choose language' | trans }}

For the nginx config on the webserver I use this one: https://gist.github.com/DarrylDias/be8955970f4b37fdd682

## Technical Details

- Pagekit version: latest
- Webserver: nginx
- Database: mysql 
- PHP Version: https://gist.github.com/DarrylDias/be8955970f4b37fdd682

## Troubleshooting

- [ ] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [ ] I have tried disabling all installed extensions
- [ ] I have checked the browser developer console for JavaScript errors

**Comment by izuolan** [comment]
You can use 'docker run pagekit/pagekit' to run .

See more [https://hub.docker.com/pagekit/pagekit](https://hub.docker.com/pagekit/pagekit)

or, use releases : https://github.com/pagekit/pagekit/releases

**Comment by florianletsch** [comment]
So, you see the following line appear in the installer?

```
{{ 'Choose language' | trans }}
```

This is a template string from the frontend that should be replaced by the installer's JavaScript. Somehow the script is not running properly.

Can you please check the developer console of your browser to see if there any JS error or if there are network errors, for example when the JS files couldn't be loaded?

**Comment by ryanlhunt** [comment]
I have the same issue and I'm getting a 404 error for the JS files.

**Comment by MalteScharenberg** [comment]
@ryanlhunt Did you installed Pagekit from source? If that is the case, please follow our [installation guide](https://pagekit.com/docs/developer/source) or download the [latest release](https://github.com/pagekit/pagekit/releases).
