### ISSUE TITLE
How can I export post to markdown ?

### ISSUE THREAD

**Issue by izuolan** [pagekit/pagekit#646]
## Problem

How can I export post to markdown ? Backup posts and pages .
## Technical Details
- Pagekit version: 1.0.2
- Webserver: Nginx 1.9
- Database: mysql
- PHP Version: 5.6

**Comment by florianletsch** [comment]
There is currently no automatic way for this. Maybe someone wants to create a _Backup_ extension for this?

**Comment by jdegger** [comment]
A backup extension seems like a very important step towards a fully featured CMS 👍
