### ISSUE TITLE
Widget Visibility: All Pages-No Pages

### ISSUE THREAD

**Issue by sulivieri** [pagekit/pagekit#648]
## Problem

if i deselect all the Widget Visibility options than save,
the "All Pages" check return to be selected

result: no possibility to leave the widget without visibility.
is that normal?

thanks

## Technical Details

- Pagekit version: 1.0.3
- Webserver: localhost using MAMP
- Database: Mysql 5.6.25
- PHP Version: 5.6.10

## Troubleshooting

- [ x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [ x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x ] I have tried disabling all installed extensions
- [ x] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
Yes, this is intended. Currently there is no option for no visibility, except from disabling the widget.
