### ISSUE TITLE
real-time preview?

### ISSUE THREAD

**Issue by joekrump** [pagekit/pagekit#651]
## Problem

On the pagekit /features page it mentions:

> "The HTML & Markdown editor provides a great writing experience with markdown, **real-time preview**, syntax highlighting and fullscreen mode. Inserting media through the file manager is super easy."

Is the "real-time preview" implemented? It doesn't seem to be working for me. I see a dropdown option to preview the content, however this causes a preview to show up in a modal. From what is shown on the /features page it would seem that I should be able to have a live preview of some sort in a side panel. Am I missing something here?

## Technical Details

- Pagekit version: 1.0.3
- Webserver: Apache
- Database: MySQL
- PHP Version: 5.6.20

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by florianletsch** [comment]
The real-time preview is a feature of the HTML/Markdown editor (that comes from UIkit).

On the top right of the editor, you see a small arrow icon which can be used to show the editor in fullscreen mode. Then, you will see the HTML/Markdown on the left and the rendered content on the right, just like it is shown on the Features page you mentioned:

![Fullscreen mode](https://pagekit.com/storage/features/editor.gif)
