### ISSUE TITLE
Installing Themes and Extensions error

### ISSUE THREAD

**Issue by Khrizal-Weas** [pagekit/pagekit#652]
## Problem

My issue has happened to other already but with previous versions and it seems to have been fixed in the new released. 

However, I just installed PageKit and I have tried to install extensions and themes. 
I can't make it work. I've tried manually and going through the marketplace. 

Here's what is hapenning: 
![pagekiterror](https://cloud.githubusercontent.com/assets/19479063/15409816/ccc671fc-1e16-11e6-8041-7665cbfbc822.png)

For information, this is only my second attempt to make a website. I might sound quite unfamiliar with your advice, I'll do my best. 

Thank you.

EDIT : Removing Extensions or Themes leads to the same error.

EDIT : I've been working on the gitter with Jorin Vermeulen (@xorinzor). I can't understand what we did, but we made it work. Almost work I should say. I still have issues with the loading bar, but If I wait a few seconds then reload the page, the theme or extansion is correctly install. Which makes it just a slight frontend bug (I reckon). 
## Technical Details
- Pagekit version:1.0.3
- Webserver:Apache (localhost)
- Database:MySQL
- PHP Version:7.0.6
## Troubleshooting
- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions

**Comment by guileh** [comment]
I'm with the same issue.

**Comment by MalteScharenberg** [comment]
Can you provide the response content of the request made during installation?

**Comment by guileh** [comment]
There is no error. The installer dialog never finish the process. But if you refresh the page and open mywebsite.com/admin/system/package/extensions they are there. Click on the red dot to enable it and that's all right.

**Comment by fschmittlein** [comment]
I'm with the same issue.

**Comment by guileh** [comment]
Like I said, It's a little bug. What matters is that you can access the ADMIN/SYSTEM/PACKAGE/EXTENSIONS and turn it on.

**Comment by MalteScharenberg** [comment]
Can one of you provide admin credentials so I can test this. You can contact me via private Gitter message.

**Comment by InfoPartizan** [comment]
http://smartseller.site/admin
Partizan
Partizan123

I can give you access to the site.
The same problem - not installed extensions and themes.
Help if you can!
I have several sites hosted on this and on all one and the same problem.
And before all is well set up.
On the other hosting everything works well.

**Comment by MalteScharenberg** [comment]
Please reopen if the issue still persists.
