### ISSUE TITLE
extentions restricted area

### ISSUE THREAD

**Issue by arash-parsi** [pagekit/pagekit#653]
## Problem

I am from Iran and you restricted Iran for downloading extensions from your website or the CMS admin marketplace menu.
Even Google Analytic stopped such restrictions for Persians after what they call `Iran Nuclear deal`. could you please stop these behaviors cause this is kind of racist now and defiantly it is not acceptable in the new world!

**Comment by florianletsch** [comment]
There is no geo restriction in place, to the best of my knowledge. What kind of error message do you receive that makes you think it is blocked from the server side?
