### ISSUE TITLE
Feature Request: sitemap generator

### ISSUE THREAD

**Issue by michidk** [pagekit/pagekit#654]
Hey,

as already mentioned in #120, a sitemap generator would be a good addition (maybe as a plugin?)
https://en.wikipedia.org/wiki/Sitemaps

**Comment by peterbrinck** [comment]
Yes, a sitemap generator would be amazing!

**Comment by michidk** [comment]
So there is a plugin now on the pagekit marketplace: https://pagekit.com/marketplace/package/tomekknapczyk/sitemap

But it doesnt work for me. Tested it on two pagekit installations.

**Comment by peterbrinck** [comment]
I've just installed it, it works great for me

**Comment by florianletsch** [comment]
It's great to see an extension appear that solves this demand. For further questions for the sitemap generator, I would suggest you head over to the according Guthub repository and open an issue there. Thanks! https://github.com/mafisz/pagekit-sitemap

And thanks to @mafisz for building this. 👍
