### ISSUE TITLE
Multiple feeds in dashboard

### ISSUE THREAD

**Issue by 834rd** [pagekit/pagekit#655]
## Problem

I've added two feed-reader. First one was the pagekit-feed (1 posts to show) and the second one, was the blog from my wife (wordpress -> 1 posts to show). 

I've reloaded my dashboard (press F5) and now i have multiple feeds from all and can't remove this, because all feeds have the same id.

Sorry for my bad englisch.

http://834rd.com/storage/Pagekit/PagekitFeeds.jpg

## Technical Details

- Pagekit version: 1.0.3
- Webserver: Apache
- Database: sqlite
- PHP Version: 7.0.4-nmm1

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by florianletsch** [comment]
Hm. So when you remove one feed, all of them disappear? When you add them again, is the issue then fixed?

**Comment by 834rd** [comment]
@florianletsch Sorry bro, but do not solved the problem. 

Tested: Relogging, Remove one, Edit one - edit works, but does not solve the problem. The one i've edit can't be removed.

**Comment by florianletsch** [comment]
Is this on a live site that is available online? Could you please send me login credentials to florian@yootheme.com so I can inspect the issue?

**Comment by florianletsch** [comment]
As I haven't heard back from you yet, I am closing this issue for now.

If this is still relevant, please send me the following details:

1. In the Pagekit database, open the `pk_system_config` table (might have a different prefix than `pk_` in your installation)
2. Find the row where the name is `system/dashboard` (usually it is the one with `id` = 1)
3. Copy the contents of the `value` column and send them to me, for example as a link to a github gist here in the issue. You could also manually remove the duplicate widgets in that json notation and save the new value, but I would like to review what exactly might have caused the broken state.
