### ISSUE TITLE
VueJS local storage error when private browsing

### ISSUE THREAD

**Issue by benedu** [pagekit/pagekit#658]
## Problem

VueJS (vuejs.min.js ) is throwing errors when no local storage is available. I came around this because one of our users uses Safari in private browsing mode. And there Safari restricted the access to the local storage. Chrome and Firefox are working fine. The quickfix for ous was to simply wrap the local storage calls in a try-catch.

The errors are:
```
15:54:49.201 TypeError: i.localStorage is null
Stack trace:
s.adapters.local.load@http://myurl.de/app/system/app/bundle/vue.js?v=8f31:1:5538
1 vue.js:1:5635
s.adapters.local.load() vue.js:1
o() vue.js:1
s.select() vue.js:1
t.exports() vue.js:1
r() vue.js:1
ki/i.use() vue.min.js:7
<anonymous> vue.js:1
e() vue.js:1
<anonymous> vue.js:1
<anonymous> vue.js:1
```

## Technical Details

- Pagekit version: latest

## Troubleshooting

- [X] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [X] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [X] I have tried disabling all installed extensions
- [X] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
Thanks for reporting! Will be fixed within the next release.
