### ISSUE TITLE
Adding extensions to the market place that are already on packagist.

### ISSUE THREAD

**Issue by crwgregory** [pagekit/pagekit#661]
## Problem

Pretty much in the title. It would be nice if this was possible, I have created an extension I host on packagist and would like to make it available in the marketplace.

Is this the intended behavior of the marketplace?

**Comment by peterbrinck** [comment]
If you go to https://pagekit.com/ and create an account, you can upload the your extension to the marketplace, and connect it to a GitHub repo, so it automatically updates from GitHub

**Comment by crwgregory** [comment]
That's what my problem is. Unless I am misunderstanding something. But I signed up and tried to publish the extension in the market place but it told me that there is already a packagist with that name. It kind of looks like the marketplace is a wrapper for packagist and that when you publish an extension on pagekit, it creates a packagist for the extension, which makes it easy to sync with git hub, very cool way to do it. Just would be nice to be able to add packages/extensions that have already been published to packagist.

**Comment by peterbrinck** [comment]
Oh, I see
Then I don't have the answer

**Comment by MalteScharenberg** [comment]
Currently it is not possible to use names at the marketplace that already exist at packagist. This has to do with Pagekits dependency resolution.

**Comment by crwgregory** [comment]
@MalteScharenberg  Can this be tagged as an enhancement and added to a queue to be worked on? Or is this very low on a priority list that I should do what @peterbrinck suggested?

**Comment by MalteScharenberg** [comment]
This is not possible without making sacrifices at performance and functionality. 

A Pagekit package can depend on packages from Packagist AND Pagekit Marketplace. Packages from both source can be required within the `composer.json` which necessitates unique names across both sources.

Another argument for unique names is the fact that the Marketplace API provides a subset of Packagist packages for performance reasons (makes communication with Packagist unnecessary). This would not be possible with name conflicts. 

Sine one can use namespaces to avoid naming conflicts, I think that this restriction is justified.

@crwgregory Just to be clear: We do not create any packages at Packagist.

**Comment by crwgregory** [comment]
I see, I guess then my question becomes: Would it be possible to use the marketplace as a package host *and* a package pointer? ( Pointing to packages installed on Packagist )

I understand why this might be unattractive from a business standpoint, but I'm still curious to see what you have to say about it.

Also does Pagekit implement a Packagist like packaging hosting system?

Thanks @MalteScharenberg!

**Comment by MalteScharenberg** [comment]
Yes, Pagekit.com implements the same packaging hosting system like Packagist does.

A package pointer would be possible. But what would be the advantage of this? Why should someone list a Pagekit extension at Packagist?

**Comment by crwgregory** [comment]
That's a good question, and I think that the use case would be quite small. Sense 
> Pagekit.com implements the same packaging hosting system like Packagist does.

However I think that it would add extensibility to the marketplace. If you could do both, why not do both? Anyone who normally uses Packagist doesn't have to stop using what they know, and still make their application available on the market. 

And anyone who didn't think they wanted their package on the market so put it on packagist, then later changed their minds and now wants it on the market place, like yours truly. :smile:

**Comment by MalteScharenberg** [comment]
I think Packagist makes more sense for things like libraries and frameworks. I can't imagine a useful scenario for a Pagekit extension on Packagist.

**Comment by crwgregory** [comment]
Fair enough. I'll rename mine when I put it up pagekit. Thanks for the responses.
