### ISSUE TITLE
Pagekit Documentation 'Events section' Link Returning 'Not Found'

### ISSUE THREAD

**Issue by crwgregory** [pagekit/pagekit#664]
[Here is the page that has the link to 'Events section' on it.](https://pagekit.com/docs/developer-basics/modules#listen-to-events)

The link points to https://pagekit.com/docs/developer-basics/architecture-events which gives a 'not found'. 

I can submit a commit if I get the right url.

Thanks!

**Comment by florianletsch** [comment]
Thanks, I have fixed the link. 

In the future, please open issues for the docs directly in the docs repository. Thanks! https://github.com/pagekit/docs
