### ISSUE TITLE
Right way to update pagekit on server.

### ISSUE THREAD

**Issue by Randore** [pagekit/pagekit#668]
Make sure to provide the following details when submitting your issue. Remove anything that doesn't apply for your scenario. Thanks!
## Problem

Update on server is not working properly.
http://prntscr.com/bcalvy
http://prntscr.com/bca2ri
http://prntscr.com/bcamlj

Your problem description here...
Even after updating the pagekit to latest version, it still doesn't show and it keeps showing that update is available and my current version to 0.11.0 pagekit.
## Technical Details
- Pagekit version: 0.11.0
- Webserver: Apache
- Database: mysql
- PHP Version: 5.6.19
## Troubleshooting
- [ Yes] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [Yes ] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [No ] I have tried disabling all installed extensions
- [Yes ] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
If the problem still exists please reopen.
