### ISSUE TITLE
Enabling new theme redirects to error page

### ISSUE THREAD

**Issue by ashrafkholeif** [pagekit/pagekit#670]
## Problem

When enabling a theme from the system settings Under **System>Themes** it redirects to an error page but the theme is successfully changed.

**here is the error page:**

_Not Found_

_The requested URL /websites/pagekitdev/admin/system/package/themes was not found on this server._

## Technical Details

- Pagekit version: 1.0.3
- Webserver: Apache/2.4.7 (Ubuntu)
- Database: mysql 5.5.49-0ubuntu0.14.04.1
- PHP Version: 5.5.9-1ubuntu4.17

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
I can not reproduce this bug. Can you provide admin credentials? You can send them to me via private Gitter message.

**Comment by ashrafkholeif** [comment]
Solved rewrite_module issue

**Comment by marechaljeremy** [comment]
Hello,

I have the same problem as ashrafkholeif. Did you find a solution to this redirect issue with a "The requested URL / admin / system / package / themes was not found on this server" error. On the other hand, the theme or the extension is well acted upon.

Thank you in advance for your answer.

Jérémy
