### ISSUE TITLE
Can not include (Vue.js) components

### ISSUE THREAD

**Issue by e-it** [pagekit/pagekit#671]
## Problem

I can not include custom Vue.js components. I followed https://pagekit.com/docs/developer-basics/vuejs-and-webpack to create a component that should provide a modal-field that should be included to the settings-view of my extension. This modal should be used multiple times on the same page with different contents, so I would prefer using a custom component instead of hard-coding it over and over again to the settings-view (`views/settings.php`).

To archive this I created the following file: `app/components/template.vue`

```
<template>
<div>Test</div>
</template>

<script>

	module.exports = {

		section: {
			label: 'Template',
			priority: 100
		}
	};

	window.Settings.components['template'] = module.exports;

</script>
```

I also updated the `webpack.config.js`

```
module.exports = [

    {
        entry: {
            "settings": "./app/views/admin/settings",
            "template": "./app/components/template.vue"

        },
        output: {
            filename: "./app/bundle/[name].js"
        },
        module: {
            loaders: [
                {test: /\.vue$/, loader: "vue"}
            ]
        }
    }

];
```

and I registered the component in the `index.php`

```
		'events'      => [
			'view.scripts' => function ( $event, $scripts ) {
				$scripts->register( 'template', 'isp:app/bundle/template.js', '~settings' );
			}
		]
```

Now I try to get the things working in the view itself. 

```
<?php
$view->script( 'settings', 'isp:app/bundle/settings.js', [ 'vue', 'uikit-form-password', 'editor' ] )  ?>
 …
<component :is="template"></component>
```

But the Test-string is not shown

## Technical Details

- Pagekit version: 1.0.3
- Webserver: Apache 2.4
- Database: MariaDB
- PHP Version: PHP 5.6

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [ ] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by crwgregory** [comment]
This is not a Pagekit issue.

**Comment by florianletsch** [comment]
The string `<component :is="template"></component>` can't just be anywhere in the document, it must be inside a Vue template, so that it is actually inside the Vue scope and Vue can instantiate the component that you've created.
