### ISSUE TITLE
Pagekit update may overwrite files in storage

### ISSUE THREAD

**Issue by florianletsch** [pagekit/pagekit#672]
The Pagekit release packages include files which are linked from the demo content (2 pagekit logos + the hero image). These packages are also used when running Pagekit updates. If a user has a file with the same name in their storage folder, this file is overwritten.

Problem: Removing these files from the release package will mean that the demo content links to missing files.

Suggestion: Host the files externally (`pagekit.com/demo-images/`) and statically link from the demo content.

**Comment by MalteScharenberg** [comment]
Files inside the storage folder are not updated automatically (https://github.com/pagekit/pagekit/blob/develop/app/installer/src/SelfUpdater.php#L20).
