### ISSUE TITLE
Impossible to add new extensions with marketplace and manual upload

### ISSUE THREAD

**Issue by SwissWar** [pagekit/pagekit#673]
## Problem

Impossible to add new extensions with marketplace and manual upload. The following error happen:

> Loading composer repositories with package information
> The "https://pagekit.com/packages.json" file could not be downloaded (HTTP/1.1 400 Bad Request)
## Technical Details
- Pagekit version: 1.0.3
- Webserver: Apache/2.4.10 (Debian)
- Database: mysql 5.5.47-0+deb8u1
- PHP Version: 5.6.17-0+deb8u1

The test server experiencing this issue is internet facing, without proxy or anything. The file "https://pagekit.com/packages.json" is accessible through wget command on this server.
## Troubleshooting
- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by SwissWar** [comment]
Screenshot of the problem
<img width="612" alt="capture d ecran 2016-06-09 a 00 18 11" src="https://cloud.githubusercontent.com/assets/3686870/15913010/13639c22-2dd8-11e6-8467-81973680faff.png">

**Comment by MalteScharenberg** [comment]
This looks like a temporary download problem. Did you try at different times?

**Comment by SwissWar** [comment]
Yes I'm still trying since yesterday at 2PM (never worked before). 

Another user on gitter tried on his own installtion:
> Rob Huijben @robhuijben juin 08 15:31
@SwissWar I just checked on my own installation, but all went fine here.

So I tried from the CLI as suggested:
> Chris @crwgregory 00:41
@SwissWar sorry you can't show me the composer.json sense it's not your extension your installing. can you run php pagekit install {vendor}/{project} from pagekit root? You'll have to find the vendor and project names.

Here is the command I've tried and the output :
`php pagekit install pagekit/extension-analytics`
![oggier net - putty](https://cloud.githubusercontent.com/assets/3686870/15924447/5dafc8b4-2e32-11e6-8ec7-77ca339af0eb.jpg)

With this error I tried to clear packages.php array as mentioned in https://gitter.im/pagekit/pagekit/archives/2016/03/04

I probably missed something in the install or other but impossible to know what !

Thanks

**Comment by SwissWar** [comment]
As suggested by @crwgregory on gitter, doing the same with -vvv flag I'm having this output:
![oggier net - putty_3](https://cloud.githubusercontent.com/assets/3686870/15933192/180c1790-2e5f-11e6-9ae0-868fd2dd0536.jpg)

Thanks for your help !

**Comment by MalteScharenberg** [comment]
Please reopen if the problem still exists.
