### ISSUE TITLE
Input of Content-fields (<v-editor>) is not validated as required when creating sites or blog-posts

### ISSUE THREAD

**Issue by e-it** [pagekit/pagekit#674]
## Problem

Input of Content-fields (`<v-editor>`) is not validated as required when creating sites or blog-posts. So empty pages can be saved.

## Technical Details

- Pagekit version: 1.0.3
- Webserver: Apache 2.4
- Database: SQLite
- PHP Version: 5.6

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
Is this a problem?

**Comment by e-it** [comment]
I think so. A blog post without content does not make a lot of sense I guess? Maybe I just miss the use-case for an empty blog page ;-).

**Comment by florianletsch** [comment]
Well, it probably doesn't make a lot of sense in a real website. But why forbid it? Sounds like Word not allowing to save empty *.doc files. 😉 

I think this is not an issue. In particular when setting up the initial structure of a website, it would be quite annoying to force some content into the editor. It's easier to just create empty pages and blog posts before you actually start filling in the content.
