### ISSUE TITLE
While installing "Portfolio" from the market place "please create a GitHub OAuth token to go over the API rate limit"

### ISSUE THREAD

**Issue by SiemdeNijs** [pagekit/pagekit#676]
Make sure to provide the following details when submitting your issue. Remove anything that doesn't apply for your scenario. Thanks!

## Problem

When I installed my first pagekit installation all went fine, now I've installed a second and when I go into the "marketplace" section and try to install "Portfolio", I get the following: 
"Could not fetch https://api.github.com/repos/claviska/SimpleImage/zipball/5be7b5c912b94b85b20e423b9b8bd4680ccaa53b, please create a GitHub OAuth token to go over the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+hrolf+2016-06-10+2033" 

I've tried downloading portfolio from github, tried the Troubleshooting, sadly without succes.

## Technical Details

- Pagekit version: latest 1.0.3
- Webserver: Apache/2.2.31 (Unix)
- Database: MySQL 5.5.48-log
- PHP Version: 5.5.35

## Troubleshooting

- [ x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [ x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [ x] I have tried disabling all installed extensions
- [ x] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
How many extensions did you install and are you on shared hosting?

**Comment by SiemdeNijs** [comment]
Thanks for your reaction, I'm not on shared hosting and I've fixed it by doing another complete re-install of Pagekit, sadly also  the database had to be deleted in order for everything to work right again.

Sadly now I'm having problems with the Portfolio extension: changing thumbsizes does not make any change at all to the front-end, cache (temp) is writable ..Pagekit can be exhausting at times.

Kindest regards and thanks for your reply.

**Comment by SiemdeNijs** [comment]
Back to the original problem after another reinstall due to instability of the extension.. 
Maybe Pagekit is just not my thing.

**Comment by alomvar** [comment]
This is a problem I know but completely outside the context of PageKit. [They have a rate limit](https://developer.github.com/changes/2012-10-14-rate-limit-changes/) for anonymous users to ensure nobody is abusing or using the API in an unfair way. You maybe get this error because there are too many unauthenticated requests to GitHub from the server you host PageKit on.

Just follow the link from your error message. You can obtain a token which will be used for requests and raises the limit outside of what one has to worry about.

**Comment by nbpalomino** [comment]
Indeed it looks not related to Pagekit. 
Which server are you hosting Pagekit?
