### ISSUE TITLE
Google page rendering instead of pagekit homepage

### ISSUE THREAD

**Issue by andreybolonin** [pagekit/pagekit#678]
Hello.

We using pagekit 1.0.2 on our VPS with php 7.0.4 on Ubuntu Server 16.04.

All work fine.

But today, we post new blog article.

And have that home page rendering this http://foxweb24.ru/

What is it ?

I try too disable all modules http://i.imgur.com/UeRi5ov.png.

I clear caches.

But nothing helps.

## Technical Details

- Pagekit version: 1.0.2
- Webserver: Apache/2.4.18 (Ubuntu)
- Database: 5.7.12-0ubuntu1
- PHP Version: 7.0.4-7ubuntu2.1

**Comment by Nayir** [comment]
What is the name of your theme ? It's a custom theme ?

**Comment by florianletsch** [comment]
This seems to be resolved? Can you provide any details what happened here?
