### ISSUE TITLE
Admin reset password is broken

### ISSUE THREAD

**Issue by Akwaryoum** [pagekit/pagekit#679]
## Problem

I can successfully rest my password on /user/resetpassword but the form on /admin/login for the password reset request is broken, there is no action url tag so the form simply does nothing and refresh the page...
I think the problem is that there is no route for @system/resetpassword/reset for some reason in [login.php](https://github.com/pagekit/pagekit/blob/master/app/system/modules/theme/views/login.php)

## Technical Details

- Pagekit version: 1.0.3
- Webserver: Apache/2.2.22
- Database: SQLite
- PHP Version: 5.6.21

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by MalteScharenberg** [comment]
fixed with https://github.com/pagekit/pagekit/commit/c9b68c08df5d4f4454f0f3e52ebe2ceb6b20b680

**Comment by Nayir** [comment]
I have no email sended when i ask for a new password.

Same issue in local or production.

**Comment by ricardobarantini** [comment]
The problem still persist.

**Comment by MalteScharenberg** [comment]
Do you have a mail smtp server configured?

**Comment by ricardobarantini** [comment]
Yes, I have. I don't need to configure anything in Pagekit, right?
