### ISSUE TITLE
InvalidArgumentException in NodeTrait.php line 31: A node cannot have itself as a parent

### ISSUE THREAD

**Issue by bOnepain** [pagekit/pagekit#680]
InvalidArgumentException in NodeTrait.php line 31:
A node cannot have itself as a parent

I'm just beginning with PageKit, and I was configuring a menu in the backoffice. Just trying to move nodes as parent or as children. I made a bad drag n drop I don't know exactly, but the fact is that one of the menu node was persisted with its own id as parent_id in the pk_system_node table.
I fixed that directly in the database. I haven't had the time right now to have a look at the code, but it seems there's a constraint missing to avoid a node to register it as parent node...

## Technical Details

- Pagekit version: 1.0.3
- Webserver: Apache/2.4.10 (Debian)
- Database: mysql 5.7.12
- PHP Version: 7.0.6-1~dotdeb+8.1

**Comment by MalteScharenberg** [comment]
Thanks for reporting!

**Comment by bOnepain** [comment]
Thanks for fixing so quickly !
