### ISSUE TITLE
Config options in database not consistently displayed in config()

### ISSUE THREAD

**Issue by xorinzor** [pagekit/pagekit#685]
Make sure to provide the following details when submitting your issue. Remove anything that doesn't apply for your scenario. Thanks!

## Problem

So the title might not be the clearest, but when using `App::module('shoutzor')->config('liquidsoap');` it will only show the default config settings as set in the `index.php` file, whereas  `App::config()->get('liquidsoap')` will display the changes to config settings as stored in the database.

This is very inconsistent behaviour and IMO not something that would be expected, is this a bug or intended?

Example:
```
$baseConfig = App::module('shoutzor')->config('liquidsoap'); //Only returns default values as stored in index.php
$config = App::config('liquidsoap')->toArray(); //only returns values that are stored in the DB, it doesn't first fetch the default values from index.php (if nothing is saved before, that means 0 results)
$config = array_merge($baseConfig, $config); //only now you have a proper list of values including changes as stored in the database
```

## Technical Details

- Pagekit version:1.0.3
- Webserver: Apache
- Database: MySQL 5.6.31
- PHP Version: 5.6.20-0+deb8u1

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [X] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [X] I have tried disabling all installed extensions
- [X] I have checked the browser developer console for JavaScript errors

**Comment by crwgregory** [comment]
Are you setting the config properly when you have a change in the config?

**Comment by xorinzor** [comment]
yes, but it will (as I said in the comments in the example) only output the values that are already stored in the database, which IMO is a bad approach.

It should always first get the default values from the index.php file (to make sure no values are left out), then merge that data with the data stored in the database.

That way you always have a complete config array WITH all the changes.

**Comment by crwgregory** [comment]
It will get defaults when no changes have been made to a default. If you change the defaults (update) then it will get those updated values. If you don't want to get the updated values then you should not be using the config option. That's the point of that config, you can set default options, then you can make updates and changes to that config. And subsequently get those changes on demand. That's what a config is.

**Comment by xorinzor** [comment]
I don't think you're understanding the issue.

If I have the default values:
- a = test
- b = test
- c = test

and I use `App::config('liquidsoap')->set('b', 'something');`

then the output from `App::config('liquidsoap')->toArray();` will ONLY be:
- b = something

it doesn't show `a` or `b` because those values didn't get saved into the database.

Expected behaviour should be to show:
- a = test
- b = something
- c = test

The same goes for `App::module('shoutzor')->config('liquidsoap')`, a complete list WITH updated values is expected, but instead only the default values are provided:
- a = test
- b = test
- c = test

**Comment by crwgregory** [comment]
Ah, that should not be the case and it looks like it is an issue then. A localized one at that as well. 

`App::module('platform/listings')->config('endpoints');`

Is the excepted syntax, and works on my company's install of pagekit. Can you do some digging into the core of pagekit and find where this may be tripping up for you?

**Comment by xorinzor** [comment]
Are you sure it still works for you when you delete the stored config options from the database?
If you aren't doing the config merge as shown in my example I expect your code to throw some errors after you do that.

I don't have an IDE that allows me to easily dig through the code :/ (I'm using Atom) so I don't think I will succeed at doing so

**Comment by crwgregory** [comment]
I have deleted the stored config options from the database before. I think I just deleted the data inside of the variable, not the entire variable. But I only did that because I messed something up and had to. 

If you deleted the entire variable, that might be why your having troubles. If you can easily make a clean install of pagekit and try to replicate the problem there. You should be getting the results you expect. Something happened to change that though.

**Comment by xorinzor** [comment]
It basically is a clean install, and I'm 100% sure the same result as explained will happen again since I tried deleting the values from the database myself which resulted in an empty array beeing returned.

**Comment by crwgregory** [comment]
If you are deleting values from the database, that is not a clean install. Pagekit might need those values to be in the database, default or not.

**Comment by xorinzor** [comment]
I understand that, but pagekit never writes the default values to the database until you tell it to.
So if I do a clean install, nothing will change.

**Comment by crwgregory** [comment]
If it works for us, but not for you, then it is a localized problem. Until you start 100% clean and can reproduce the problem, then the validity of the problem is in question.

**Comment by xorinzor** [comment]
You said you deleted the data inside a variable, never the entire variable, that's not going to reproduce the problem I'm having.

I can guarantee this is an issue with pagekit and can be reproduced in other installations.

**Comment by crwgregory** [comment]
You can't guarantee that sense it is not being reproduced in other installs of page kit. Like my entire companies.

**Comment by xorinzor** [comment]
I don't see why I wouldn't be able to guarantee that.

Doing a clean install won't change any core pagekit files, won't change my extension's files, will still be just a basic database with no additional data from my extension.

Which is the exact same as what I have right now.

**Comment by jdegger** [comment]
@xorinzor Could you maybe provide an example for us to reproduce it? I might have some time to dig into the source.


That being said, please stop this argument.. it drained my energy just reading it..

**Comment by xorinzor** [comment]
@jdegger I will put together an extension to demonstrate this, give me a moment.

**Comment by xorinzor** [comment]
Funny how things never work when you want them to..

It shows the problem, but doesn't actually store the value in the database, no clue why, there's no difference to my other plugin which does (https://github.com/xorinzor/pagekit-shoutzor-module).

Install, then go in the admin panel to the example page, it shows the problem.

https://www.jorinvermeulen.com/downloads/example.zip

**Comment by jdegger** [comment]
The values were not saved because you called `die()`. You can't do that.

So far I have determined the following things:
1. The documented way of using the config function differs from actual usage
2. You must only call the key you're looking for in the database it seems

I have not got it working so far. Maybe @ckdarby can jump on and identify the problem.

At this point I'm not sure it so much a bug with pagekit but more probably with the documentation.

**Comment by xorinzor** [comment]
Ah okay, I didn't think about that.

Maybe I am just completely misunderstanding it, but personally I'd expect that if I request a list of config values with that method, that I get the complete list (whether those values are edited or default).

Is that not the idea of these methods?  It seems kind of odd to me that you have to do an array_merge yourself to get such a list of variables.

**Comment by jdegger** [comment]
I don't have much time on hands now but I mostly compared your implementation with the formmaker extension and saw that config variables were not used in the same way. Might be worth a quick look in their source code.

**Comment by crwgregory** [comment]
Definitely right about not using die(), you can just return an empty array or something, but I think it's a Symfony thing that you have to return for the request to be fully completed? 

Another thing, when you call:
`App::config('demovalues')->set('a', 'something');`
Pagekit thinks you are requesting a module named 'demovalues'. You have to request the module 'demo' then set the config 'demovalues'. You can then pass in an array with the single value you want to change `['a' => 'something']` and Pagekit will merge that into the returned config next time the request is made.

> If you directly read the config from the module, it will still have the old value. After the next request, Pagekit will have merged the changes and made them available as the config property of the $module instance.

```
$y = [
    'a' => 'something else'
];

//Lets change and store a single value in the database
App::config('demo')->set('demovalues', $y);
```

**Comment by xorinzor** [comment]
Ah okay, yes, I see the mistake from myself here.

I modified my code to the way it should be, but it seems it still won't provide a full list of variables unfortunately.

**Comment by crwgregory** [comment]
Not sure why it would not be providing the full list. Using this action:
```
public function indexAction()
    {
        $y = [
            'a' => time(),
            'b' => 'something'
        ];

        App::config('demo')->set('demovalues', $y);

        return ['config' => App::module('demo')->config];
    }
```
I get a return of:
```
{"config":{"demovalues":{"a":1466788038,"b":"something","c":"test"}}}
```
( Refresh 1 or 2 times )

**Comment by xorinzor** [comment]
and the variable from `c` hasn't been stored in the database yet? at `pk_system_config`?

**Comment by crwgregory** [comment]
It has not.

![image](https://cloud.githubusercontent.com/assets/9405969/16344965/a6d35012-39fc-11e6-8f25-07840d1bb429.png)

**Comment by xorinzor** [comment]
I can't reproduce that same result :/ not sure why.. for me it will only show the values that are stored in the database

**Comment by crwgregory** [comment]
I'm sorry. I don't know why that would happen. A work around would be getting the entire array and setting just the keys you want, then passing that updated array to the `set` function, then all the values will be saved to the db.

**Comment by jdegger** [comment]
Confirming @crwgregory's result:

<img width="230" alt="screenshot 2016-06-24 19 17 49" src="https://cloud.githubusercontent.com/assets/14085897/16345108/67d7d1aa-3a40-11e6-8e6b-28e96190bcce.png">

**Comment by xorinzor** [comment]
hmm okay, the demo extension does work for me, whereas my own extension doesn't.

I'm glad pagekit has this properly implemented then, now I know it's something that I've caused (the only question beeing, what).

Thanks guys.

**Comment by xorinzor** [comment]
Ah, it had to do with the name provided.

Ie: 
- `App::module('shoutzor')`
- `App::config('shoutzor')`
- `App::config('xorinzor/shoutzor')`

Both `shoutzor` and `xorinzor/shoutzor` were working for config() but only `shoutzor` was working for `module` (why I don't quite understand, because I imagine you'd actually WANT to use the full author/extension combination to prevent duplicate extension name issues).

**Comment by florianletsch** [comment]
I am happy this has been sorted out. Still, it's frustrating to see that this seems to be quite misleading. Do you guys have any advice how we can improve the according section in the docs? https://pagekit.com/docs/developer/modules#default-module-configuration

**Comment by xorinzor** [comment]
@florianletsch I'm not sure, perhaps a clear warning that using `$app->config()` will only return the default config options as set in index.php ?

I still find it odd though that the behaviour is so different, especially since you use the exact same method to write changes *to* a config file, you'd expect it to also *get* them
