### ISSUE TITLE
Update not possible / wrong file permissions (but they are correct)

### ISSUE THREAD

**Issue by e-it** [pagekit/pagekit#689]
## Problem

I tried to update Pagekit to 1.0.4 - but the update-progress fails:

```
'app/assets/codemirror/codemirror.css' not writable
'app/assets/codemirror/codemirror.js' not writable
'app/assets/codemirror/hint.css' not writable
'app/assets/jquery/AUTHORS.txt' not writable
'app/assets/jquery/bower.json' not writable
'app/assets/jquery/dist/core.js' not writable
'app/assets/jquery/dist/jquery.min.js' not writable
'app/assets/jquery/dist/jquery.slim.js' not writable
'app/assets/jquery/dist/jquery.slim.min.js' not writable
'app/assets/jquery/LICENSE.txt' not writable
'app/assets/jquery/README.md' not writable
'app/assets/js-md5/bower.json' not writable
...
```
All files are owned by `web1:web1` which is the user the PHP-script runs at. All files are `-rw-r--r--`so the user can read and write.

## Technical Details

- Pagekit version: 1.0.3
- Webserver: Apache 2.2
- Database: SQLite
- PHP Version: 5.6.23-1~dotdeb+7.1

Permissions: 
<img width="888" alt="bildschirmfoto 2016-07-01 um 12 55 42" src="https://cloud.githubusercontent.com/assets/10261817/16519696/23098b2c-3f8b-11e6-8026-3903bbe3f8a0.png">

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by e-it** [comment]
Got the same error on another machine.

Both are debian-based machines.

**Comment by florianletsch** [comment]
I think at least the directories need to be executable as well, in order to allow entering and "changing" (=adding, removing files etc) the directory. Here is some more explanation on how permissions work on directories: http://unix.stackexchange.com/questions/21251/how-do-directory-permissions-in-linux-work

**Comment by florianletsch** [comment]
I am simply assuming my previous remark was correct (let's hope it is :smile:). I am closing this for now, please comment in case this is still an issue.

**Comment by crwgregory** [comment]
I was having an issue similar to this when I cloned the project from git. I have no idea what was going wrong but I was getting a 403 on my localhost using XAMPP. Changing the directory name from 'pagekit' to 'pagekit-fork' worked for me. Some reason the server configuration didn't like the directory to be named pagekit...?

**Comment by wuliupo** [comment]
@crwgregory
The folder name should **NOT** be `pagekit`, it is hardcode in `.htaccess` if using apache (XAMP, WAMP..)
```
<FilesMatch "(...|pagekit)$">
      Require all denied
</FilesMatch>
```
https://github.com/pagekit/pagekit/blob/develop/.htaccess
