### ISSUE TITLE
Uploads no longer working after 1.0.4 update

### ISSUE THREAD

**Issue by gholleyd** [pagekit/pagekit#691]
## Problem

Uploads are no longer working after the 1.0.4 update

![image](https://cloud.githubusercontent.com/assets/19509971/16534976/fceedbca-3fa0-11e6-99eb-182b305e16e2.png)

Seems related to the update to UIkit 2.26.3

## Technical Details

- Pagekit version: 1.0.4
- Webserver: Apache 2.4
- Database: MySQL 5.5.5-10.1.10-MariaDB
- PHP Version: 5.6.19

## Troubleshooting

- [x] I have enabled debug mode: https://pagekit.com/docs/troubleshooting/debug-mode
- [x] I have verified the server requirements: https://pagekit.com/docs/getting-started/requirements
- [x] I have tried disabling all installed extensions
- [x] I have checked the browser developer console for JavaScript errors

**Comment by e-it** [comment]
Got the same error on another machine.

Both are debian-based machines.

**Comment by gholleyd** [comment]
Closing this issue after seeing update to 1.0.5
