### ISSUE TITLE
mod rewrite enabled, but navigation still links to /index.php/...

### ISSUE THREAD

**Issue by michidk** [pagekit/pagekit#693]
Hey,

i purchased a webserver (and this one is only a webserver with no access to the cli) and installed pagekit on that server.
First links like http://myDomain.de/home didn't work, because i had to define this line in my .htaccess file: ` RewriteBase /` After i did this, links like http://myDomain.de/home finally worked.

## Problem

Now the problem is, that the navigation links are still pointing to http://myDomain.de/index.php/myPage

## Technical Details

- Pagekit version: 1.0.3
- Webserver: Apache
- Database: MySQL 5.5.49-0+deb7u1-log
- PHP Version: 5.5.36

**Comment by florianletsch** [comment]
Can you review https://github.com/pagekit/pagekit/issues/642 to see if you have the same server setup (Apache, but running with FastCGI and therefor Pagekit doesn't detect mod_rewrite). Also, there is a quick fix linked in the issue, although that fix isn't upgrade-safe.

**Comment by michidk** [comment]
That fixed it! 
Apache is running with cgi-fcgi.

But now on the Dashboard, pagekit tells me that my pagekit version is outdated and i should update to pagekit 1.0.5? That message wasn't there before. And on other pagekit installations i manage, this message isn't shown, too.

**Comment by michidk** [comment]
I wouldn't close that issue... 
this should be fixed in pagekit.. Wordpress doesn't have that issue.

Changing that file after every pagekit update can't be a solution.

**Comment by florianletsch** [comment]
You're right, there should be a better option than the dirty fix that is listed in the issue I linked. However, I think this is a duplicate of #505 which is still open. :)
