### ISSUE TITLE
error running webpack

### ISSUE THREAD

**Issue by seltzlab** [pagekit/pagekit#694]
## Problem

Running webpack fails with the following error:
ERROR in ../system/app/vue.js
    Module not found: Error: Cannot resolve 'file' or 'directory' /home/antonio/Workspace/IIT/pagekit/app/system/../assets/vue-form/dist/vue-form.common.js in /home/antonio/Workspace/IIT/pagekit/app/system/app

Here is the complete webpack log: https://gist.github.com/seltzlab/50a6b5f8674fe0643430db3317a8baa0

## Technical Details

- Pagekit version: 1.0.5
- Webserver: apache2
- Database: MySQL 5.7
- PHP Version: 5.6

**Comment by MalteScharenberg** [comment]
Vue-Form changed its version in 1.0.5. Try to run `bower update`.

**Comment by seltzlab** [comment]
Thanks for instant reply!

I tried with bower update but still the same issue.
Here it is the bower log: https://gist.github.com/seltzlab/fcbc0c7d1866223210d7c1e6e03b7a83

**Comment by seltzlab** [comment]
Running also npm install didn't solve the problem

**Comment by MalteScharenberg** [comment]
Sometimes Bower dose not work as aspected. Delete the vue-form folder and run `bower install` again.

**Comment by seltzlab** [comment]
That did the trick.
Note that I removed vue-form, vue-intl and vue-resource to make it works

**Comment by wuliupo** [comment]
yes, it is a summary:

```
npm install
rm   -rf app/assets/vue-form   app/assets/vue-intl   app/assets/vue-resource
bower update
webpack
gulp
```

and the package name should **NOT** be pagekit, such as change it to `pagekit-fork`
https://github.com/pagekit/pagekit/issues/689
