### ISSUE TITLE
Magic method __callStatic of StaticTrait passes object to 'call_user_func_array'

### ISSUE THREAD

**Issue by crwgregory** [pagekit/pagekit#706]
## Problem

I am trying to call a closure function with `App::myFunction()` and pass a parameter to it: `App::myFunction($string)`, when the method hits `__callStatic` the first thing it does is get the `$value` from `static::$instance->offsetGet($name);`. This returns the object from the function I want to call. It then checks if I added any `$args` to the call, and sense I did it tries to use `call_user_func_array` and pass in the `$value` object as it's callback when it needs to be a string of the function name.

Am I doing something wrong? I think that `offsetGet` should be returning a namespace in this instance. My closure looks like:

```
$app['myFunction'] = function($string) {
   return new MyObject($string);
}
```
## Technical Details
- Pagekit version: 1.0.5
- Webserver: XAMPP
- Database: SQL
- PHP Version: 5.6.21

**Comment by MalteScharenberg** [comment]
Please use Gitter or the Pagekit Forum for support questions.
