### ISSUE TITLE
How to delete Widgets?

### ISSUE THREAD

**Issue by sulivieri** [pagekit/pagekit#709]
## Problem

How can i delete a widget?
when i select a widget by the checkbox no option for delete is displayed
(just publish, unpublished, copy, move)
it's normal?

thanks

## Technical Details

- Pagekit version: 1.0.5
- Aurora Theme

**Comment by sulivieri** [comment]
I noticed that:
- using One Theme, option for delete widgets is available.
- using Aurora Theme, option is not available.

**Comment by MalteScharenberg** [comment]
So this can be closed? :)
