### ISSUE TITLE
Uikit slideshow issue in Pagekit 1.0.5

### ISSUE THREAD

**Issue by Sulpher** [pagekit/pagekit#715]
## Problem
After updating Pagekit to version 1.0.5 I have noticed a problem with Uikit slideshow.
There is so-called "blinking" effect when I am switching slides. 
The HTML code is typical and taken from example: http://getuikit.com/docs/slideshow.html

Your problem description here...
Uikit Slideshow component works incorrectly in Pagekit 1.0.5. the slide is "blinking" during the switching.

I've uploaded a temporary video to show the problem:
https://youtu.be/TzUY75W7cWA

## Technical Details

- Pagekit version: 1.0.5
- Webserver: 	Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.4.45
- Database: sqlite 3.7.17
- PHP Version: 7.0.9

**Comment by Sulpher** [comment]
Oh, it seems I forgot to publish the video. I am sorry.  The link above must be available.

**Comment by Sulpher** [comment]
I updated Uikit to ver.2.26.4 in Pagekit 1.0.5 and it solved the problem.

**Comment by MalteScharenberg** [comment]
Thanks for pointing this out. The next Pagekit release will contain the latest UIkit version.
