### ISSUE TITLE
Module API REST

### ISSUE THREAD

**Issue by GlauberF** [pagekit/pagekit#716]
## Module API REST

Hello,
you have the api module , which is made the REST calls to available I pay?
the module responsible for processing and return json , https://pagekit.com/api/
I buy the module , paid for it .

**Comment by GlauberF** [comment]
??

**Comment by MalteScharenberg** [comment]
What do you have in mind? You can find lots of examples in Pagekit where JSON is returned. We are not selling our internal API.

**Comment by GlauberF** [comment]
I need an internal api, like yours, I will work with some Brazilian clients, some unique to my company and theme related to our area.
You could develop this api or assign the api you as an example?

**Comment by MalteScharenberg** [comment]
I'm sorry, we do not take custom orders. I will close this issue because it dose not follow our [contribution guidelines](https://github.com/pagekit/pagekit/blob/develop/.github/CONTRIBUTING.md#issues). Please use Gitter or our Google group for further questions.

**Comment by GlauberF** [comment]
ok
