### ISSUE TITLE
manually install a module developed

### ISSUE THREAD

**Issue by GlauberF** [pagekit/pagekit#718]
## Problem

was developing extensions and the same work, I began to develop modules, took the example of google analytics and tried to manually put the package folder, but it does not work, how do I install it manually, and the Analystics folder inside package?

**Comment by MalteScharenberg** [comment]
The `composer.json` and `index.php` must be present inside of your extension folder.

**Comment by GlauberF** [comment]
installed manually when I click request code , it returns the error that is in the image.


![oauth](https://cloud.githubusercontent.com/assets/11314585/17111926/21e5662e-527a-11e6-9eb2-2a36ee741f42.png)

**Comment by GlauberF** [comment]
I noticed that when you install manually, it does not update the dependencies automatically and does not generate the Lusitanian folder , which is out of / packages / pagekit not just include the analytics folder inside / packages / pagekit , must have some command to update and seek the dependencies that the module needs and then installing the module , could you help me?
If you have any command via composer to manually install this module, after he was in the packages folder / pagekit ?
Help me :)

**Comment by MalteScharenberg** [comment]
We have a [Command](https://github.com/pagekit/pagekit/blob/develop/app/console/src/Commands/UpdateCommand.php) for this.
