### ISSUE TITLE
Missing pages in sub-folder feature

### ISSUE THREAD

**Issue by jpl42** [pagekit/pagekit#725]
## Problem
No function for sub-folder pages. I can create a page at root (example.com/contact), I can create a blog and have pages in `blog` sub-folder (example.com/blog/first-post); but cannot create pages in a custom sub-folder (example.com/downloads/file-1). I think that this is probably a feature request as I've never noticed this option anywhere, but if I'm missing the obvious please let me know how.
Besides this lacking of a basic feature I love Pagekit and have used it in production for months, thanks Pagekit devs and to anybody who can update me on this problem.

## Technical Details
- Pagekit version: 1.0.5
- Webserver: nginx 1.10.0
- Database: sqlite 3.11.0
- PHP Version: 7.0.8

#### Duplicate of 452

**Comment by mariolacko** [comment]
How to create a sub-folder page (Example):
1. Create a page (example.com/portfolio)
2. Create another page (eample.com/shop)
3. Drag & Drop page "shop" to right (that create example.com/portfolio/shop)

**Comment by jpl42** [comment]
Worked, thank you!
