### ISSUE TITLE
Feature Request: Add RSS Subscription for Blogs

### ISSUE THREAD

**Issue by chao10** [pagekit/pagekit#731]
## Problem
I think it would be quite necessary to add RSS for blogs (and perhaps comments) so that end users can subscribe to the rss source. This feature could be provided as a plugin, just like the search plugin.

Thanks.

## Technical Details

- Pagekit version: 1.0.7
- Webserver: Nginx 1.4.6
- Database: MySQL 5.5
- PHP Version: 5.5.9

**Comment by florianletsch** [comment]
The blog already generates an RSS feed that users can subscribe to.

For example the official Pagekit Blog: https://pagekit.com/blog ...has its RSS feed at https://pagekit.com/blog/feed
