### ISSUE TITLE
pagekit auto complete

### ISSUE THREAD

**Issue by upliu** [pagekit/pagekit#734]
We use App::module('session') to get  Session components ,
How can I make IDE to auto complete the methods or properties in the object.

**Comment by nbpalomino** [comment]
What IDE do you use? PhpStorm ? NetBeans?

**Comment by crwgregory** [comment]
I use PhpStorm and I could never get it to register for auto complete on those static methods. The way those methods are implemented at runtime and query objects based on strings, makes it impossible for for any IDE to pick up what your putting down.
