### ISSUE TITLE
giving this error when you click install packages pagekit

### ISSUE THREAD

**Issue by GlauberF** [pagekit/pagekit#736]
## Problem

giving this error when you click install packages pagekit.
version of pagekit:  1.0.7
## Technical Details

![erro](https://cloud.githubusercontent.com/assets/11314585/17777306/71ff24b4-6536-11e6-919f-41f8b255a571.png)

**Comment by MalteScharenberg** [comment]
Remove the contents form the array in `packages/packages.php` and try again.

**Comment by MalteScharenberg** [comment]
Please reopen if the issue still exists.
