### ISSUE TITLE
Async or Defer options do not work for dependencies 

### ISSUE THREAD

**Issue by dawid-in** [pagekit/pagekit#738]
This:
`<?php $view->script('theme', 'theme:js/theme.js', ['uikit-sticky',  'uikit-lightbox',  'uikit-parallax', 'uikit-slideshow', 'verticalDropdown'], ['defer', 'async']) ?>`
Will load theme.js asynchronously. It would be nice to have an option to load the dependencies asynchronously.

**Comment by jdegger** [comment]
Duplicate https://github.com/pagekit/pagekit/issues/682 @MalteScharenberg
