### ISSUE TITLE
GZIP Compression

### ISSUE THREAD

**Issue by autosta** [pagekit/pagekit#739]
## Problem

I cannot enable GZIP compression for my pagekit website. Compression is enabled and it works on my other websites that are not pagekit and are hosted on the same server. Would be very grateful if anyone has any suggestions.
## Technical Details
- Pagekit version: 1.0.2
- Hosting: Shared
- PHP Version: 5.6

**Comment by jdegger** [comment]
You omitted the most important part of the technical details. What server do you use and what does your network structure look like?

Is this hosted on shared hosting, vps, microservice provider (docker, heroku, aws?).

**Comment by autosta** [comment]
It is hosted on shared hosting.

**Comment by nbpalomino** [comment]
+1 on @jdegger reply... 

Give more info please.
