### ISSUE TITLE
Problems with browser cache

### ISSUE THREAD

**Issue by LrMiLoef** [pagekit/pagekit#740]
## Problem

I have a problem with the brwosercaching of js files, that are included into die view php files of my extension. In the deveoloper console i can see that pagekit appends something like "?v=3326" to the js files. How can i count this version up to force a refresh of the browser cache? 

## Technical Details

- Pagekit version: 1.0.8
- Webserver: apache
- Database: mysql
- PHP Version: 7

**Comment by jdegger** [comment]
Either updating the config secret or the version number seems to trigger it. I'm not sure if you should do that without knowing the consequences (breaking stuff that's being used by the secret of disabling the update method)

https://github.com/pagekit/pagekit/blob/6d881162c0f62e482aeea176cfeb58bc859a54f8/app/system/src/SystemModule.php#L26-L27

**Comment by LrMiLoef** [comment]
because of this i created the issue :-) What is the best way to clear the java cache when i have done some changes in the js files of an extension.

**Comment by MalteScharenberg** [comment]
You are trying to solve this problem in the wrong place. This cache is designed to break all caches after system updates by changing the filenames. If you use this mechanism during development, you have to change the name after each change, which is not an elegant solution.

Best practise for this is to simply disable your browsers cache. All major browsers provide settings for this (e.g. Chrome even has a setting for just disabling caching if the dev tools are open).

**Comment by LrMiLoef** [comment]
Ok.. but what happens if i have created an update-package for my extension? Will the version number also change in that case? I can't tell all the visitors of my page to clear the cache manually, you know?

**Comment by MalteScharenberg** [comment]
You can provide the version number of your extension when adding new scripts. By doing so Pagekit will use this version for calculating the cache breaker instead of the Pagekit version.

**Comment by malles** [comment]
If you include your scripts like this, the version of your module will be in the header, breaking the users cache on update.
```php
$view->script('m-script', 'namespace/module:app/bundle/script.js', ['vue','uikit-tooltip'], ['version' => App::config('system')->get('packages.namespace/module')]); 
```
While developing, disabling the browsers cache should work.
