### ISSUE TITLE
Pagekit self-update command fails

### ISSUE THREAD

**Issue by mpavel** [pagekit/pagekit#741]
## Problem

I wanted to update Pagekit from 1.0.5 to latest version. I first tried this via command line by running:
`./pagekit self-update`. The output I received is the content of a webpage, which inside the body has `<h1>Whoops, looks like something went wrong.</h1>`.

I checked at the recommended way to update Pagekit, and went with the update in the admin panel. Update was successful. After update, I wanted to run `./pagekit self-update` to see what I get. Same result.

I checked the `app/console/src/Commands/SelfupdateCommand.php` and it seems the problem comes from [line 42](https://github.com/pagekit/pagekit/blob/develop/app/console/src/Commands/SelfupdateCommand.php#L42) (`$this->client = new Client;` - >GuzzleHttp\Client). However, I can't find a reference to GuzzleHttp anywhere in the dependencies (by looking at Composer).

After a quick `grep -r 'Guzzle' ./*` in the project folder, I see Guzzle being referenced in the following places:

* `./app/console/src/Commands/SelfupdateCommand.php:use GuzzleHttp\Client;`
* `./app/console/src/Commands/SelfupdateCommand.php:use GuzzleHttp\Exception\BadResponseException;`
* `./app/console/src/Commands/SelfupdateCommand.php:use GuzzleHttp\Exception\TransferException;`
* `./app/console/src/Translate/TransifexApi.php:use GuzzleHttp\Client;`
* `./app/vendor/monolog/monolog/tests/Monolog/Formatter/NormalizerFormatterTest.php: `
* `./CHANGELOG.md:- Removed Guzzle dependency` 

So, according to Changelog, Guzzle dependency was removed in version 0.11.3 (April 7, 2016). Not sure what the plan is for `self-update`, so I'm making this issue here to reference the problem I found (couldn't find another issue which talks about `self-update`).

## Technical Details

- Pagekit version: 1.0.5 and 1.0.8
- Webserver: 	nginx/1.9.14
- Database: SQLite 3.8.2
- PHP Version: 7.0.5-2+deb.sury.org~trusty+1

**Comment by MalteScharenberg** [comment]
Thanks for reporting!

**Comment by Eihrister** [comment]
I'm having the same problem, right now, with 1.0.8.

**Comment by tobbexiv** [comment]
The fix for this is not delivered yet. So 1.0.8 still contains this bug and only the next version should not have it any more.
