### ISSUE TITLE
Request for more widgets

### ISSUE THREAD

**Issue by PrimozRome** [pagekit/pagekit#743]
I would like to see more widget designs especially in category

- sales
- financial and
- statistics

It would be pretty cool to have designs for something like

- top 5 or top N [customers, suppliers, products, etc...]
- sales figures in comparison to previous year
- sales by region, countries, quarters
- highest cost 
- etc...

Thanks

**Comment by florianletsch** [comment]
Thanks for your ideas. I think these would be great as extensions, as the ideas are very focussed on a particular kind of website. I am closing this now, as this is not a request for the Pagekit core.
