### ISSUE TITLE
Add Page

### ISSUE THREAD

**Issue by xtech86** [pagekit/pagekit#746]
Hello,

This is more of a suggestion before I submit a pull request. At present when viewing the Pages in the Admin UI. There is an button 'Add Page' but the wording is wrong since you can Add Page and Add Link it's no longer valid.

I suggest here we change:

Add Page

to

Add +

Many thanks
Tony

**Comment by florianletsch** [comment]
Thanks, we'll pass this idea on to our design and UX team.
