### ISSUE TITLE
Theme Page Overwrites (Custom Maintenance and Error Pages)

### ISSUE THREAD

**Issue by luisreyes** [pagekit/pagekit#748]
## Problem

Cannot overwrite system theme views. i.e. maintenance.php and error.php

`/packages/my-themes/my-theme/views/system/theme/maintenance.php` 
This is not recognized and the default one renders instead
`/app/system/modules/theme/views/maintenance.php`

Other system views CAN be overwritten. i.e. page.php, user/login.php
`/packages/my-themes/my-theme/views/system/site/page.php`
`/packages/my-themes/my-theme/views/system/user/login.php`
## Technical Details
- Pagekit version: 1.0.8
- Webserver: maMP
- Database: SQLite
- PHP Version: 7.0

**Comment by MalteScharenberg** [comment]
The maintenance page is currently rendered too early to be overwritten.

**Comment by luisreyes** [comment]
I solved my issue by making my own custom maintenance page workflow.

**template.php** now checks the value of the maintenance checkbox
```php
<?= $view->render((!$params['maintenance.enabled'] || $app->user()->isAuthenticated()) ? 'theme/layout.php' : 'theme/maintenance.php', ['params' => $params]) ?>
```

The **template.php** page then redirects accordingly.
My custom **maintenance page** also packs more options.
I need more control for my clients.

<img width="1052" alt="screen shot 2016-11-14 at 8 42 05 pm" src="https://cloud.githubusercontent.com/assets/928544/20289961/f4c26e24-aaaa-11e6-8662-9a308820212b.png">

**Comment by tobbexiv** [comment]
@MalteScharenberg I was able to overwrite the maintenance page the same way you can overwrite the error page after I changed this line to `$response = App::view('system/maintenance.php', compact('message', 'logo'));`: https://github.com/pagekit/pagekit/blob/c76ae5741bafc8b66bc07d102338c7ffe2484638/app/system/modules/site/src/Event/MaintenanceListener.php#L25

So it does not seem to be too early. Or is there anything I miss why this should not be changed? If you don't see any objections I will create a PR if I find the time.

**Comment by MalteScharenberg** [comment]
@tobbexiv If you just remove the prefix, Pagekit wont find the maintenance view because it is located in the admin backend theme.

**Comment by tobbexiv** [comment]
@MalteScharenberg For me it worked in my dev environment. I removed the prefix and was able to use the default maintenance page as well as to overwrite it. The `system` shortcut which allows for this is defined [here](https://github.com/pagekit/pagekit/blob/c76ae5741bafc8b66bc07d102338c7ffe2484638/app/system/modules/theme/index.php#L67) if I see it correctly.
