### ISSUE TITLE
Listener called 141x

### ISSUE THREAD

**Issue by Smeaven** [pagekit/pagekit#750]
## Problem

I created my own Listener which subscribes to the event `route.configure` (to read a custom annotation). I dont know why, but it is called 141x. I tested this with printing a simple string in the listener's method and counting it on clientside.

## Technical Details

- Pagekit version: 1.0.8
- Webserver: Pagekit's
- Database: SQLite
- PHP Version: 5.6

**Comment by MalteScharenberg** [comment]
This event is triggered every time a route is added. Based on this, I would guess that you have 141 routes registered.
