### ISSUE TITLE
Failed to open stream: Operation not permitted

### ISSUE THREAD

**Issue by ivapelc** [pagekit/pagekit#753]
After all I managed to install the Pagekit succesfuly (trouble with PeaZip not showing/extracting most of the files in ZIP). Now I want to install extensions/themes, but every single one (except for Shortcuts which somehow installed after many tries) gives me similar error:

> Loading composer repositories with package information
> Updating dependencies
> - Installing pagekit/theme-hello (1.0.3)
>   Downloading
>   The "https://pagekit.com/package/pagekit/theme-hello/1.0.3.zip" file could not be downloaded: failed to open stream: Operation not permitted
- Pagekit version: 1. 0. 8.
- Webserver: Apache
- Database: MySQL   5.5.5-10.1.14-MariaDB
- PHP Version: 5.6.16

**Comment by MalteScharenberg** [comment]
Seems like external downloads are not permitted in your environment. Are your running at localhost or online hoster (if yes which one?)?
