### ISSUE TITLE
[Feature Request] Enqueue scripts in footer

### ISSUE THREAD

**Issue by mihokovic** [pagekit/pagekit#761]
## Problem

There's still no option to make PageKit enqueue scripts in footer rather than head using a php function/command.
It would be great if `$view->script($id, $path [, $dependencies ])` had one more parameter that'd let us choose enqueue position.

`defer` or `async` really have nothing to do with this so please don't point to that like in previous threads related to this issue.

Also, I've noticed the area in `/admin/site/settings` that says

> Insert code in the header and footer of your theme. This is useful for tracking codes and meta tags.

It's not really convenient to use a web interface to include scripts in footer if all the coding is done outside. This area is good for exactly what it says - tracking codes.
## Temporary workaround

I thought of a temporary workaround, so if anyone else wants to achieve this right now no matter how, here you go:

`<script src="<?= $view->url()->getStatic('theme:js/theme.js') ?>"></script>` - place this right before `</body>` tag and you're all set.

Obviously this was meant for local scripts because there's no other way to include them in footer unless you want to manually write the whole local url, which is not really advisable.
Since this is only a workaround, you can't set parameters such as `$id` or `$dependencies` but it works. And for external scripts you just do usual `<script src=""></script>` - placing it in the footer as well.
## Technical Details
- Pagekit version: 1.0.8

**Comment by MalteScharenberg** [comment]
Why are `async` or `defer` not related to enqueuing scripts in the footer? I think both are solving the same issue.
