### ISSUE TITLE
Suddenly login does not work

### ISSUE THREAD

**Issue by mino72** [pagekit/pagekit#769]
## Problem

Suddenly login does not work, user name and password are correct, how to solve? thank you for our fantastic work! :-)

## Technical Details

- Pagekit version: 1.0.8
- Webserver: Apache
- Database: SQLite
- PHP Version: 5.6.24

**Comment by tobbexiv** [comment]
Your page also throws an error which indicates that your database is corrupted. So the database file you have is somehow broken. Read statements on the database seem to still work, but everything which is an insert or update fails. A cause for this might be an unsafe copying of he database while it was in use.

In most cases this can be solved by safely copying the database to a new file which then replaces the old one in the end. The question is now how your access to the server is, so can you access a command line, and how your technical skills are, so are you able to do such a safe copy.

However this stackoverflow question contains some information on this problem and possible solutions: http://stackoverflow.com/questions/5274202/sqlite3-database-or-disk-is-full-the-database-disk-image-is-malformed
So you either might use this information on your own or you have someone who can help you with this.

**Comment by mino72** [comment]
Thank you so much for your answer,
my technical skills are very limited :-) ... let's see what I can do.

I do not understand how it could have happened, but I have to say that I was already successful but it was the beginning of the construction of the site is've redone all over again.

However your work is excellent!

**Comment by mino72** [comment]
Solved!

I followed these instructions:
[https://community.spiceworks.com/how_to/1468-how-to-fix-corrupt-sqlite-database](https://community.spiceworks.com/how_to/1468-how-to-fix-corrupt-sqlite-database)

regards
