### ISSUE TITLE
PageSpeed Insights reports a bad score

### ISSUE THREAD

**Issue by FDiskas** [pagekit/pagekit#772]
## Problem
PageSpeed Insights reports a bad score because of blocking js.
More info here: https://developers.google.com/speed/docs/insights/BlockingJS
And here: https://developers.google.com/web/fundamentals/performance/critical-rendering-path/adding-interactivity-with-javascript

**Comment by MalteScharenberg** [comment]
Blocking JS is already discussed here: https://github.com/pagekit/pagekit/issues/682.
On https://pagekit.com we are experimenting with asynchronous asset loading, which results in a better [score](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fpagekit.com&tab=desktop).
