### ISSUE TITLE
Trouble connecting with demo.pagekit.com versus pagekit.com

### ISSUE THREAD

**Issue by visualinventor** [pagekit/pagekit#775]
<img width="624" alt="screen shot 2016-11-29 at 4 29 20 pm" src="https://cloud.githubusercontent.com/assets/115391/20731837/ab5d1574-b651-11e6-9d47-98bd328737a0.png">
## Problem

I am having an issue installing any new anything from the marketplace. I can confirm that the Db and the code is working correctly but it appears there is some issue with composer.

## Technical Details

- Pagekit version: 1.0.9
- Webserver: Apache Lightspeed
- Database: Mysql
- PHP Version: 5.6

When attempting to install anything from the Marketplace I keep getting this error:

`Loading composer repositories with package information
The "https://pagekit.com/packages.json" file could not be downloaded: Peer certificate CN=`demo.pagekit.com' did not match expected CN=`pagekit.com'
Failed to enable crypto
failed to open stream: operation failed`

**Comment by MalteScharenberg** [comment]
Which OS and which OpenSSL version is running on your server?

**Comment by visualinventor** [comment]
`openssl version -a`

reveals ...

`OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008
built on: Tue May 31 05:53:49 EDT 2016
platform: linux-elf
options:  bn(64,32) md2(int) rc4(idx,int) des(ptr,risc1,16,long) blowfish(idx) 
compiler: gcc -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -I/usr/kerberos/include -DL_ENDIAN -DTERMIO -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=generic -fasynchronous-unwind-tables -Wa,--noexecstack -DOPENSSL_USE_NEW_FUNCTIONS -fno-strict-aliasing -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DMD5_ASM -DRMD160_ASM -DAES_ASM
OPENSSLDIR: "/etc/pki/tls"
engines:  padlock dynamic `

**Comment by MalteScharenberg** [comment]
This version is from 2007. Are you able to update?
