### ISSUE TITLE
Wrong information showed up on update page + German language error

### ISSUE THREAD

**Issue by acon1000** [pagekit/pagekit#786]
## Problem

In my German Pagekit I've opened the update section.
I've got the option to update to version 1.0.10 which I already have. There was no reaction by clicking the update buttons. After a refresh I've got the usual page with the information that there is no update available.
Also the German text is wrong when an update is available. It says "keine" instead of "eine". One letter but a big difference.

Screenshots:

![2016-12-23_114447](https://cloud.githubusercontent.com/assets/24732267/21452480/78fa2a04-c907-11e6-8329-739948f9a346.png)
![2016-12-23_115356](https://cloud.githubusercontent.com/assets/24732267/21452481/7b7a1a14-c907-11e6-9203-954d9ad7b0f2.png)

## Technical Details

- Pagekit version: 1.0.10
- Webserver: Linux
- Database: MySQL 5.6.33
- PHP Version: 5.6.19

**Comment by MalteScharenberg** [comment]
Thanks, I've corrected the translation strings. 
The wrong string is only in the Switzerland translations, Germans are fine.

Best Regards
Malte
