### ISSUE TITLE
A lot of console warnings when enable debug mode

### ISSUE THREAD

**Issue by duy-ly** [pagekit/pagekit#788]
## Problem

I pulled a fresh new pagekit from develop branch, run composer and npm install, then open the admin page and enable the debug mode. A lot of console warning appear in Chrome developer tools.
<img width="1264" alt="screen shot 2017-01-03 at 10 24 11 pm" src="https://cloud.githubusercontent.com/assets/3692616/21612518/22513304-d204-11e6-893d-7fb83e3bb54e.png">

## Technical Details

- Pagekit version: 1.0.10
- Webserver: Apache/2.4.18 (Unix) 
- Database: MySQL 5.7.15
- PHP Version: PHP/7.1.0

**Comment by deviprsd21** [comment]
It's a normal thing. Here vue is just suggesting to initialize variables in the `data` key to improve performance. Either way these are just warnings nothing serious.
