### ISSUE TITLE
When UIkit 3 will be added to the Pagekit natively?

### ISSUE THREAD

**Issue by hanlan** [pagekit/pagekit#790]
As titled, the UIkit 3 is a fantastic new weapon, since the file structure has been changed a little, manually updated UIkit in a pagekit system will not work unless to do a lot of modification, apparently this is not everyone want.

So, when the Pagekit will be updated and come with the UIkit 3 natively?

Thanks.

**Comment by Yanbo** [comment]
Or is there any way to update by hand to support uikit3?

**Comment by erikperin** [comment]
When? When? When?

**Comment by deviprsd21** [comment]
I think we should wait for UIKit to come out of beta stage first.

**Comment by KrakenEXE** [comment]
Is there any update on this?

**Comment by saschadube** [comment]
We have to wait till [UIkit 3](https://getuikit.com) is feature complete and out of Beta status. Once it is ready it will be integrated in Pagekit.
