### ISSUE TITLE
An error occurred when the installation was completed and jumped to the '/index.php/admin' page

### ISSUE THREAD

**Issue by inhere** [pagekit/pagekit#794]
## Problem

An error occurred when the installation was completed and jumped to the '/index.php/admin' page

```
Symfony\Component\Debug\Exception\ContextErrorException: Warning: include(/var/www/xxxx/tmp/cache/2b60fdebcaa75fe3e459bd0870b76f01c6077700.cache): failed to open stream: No such file or directory in /var/www/xxxx/app/vendor/doctrine/cache/lib/Doctrine/Common/Cache/PhpFileCache.php on line 112

... ...
```

## Technical Details

- Pagekit version: 1.0.10
- Webserver: chrome 56
- Database: sqlite
- PHP Version: 7.0.12

**Comment by MalteScharenberg** [comment]
Did this error persists or did it just occurred once after installation?
