### ISSUE TITLE
How to insert or activate Slider in Hero Section?

### ISSUE THREAD

**Issue by asharamseervi** [pagekit/pagekit#796]
Pagekit is awesome !!

But, due to some conerns, it still missing something. There are many concerns, but for now. How to implement Slideshow in Hero Section. I'm looking to make attractive portfolio, slideshow will help me at frontpage instead of Hero Single Image. I'm using default theme(theme-one) of Pagekit and willing to set slideshow in full 

I had tried [UIKit examples](https://getuikit.com/v2/docs/slideshow.html), but none of work, why? Inshort, How to implement " Full viewport height slideshow". Please help.

**Comment by MalteScharenberg** [comment]
Please use Gitter or the Pagekit forum for support requests.
