### ISSUE TITLE
MySQL encoding problems

### ISSUE THREAD

**Issue by HostSpectr** [pagekit/pagekit#80]
Server configuration:
PHP 5.4.23
MySQL-server 5.5.30
MySQL-client 5.6.15

When using the Cyrillic text is written in a corrupted database encoding. 
And, of course, can be seen on the site of the problem. 
Example: http://s17.postimg.org/jn5tn9hbj/image.jpg
Probably Pagekit not set the correct encoding for transactions. 
While other engines that run on the server with UTF-8 and Cyrillic, do not experience problems.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. The code base completely changed, so I close this issue. Please open a new issue if it still exists.
