### ISSUE TITLE
Extensions and Themes don't show up in Admin Panel

### ISSUE THREAD

**Issue by wesleysch** [pagekit/pagekit#802]
## Problem

We have a local PageKit installation, with the Blog extension, that works just fine. However, when we host in on a cloud server (Bluemix in this case), both the Extensions section as well as the Themes section in the admin settings panel remains empty. The repository we use locally is exactly the same as the one being used on the cloud. Although the sections remain empty, the Blog admin panel is still accessible. Furthermore, when installing a new extension through the Marketplace, it will show up.

What can be the cause for this?

## Technical Details

- Pagekit version: 1.0.11
- Webserver: Apache
- Database: MySQL
- PHP Version:7.0.5

**Comment by MalteScharenberg** [comment]
The packages in the extension overview section are searched in the filesystem by a glob (https://github.com/pagekit/pagekit/blob/develop/app/installer/src/Package/PackageFactory.php#L176). Maybe you missed to upload files or your filesystem behaves differently?
