### ISSUE TITLE
Several sections on one page

### ISSUE THREAD

**Issue by foxonfleek** [pagekit/pagekit#803]
## Problem

When will a grid builder - like visual composer - be implemented in the backend of pagekit to create pages? Or is there a workaround? I can't seem to figure out to do that efficiently. Maybe this is a beginner question but I really love the backend of this cms and it would be so great if you could build pages easily like a pagebuilder.

Best regards.

## Technical Details

- Pagekit version: 1.0.11
- Webserver: not relevant
- Database: not relevant
- PHP Version: not relevant

**Comment by SPQRInc** [comment]
As far as I know YooTheme is going to implement YooTheme Pro, which matches your needs:-)
