### ISSUE TITLE
Custom theme not showing

### ISSUE THREAD

**Issue by mlemmers** [pagekit/pagekit#808]
I'm following the documention(https://pagekit.com/docs/tutorials/theme), which is insanely simple, but for no apparent reason my theme does not show up. 

Is there n standard procedure for bugfixing this? There are literally two files (composer.json and index.php) that need custom content.

Composer.json

`{
    "name": "custom/marjolein",
    "type": "custom-theme",
    "version": "1.0.0",
    "title": "Marjolein",
    "description": "A blueprint to develop your own themes.",
    "license": "MIT",
    "authors": [
        {
            "name": "Mathijslemmers",
            "email": "info@mathijslemmers.com",
            "homepage": "http://mathijslemmers.com"
        }
    ],
    "extra": {
        "image": "image.jpg"
    }
}`

Index.php

`<?php

/**
 * Configuration
 */
return [

    /**
     * Unique name that identifies your theme.
     */
    'name' => 'marjolein',

    /**
     * Change default layout to use a Twig template.
     *'layout' => 'views:template.twig',*/

    /**
     * Define menu positions.
     * Will be listed in the backend so that users
     * can assign menus to these positions.
     */
    'menus' => [

        'main' => 'Main',

    ],

    /**
     * Define widget positions.
     * will be listed in the backend so that users
     * can publish widgets in these positions.
     */
    'positions' => [

        'sidebar' => 'Sidebar',

    ],

    /**
     * Define theme configuration.
     * This is the theme's default configuration. During run-time, they will be merged with
     * settings the user has set in the backend. The default configuration can therefore
     * be overwritten.
     */
    'config' => []

];`

Does anyone know what I could be missing or could someone tell me the usual bugfix procedure for this?

Thank you so much in advance.

**Comment by mlemmers** [comment]
Codeblocks not working. Everything is failing me today 😅

**Comment by tobbexiv** [comment]
In composer.json you must set `"type": "pagekit-theme"` instead of `"type": "custom-theme"`. Otherwise pagekit does not find the theme.

Also you should consider that the name is `vendor/theme-name`, so in your case the vedor would be custom instead of your name.

Example data from one theme by me (with additional comments):

composer.json:
```
{
    "name": "tobbe/theme-tobbe", // name of the theme
    "module": "tobbe/theme-tobbe", // I want to use the prefixed name in pagekit, else the extension would be in the "global" namespace
    "type": "pagekit-theme", // do not change: pagekit theme
    "version": "0.5.0",
    "title": "Tobbes Theme",
    "description": "Theme for Tobbe.",
    "license": "MIT",
    "authors": [
        {
            "name": "Tobbe",
            "email": "contact@tobbexiv.de",
            "homepage": "https://github.com/tobbexiv"
        }
    ],
    "extra": {
        "image": "image.jpg" // we want to have an image in pagekits theme overview
    }
}
```

index.php:
```
return [
    'name' => 'tobbe/theme-bcs', // prefixed name for the theme
    'type' => 'theme',
    /**
     * Change default layout to use a Twig template.
     */
    'layout' => 'views:template.twig',
    /**
     * Define menu positions.
     * Will be listed in the backend so that users
     * can assign menus to these positions.
     */
    'menus' => [],
    /**
     * Define widget positions.
     * will be listed in the backend so that users
     * can publish widgets in these positions.
     */
    'positions' => [],
    /**
     * Node defaults.
     */
    'node' => [],
    /**
     * Widget defaults.
     */
    'widget' => [],
    /**
     * Define theme configuration.
     * This is the theme's default configuration. During run-time, they will be merged with
     * settings the user has set in the backend. The default configuration can therefore
     * be overwritten.
     */
    'config' => [],
    'events' => []
];
```

---

Multiline code needs ` ``` ` to be displayed as code. One ` is only for inline code

**Comment by mlemmers** [comment]
@tobbexiv You lifesaver you! I feel incredibly stupid for changing the type name, I was used to doing that in an older CMS similar to Pagekit.

Thanks a bunch and have a great remainder of the day!
