### ISSUE TITLE
Login widget - Your form markup here

### ISSUE THREAD

**Issue by poltys** [pagekit/pagekit#809]
## Problem

I don't understand how to add a login widget to pagekit. When I try to add it from the widget panel I got this: `Your form markup here` 

![screenshot from 2017-03-08 22-57-02](https://cloud.githubusercontent.com/assets/12951939/23725886/927c4f58-0452-11e7-91da-548026e2a4cb.png)

## Technical Details

- Pagekit version: 1.0.11
- Webserver: Apache
- Database: Mysql 5.7.16-10
- PHP Version: 5.6.26

**Comment by MalteScharenberg** [comment]
This looks like a bug. Did you installed the release package?

**Comment by poltys** [comment]
I was not able to remember - I have downloaded the last version from the website and... it works perfectly fine now. 

Thanks!
