### ISSUE TITLE
Can't login, no reset email being sent

### ISSUE THREAD

**Issue by amrikahill** [pagekit/pagekit#811]
Hi there, 

I got logged out after a few hours and when trying to log back in, the password did not work at all. 

When I requested the password be sent/reset, I never got an email. I've done this several times now. I can't get access to my pagekit admin page now. 

Any help would be appreciated!

Thanks!

**Comment by crlang** [comment]
You need to pre-set the mailbox to send the configuration, otherwise the registration or forget the password operation can not send mail. Of course, it is prompted to send a success.

**Comment by MalteScharenberg** [comment]
Please use Gitter or the Pagekit Forum for support requests.
