### ISSUE TITLE
CLI-Command 

### ISSUE THREAD

**Issue by LrMiLoef** [pagekit/pagekit#812]
## Suggeston

It would be great when you would integrate an commad for generating an extension skeleton. 
In Symfony exists such an command ( generate:bundle).

**Comment by tobbexiv** [comment]
Seems to me like a request for #468 or drunken-kungfu/pagekit-template-generator which requires #703. So either the author did not respond (and the pagekit team did also not step in as announced) or the pagekit team did not respond and so the author has no chance to solve the issues ...
