### ISSUE TITLE
page are unrendered

### ISSUE THREAD

**Issue by chuoke** [pagekit/pagekit#817]
I got unrendered page after I did follow the doc.  
like this:  
![013 - pagekit](https://cloud.githubusercontent.com/assets/17611457/25123591/82580c74-245b-11e7-9c3a-2850b5677ddc.png)  
---------------------
What I miss ?

**Comment by SPQRInc** [comment]
Hm, looks like there's a problem with Vue.js. Which browser do you use? Is there any error in the JS-console?

**Comment by emptynick** [comment]
I guess you missed using `npm install`
