### ISSUE TITLE
Validator fails on cancelling empty form in modal

### ISSUE THREAD

**Issue by SPQRInc** [pagekit/pagekit#818]
## Problem

Die vue-validator fails, if a form in a modal is left empty and the modal is going to be closed.

On second click it works as expected.

Demo: https://spqr.wtf/drops/Screen-Recording-2017-04-26-10-05-28.mp4 

If you do not want to watch the screen recording:

<img width="1050" alt="bildschirmfoto 2017-04-26 um 10 09 00" src="https://cloud.githubusercontent.com/assets/23051150/25424392/8323d44a-2a68-11e7-9411-0652e6dc257e.png">
<img width="1053" alt="bildschirmfoto 2017-04-26 um 10 09 10" src="https://cloud.githubusercontent.com/assets/23051150/25424391/83239da4-2a68-11e7-9f15-858b70ebc3c4.png">
<img width="1042" alt="bildschirmfoto 2017-04-26 um 10 09 17" src="https://cloud.githubusercontent.com/assets/23051150/25424393/8323fbd2-2a68-11e7-810c-3aea435ceb24.png">

## Technical Details

- Pagekit version: 1.0.11
- Webserver: Apache 2.4
- Database: SQLite 
- PHP Version: 7.1

**Comment by MalteScharenberg** [comment]
Unfortunately I can not recreate this issue. Is it still not working for you? Which browser are you using?

**Comment by SPQRInc** [comment]
It's Safari Version 10.1.1 (12603.2.4) .

**Comment by MalteScharenberg** [comment]
Fixed in https://github.com/pagekit/vue-form/commit/ef7b8d8fb9623f632cf337f1596695d441ce7935.
