### ISSUE TITLE
Backend: Menu structure with wrong match

### ISSUE THREAD

**Issue by SPQRInc** [pagekit/pagekit#819]
## Problem

I created a extension called "sitemap-generator". Now I wondered, why the menu of the pagekit's site is shown, if I click the extension's menu entry in the admin-backend.

<img width="1238" alt="bildschirmfoto 2017-04-26 um 15 14 44" src="https://cloud.githubusercontent.com/assets/23051150/25436274/1cf83456-2a93-11e7-843c-811c358e7564.png">

This seems to be a problem on registering my menu:

```
'sitemap'           => [
			'label'  => 'Sitemap',
			'url'    => '@sitemap',
			'active' => '@sitemap(/*)?',
			'icon'   => 'sitemap:icon.svg'
		],
```

because pagekit/app/system/modules/site/index.php matches this way:

```
        'site' => [
            'label' => 'Site',
            'icon' => 'system/site:assets/images/icon-site.svg',
            'url' => '@site/page',
            'access' => 'site: manage site || system: manage widgets || system: manage storage || system: access settings',
            'active' => '@site*',
            'priority' => 105
        ],
```

 
Your problem description here...

## Technical Details

- Pagekit version: 1.0.11
- Webserver: Apache 2.4
- Database: SQLite
- PHP Version: 7.1.2

**Comment by MalteScharenberg** [comment]
Thanks for contributing!
