### ISSUE TITLE
Error running gulp

### ISSUE THREAD

**Issue by seltzlab** [pagekit/pagekit#821]
## Gulp compilation error

Running npm install produce an error with the gulp compilation:

`./node_modules/gulp/bin/gulp.js 
[09:53:18] Using gulpfile ~/Workspace/IIT/pagekit/gulpfile.js
[09:53:18] Starting 'compile'...
Error in plugin 'gulp-less'
Message:
    '../../../../../assets/uikit/less/uikit.less' wasn't found. Tried - /home/antonio/Workspace/IIT/pagekit/app/assets/uikit/less/uikit.less,../../../../../assets/uikit/less/uikit.less in file /home/antonio/Workspace/IIT/pagekit/app/system/modules/theme/less/uikit/uikit.less line no. 4
Details:
    type: File
    filename: /home/antonio/Workspace/IIT/pagekit/app/system/modules/theme/less/uikit/uikit.less
    index: 86
    line: 4
    callLine: NaN
    callExtract: undefined
    column: 0
    extract: ,@import "../../../../../assets/uikit/less/uikit.less";,
    lineNumber: 4
    fileName: /home/antonio/Workspace/IIT/pagekit/app/system/modules/theme/less/uikit/uikit.less
Error in plugin 'gulp-less'
Message:
    '../../../../../assets/uikit/less/uikit.less' wasn't found. Tried - /home/antonio/Workspace/IIT/pagekit/app/assets/uikit/less/uikit.less,../../../../../assets/uikit/less/uikit.less in file /home/antonio/Workspace/IIT/pagekit/app/system/modules/theme/less/uikit/uikit.less line no. 4
Details:
    type: File
    filename: /home/antonio/Workspace/IIT/pagekit/app/system/modules/theme/less/uikit/uikit.less
    index: 86
    line: 4
    callLine: NaN
    callExtract: undefined
    column: 0
    extract: ,@import "../../../../../assets/uikit/less/uikit.less";,
    lineNumber: 4
    fileName: /home/antonio/Workspace/IIT/pagekit/app/system/modules/theme/less/uikit/uikit.less
[09:53:19] Finished 'compile' after 192 ms
[09:53:19] Starting 'default'...
[09:53:19] Finished 'default' after 6.73 μs
`

I tried to remove the app/assets and reinstall with bower but it didn't solved.

## Technical Details

- Pagekit version: 1.0.11
- NPM version: 3.10.8
- Gulp version: 3.9.1
- Bower version: 1.7.9

**Comment by R4c00n** [comment]
Same issue here, tried with a fresh install with source from `develop` branch.

**Comment by hjlld** [comment]
The actual path of "less" files should be "assets/uikit/src/less/uikit.less" but not "assets/uikit/less/uikit.less". 

Then I copied the "less" folder to the "uikit" folder, but gulp still threw an error for "'uikit/less/components/form-advanced.less' not found".

Then I checked the default branch(develop) of UIKit repo on Github, there was no such a file as 'form-advanced.less'! But I do find this file in the v2 branch.

I'm not an UIKit user, so I don't know it's deprecated or what happend, but I think the UIKit used by PageKit doesn't correspond to their origin repo on Github.

**Comment by seltzlab** [comment]
So probably the UIKit declared in packages.json is not the same used by Pagekit?
Possible to solve? I'm quite blocked with the development

**Comment by florianletsch** [comment]
Can you try to edit `bower.json` to link to the bower repository directly? There might be something wrong with the setup since UIkit has changed to version 3...

So, in `bower.json`, change this: `"uikit": "^2.27.2"` to look as follows:

    "uikit": "git://github.com/uikit/bower-uikit.git"

Then, re-run `bower install` and `gulp`

**Comment by seltzlab** [comment]
That did the trick, thanks @florianletsch
