### ISSUE TITLE
FORMMAKER EXPORT CSV - ECHEC 

### ISSUE THREAD

**Issue by poltys** [pagekit/pagekit#822]
## Problem

EXPORT CSV is not working properly - I am unable to download formmaker results. After clicking on EXPORT nothing happen.

## Technical Details

- Pagekit version: 1.0.11
- Webserver: Apache
- Database: mysql 5.7.12-5
- PHP Version: 5.6.26

**Comment by SPQRInc** [comment]
Should be a problem with form maker? 

I think you should create an issue there: https://github.com/Bixie/pagekit-formmaker/issues .

**Comment by poltys** [comment]
Indeed.

https://github.com/Bixie/pagekit-formmaker/issues/47
