### ISSUE TITLE
Adding additional HTML to content leads to wrong Markdown-parsing

### ISSUE THREAD

**Issue by SPQRInc** [pagekit/pagekit#823]
## Problem

As I described in the pagekit-forum (https://pagekit-forum.org/forum/thread/23-adding-html-to-a-view-makes-content-invalid/) I'm having trouble adding HTML to a view by using a plugin that does the following:

public function onContentPlugins( ContentEvent $event )
	{
		
		$content = $event->getContent();		
		$html = " <div id='survey'>test</div> ";
		$event->setContent($buttons . $content);
	}

The result is that the markdown-formatted structure is not displayed correctly as you can see here:

![bildschirmfoto 2017-05-09 um 09 46 29](https://cloud.githubusercontent.com/assets/23051150/25936355/aa8abd76-3627-11e7-829a-25fb6e13bfc3.png)
![bildschirmfoto 2017-05-09 um 09 47 20](https://cloud.githubusercontent.com/assets/23051150/25936356/aab02926-3627-11e7-883c-83dd2b08c947.png)
![bildschirmfoto 2017-05-09 um 09 47 27](https://cloud.githubusercontent.com/assets/23051150/25936357/aab4d9ee-3627-11e7-9081-c70ea10a1990.png)

## Technical Details

- Pagekit version: 1.0.11
- Webserver: Apache 2.4
- Database: SQLite
- PHP Version: 7.1.2

**Comment by tobbexiv** [comment]
This is related to how [ATX headers](http://daringfireball.net/projects/markdown/syntax#header) in Markdown are parsed: The # must be at the beginning of the line. As you write your content in the same line by just prepending it, the markdown is correctly not parsed. The same applies if you write something like
a # Heading 
directly in the editor (also here on GitHub). So I would conclude that this is no bug in the parser, but you must ensure that you have a linebreak after your content if you prepend it to the normal text.
