### ISSUE TITLE
No option to rearrange order in menu

### ISSUE THREAD

**Issue by jones4410** [pagekit/pagekit#832]
## Problem
There is no option to rearrange or sort the order of menu items.

## Technical Details

- Pagekit version: 1.0.11
- Webserver: Apache/2.4
- Database: 5.5.5-10.1.23-MariaDB
- PHP Version: 7.1.5

**Comment by MalteScharenberg** [comment]
You should be able to sort them with drag and drop.

**Comment by jones4410** [comment]
Somehow the drag'n'drop framework pagekit uses didn't work in my Firefox...
Now it's working... Thanks
