### ISSUE TITLE
No link or button to upload avatar.

### ISSUE THREAD

**Issue by sooonism** [pagekit/pagekit#840]
## Problem

There is no button or link for me to upload avatar image. I tried extension UserProfile and can create an image upload but still it is not showing in my user profile.

## Technical Details

- Pagekit version: 1.0.11
- Webserver: Apache/2.2.29 (Unix)
- Database: 5.5.42
- PHP Version: 5.6.10

**Comment by MalteScharenberg** [comment]
Avatar images are fetched from https://gravatar.com/.
