### ISSUE TITLE
Large debug file.

### ISSUE THREAD

**Issue by xsurox** [pagekit/pagekit#841]
Large debug file problem ..

I have found large debug file in TMP\Temp\  directory.
Our hosting is 1GB, 
pagekit site max 50MB.
Debug file 850 MB..

It's safe to delete?

**Comment by tobbexiv** [comment]
As far as I know it is safe to delete it. It should also be deleted if you clear the cache under `System -> Settings -> Cache -> Clear Cache`.

**Comment by MalteScharenberg** [comment]
Yes it is safe to delete. But debug modus should be disabled anyway on live sites because it has serious security implications!
