### ISSUE TITLE
Filesize displaying incorrect for some languages

### ISSUE THREAD

**Issue by Tschlienger** [pagekit/pagekit#844]
## Problem

With language German (Switzerland) selected, Pagekit only shows "&d" on storage tab instead of filesize (other languages like German (Germany) or English work).

![image](https://user-images.githubusercontent.com/11772968/27824512-0be91b44-60ad-11e7-9336-0e7aa6fb0e6f.png)

## Technical Details

- Pagekit version: 1.0.12
- Webserver: Apache 2.4
- Database: MySQL 5.7
- PHP Version: 7.1

**Comment by tobbexiv** [comment]
'%d  KB' => '&d KB'

But I can not change it as I am no member of the swiss transifex team. However it might be good to also update the source files for the translations if this gets fixed as there are also Strings missing.
