### ISSUE TITLE
Pagekit installation page is broken

### ISSUE THREAD

**Issue by mhsabbagh** [pagekit/pagekit#845]
## Problem

Pagekit installation page is broken. It´s displayed in the following appearance: 
![screenshot_2017-07-05_14-13-05](https://user-images.githubusercontent.com/1293003/27862560-7c7fad3c-618e-11e7-9b02-23f5ccd8e338.png)

I checked all the requirements and installed them using `composer install`. I couldn´t find anything in the log files.

## Technical Details

- Pagekit version: 1.0.12
- Webserver: nginx
- Database: MySQL
- PHP Version: 7.0

**Comment by SPQRInc** [comment]
Hello,

how did you install Pagekit? Did you download the package or did you clone it from GitHub?

Is JS enabled in your browser?

**Comment by mhsabbagh** [comment]
Hi.

I cloned it from GitHub.

Of course it's enabled.

**Comment by SPQRInc** [comment]
Did you follow https://pagekit.com/docs/developer/source#check-out-and-install ?

You wrote you did `composer install`, but what about `npm install`?

And: There are a lot of users disabling JS in their browsers. So I just have to ask that to solve your problem.

**Comment by florianletsch** [comment]
Looks like JS and CSS are missing. This could be caused by `npm install` not being run (or failing with an error?)

Please have a look at the browser console.  It will show if any CSS and JS files cannot be loaded.

**Comment by mhsabbagh** [comment]
Oh, it's my mistake then. It seems that the installation was aborting directly after `npm install` because of:

`├── UNMET PEER DEPENDENCY css-loader@*
`
And when I tried to install it, it seems it's not compatible with my OS (Ubuntu 16.04):

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN vue-loader@8.7.0 requires a peer of css-loader@* but none was installed.

```

Any other way to get those modules installed?

**Comment by mhsabbagh** [comment]
This was the complete log for `npm install`:

`npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN lifecycle pagekit@~install: cannot run in wd %s %s (wd=%s) pagekit@ bower install && webpack && gulp /var/www/html
pagekit@ /var/www/html
├─┬ babel-core@6.25.0 
│ ├─┬ babel-code-frame@6.22.0 
│ │ ├── esutils@2.0.2 
│ │ └── js-tokens@3.0.2 
│ ├─┬ babel-generator@6.25.0 
│ │ ├─┬ detect-indent@4.0.0 
│ │ │ └─┬ repeating@2.0.1 
│ │ │   └─┬ is-finite@1.0.2 
│ │ │     └── number-is-nan@1.0.1 
│ │ ├── jsesc@1.3.0 
│ │ ├── lodash@4.17.4 
│ │ └── trim-right@1.0.1 
│ ├── babel-helpers@6.24.1 
│ ├── babel-messages@6.23.0 
│ ├─┬ babel-register@6.24.1 
│ │ ├─┬ home-or-tmp@2.0.0 
│ │ │ └── os-tmpdir@1.0.2 
│ │ ├── lodash@4.17.4 
│ │ └── source-map-support@0.4.15 
│ ├─┬ babel-template@6.25.0 
│ │ └── lodash@4.17.4 
│ ├─┬ babel-traverse@6.25.0 
│ │ ├── globals@9.18.0 
│ │ ├─┬ invariant@2.2.2 
│ │ │ └── loose-envify@1.3.1 
│ │ └── lodash@4.17.4 
│ ├─┬ babel-types@6.25.0 
│ │ ├── lodash@4.17.4 
│ │ └── to-fast-properties@1.0.3 
│ ├── babylon@6.17.4 
│ ├── convert-source-map@1.5.0 
│ ├─┬ debug@2.6.8 
│ │ └── ms@2.0.0 
│ ├── json5@0.5.1 
│ ├── lodash@4.17.4 
│ ├─┬ minimatch@3.0.4 
│ │ └─┬ brace-expansion@1.1.8 
│ │   ├── balanced-match@1.0.0 
│ │   └── concat-map@0.0.1 
│ ├── path-is-absolute@1.0.1 
│ ├── private@0.1.7 
│ ├── slash@1.0.0 
│ └── source-map@0.5.6 
├─┬ babel-loader@6.4.1 
│ ├─┬ find-cache-dir@0.1.1 
│ │ ├── commondir@1.0.1 
│ │ └─┬ pkg-dir@1.0.0 
│ │   └─┬ find-up@1.1.2 
│ │     ├── path-exists@2.1.0 
│ │     └─┬ pinkie-promise@2.0.1 
│ │       └── pinkie@2.0.4 
│ ├─┬ loader-utils@0.2.17 
│ │ ├── big.js@3.1.3 
│ │ └── emojis-list@2.1.0 
│ ├─┬ mkdirp@0.5.1 
│ │ └── minimist@0.0.8 
│ └── object-assign@4.1.1 
├── babel-plugin-transform-runtime@6.23.0 
├─┬ babel-preset-es2015@6.24.1 
│ ├── babel-plugin-check-es2015-constants@6.22.0 
│ ├── babel-plugin-transform-es2015-arrow-functions@6.22.0 
│ ├── babel-plugin-transform-es2015-block-scoped-functions@6.22.0 
│ ├─┬ babel-plugin-transform-es2015-block-scoping@6.24.1 
│ │ └── lodash@4.17.4 
│ ├─┬ babel-plugin-transform-es2015-classes@6.24.1 
│ │ ├─┬ babel-helper-define-map@6.24.1 
│ │ │ └── lodash@4.17.4 
│ │ ├── babel-helper-function-name@6.24.1 
│ │ ├── babel-helper-optimise-call-expression@6.24.1 
│ │ └── babel-helper-replace-supers@6.24.1 
│ ├── babel-plugin-transform-es2015-computed-properties@6.24.1 
│ ├── babel-plugin-transform-es2015-destructuring@6.23.0 
│ ├── babel-plugin-transform-es2015-duplicate-keys@6.24.1 
│ ├── babel-plugin-transform-es2015-for-of@6.23.0 
│ ├── babel-plugin-transform-es2015-function-name@6.24.1 
│ ├── babel-plugin-transform-es2015-literals@6.22.0 
│ ├── babel-plugin-transform-es2015-modules-amd@6.24.1 
│ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.24.1 
│ │ └── babel-plugin-transform-strict-mode@6.24.1 
│ ├─┬ babel-plugin-transform-es2015-modules-systemjs@6.24.1 
│ │ └── babel-helper-hoist-variables@6.24.1 
│ ├── babel-plugin-transform-es2015-modules-umd@6.24.1 
│ ├── babel-plugin-transform-es2015-object-super@6.24.1 
│ ├─┬ babel-plugin-transform-es2015-parameters@6.24.1 
│ │ ├── babel-helper-call-delegate@6.24.1 
│ │ └── babel-helper-get-function-arity@6.24.1 
│ ├── babel-plugin-transform-es2015-shorthand-properties@6.24.1 
│ ├── babel-plugin-transform-es2015-spread@6.22.0 
│ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.24.1 
│ │ └─┬ babel-helper-regex@6.24.1 
│ │   └── lodash@4.17.4 
│ ├── babel-plugin-transform-es2015-template-literals@6.22.0 
│ ├── babel-plugin-transform-es2015-typeof-symbol@6.23.0 
│ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.24.1 
│ │ └─┬ regexpu-core@2.0.0 
│ │   ├── regenerate@1.3.2 
│ │   ├── regjsgen@0.2.0 
│ │   └─┬ regjsparser@0.1.5 
│ │     └── jsesc@0.5.0 
│ └─┬ babel-plugin-transform-regenerator@6.24.1 
│   └── regenerator-transform@0.9.11 
├─┬ babel-runtime@6.23.0 
│ ├── core-js@2.4.1 
│ └── regenerator-runtime@0.10.5 
├── bower@1.8.0 
├── cldr-core@28.0.0 
├── cldr-localenames-modern@28.0.0 
├── UNMET PEER DEPENDENCY css-loader@*
├─┬ glob@5.0.15 
│ ├─┬ inflight@1.0.6 
│ │ └── wrappy@1.0.2 
│ ├── inherits@2.0.3 
│ └── once@1.4.0 
├── graceful-fs@4.1.11 
├─┬ gulp@3.9.1 
│ ├── archy@1.0.0 
│ ├─┬ chalk@1.1.3 
│ │ ├── ansi-styles@2.2.1 
│ │ ├── escape-string-regexp@1.0.5 
│ │ ├─┬ has-ansi@2.0.0 
│ │ │ └── ansi-regex@2.1.1 
│ │ ├── strip-ansi@3.0.1 
│ │ └── supports-color@2.0.0 
│ ├── deprecated@0.0.1 
│ ├── interpret@1.0.3 
│ ├─┬ liftoff@2.3.0 
│ │ ├── extend@3.0.1 
│ │ ├─┬ findup-sync@0.4.3 
│ │ │ ├─┬ detect-file@0.1.0 
│ │ │ │ └── fs-exists-sync@0.1.0 
│ │ │ ├─┬ is-glob@2.0.1 
│ │ │ │ └── is-extglob@1.0.0 
│ │ │ ├─┬ micromatch@2.3.11 
│ │ │ │ ├─┬ arr-diff@2.0.0 
│ │ │ │ │ └── arr-flatten@1.0.3 
│ │ │ │ ├── array-unique@0.2.1 
│ │ │ │ ├─┬ braces@1.8.5 
│ │ │ │ │ ├─┬ expand-range@1.8.2 
│ │ │ │ │ │ └─┬ fill-range@2.2.3 
│ │ │ │ │ │   ├── is-number@2.1.0 
│ │ │ │ │ │   └─┬ randomatic@1.1.7 
│ │ │ │ │ │     ├─┬ is-number@3.0.0 
│ │ │ │ │ │     │ └── kind-of@3.2.2 
│ │ │ │ │ │     └── kind-of@4.0.0 
│ │ │ │ │ ├── preserve@0.2.0 
│ │ │ │ │ └── repeat-element@1.1.2 
│ │ │ │ ├─┬ expand-brackets@0.1.5 
│ │ │ │ │ └── is-posix-bracket@0.1.1 
│ │ │ │ ├── extglob@0.3.2 
│ │ │ │ ├── filename-regex@2.0.1 
│ │ │ │ ├─┬ kind-of@3.2.2 
│ │ │ │ │ └── is-buffer@1.1.5 
│ │ │ │ ├─┬ normalize-path@2.1.1 
│ │ │ │ │ └── remove-trailing-separator@1.0.2 
│ │ │ │ ├─┬ object.omit@2.0.1 
│ │ │ │ │ ├── for-own@0.1.5 
│ │ │ │ │ └── is-extendable@0.1.1 
│ │ │ │ ├─┬ parse-glob@3.0.4 
│ │ │ │ │ ├── glob-base@0.3.0 
│ │ │ │ │ └── is-dotfile@1.0.3 
│ │ │ │ └─┬ regex-cache@0.4.3 
│ │ │ │   ├── is-equal-shallow@0.1.3 
│ │ │ │   └── is-primitive@2.0.0 
│ │ │ └─┬ resolve-dir@0.1.1 
│ │ │   ├── expand-tilde@1.2.2 
│ │ │   └─┬ global-modules@0.2.3 
│ │ │     ├─┬ global-prefix@0.1.5 
│ │ │     │ ├── ini@1.3.4 
│ │ │     │ └─┬ which@1.2.14 
│ │ │     │   └── isexe@2.0.0 
│ │ │     └── is-windows@0.2.0 
│ │ ├─┬ fined@1.1.0 
│ │ │ ├─┬ expand-tilde@2.0.2 
│ │ │ │ └─┬ homedir-polyfill@1.0.1 
│ │ │ │   └── parse-passwd@1.0.0 
│ │ │ ├─┬ is-plain-object@2.0.3 
│ │ │ │ └── isobject@3.0.1 
│ │ │ ├─┬ object.defaults@1.1.0 
│ │ │ │ ├── array-each@1.0.1 
│ │ │ │ ├── array-slice@1.0.0 
│ │ │ │ ├─┬ for-own@1.0.0 
│ │ │ │ │ └── for-in@1.0.2 
│ │ │ │ └── isobject@3.0.1 
│ │ │ ├─┬ object.pick@1.2.0 
│ │ │ │ └─┬ isobject@2.1.0 
│ │ │ │   └── isarray@1.0.0 
│ │ │ └─┬ parse-filepath@1.0.1 
│ │ │   ├─┬ is-absolute@0.2.6 
│ │ │   │ └─┬ is-relative@0.2.1 
│ │ │   │   └─┬ is-unc-path@0.1.2 
│ │ │   │     └── unc-path-regex@0.1.2 
│ │ │   ├── map-cache@0.2.2 
│ │ │   └─┬ path-root@0.1.1 
│ │ │     └── path-root-regex@0.1.2 
│ │ ├── flagged-respawn@0.3.2 
│ │ ├── lodash.isplainobject@4.0.6 
│ │ ├── lodash.isstring@4.0.1 
│ │ ├── lodash.mapvalues@4.6.0 
│ │ ├── rechoir@0.6.2 
│ │ └─┬ resolve@1.3.3 
│ │   └── path-parse@1.0.5 
│ ├── minimist@1.2.0 
│ ├─┬ orchestrator@0.3.8 
│ │ ├─┬ end-of-stream@0.1.5 
│ │ │ └── once@1.3.3 
│ │ ├── sequencify@0.0.7 
│ │ └── stream-consume@0.1.0 
│ ├── pretty-hrtime@1.0.3 
│ ├── semver@4.3.6 
│ ├─┬ tildify@1.2.0 
│ │ └── os-homedir@1.0.2 
│ ├─┬ v8flags@2.1.1 
│ │ └── user-home@1.1.1 
│ └─┬ vinyl-fs@0.3.14 
│   ├── defaults@1.0.3 
│   ├─┬ glob-stream@3.1.18 
│   │ ├── glob@4.5.3 
│   │ ├─┬ glob2base@0.0.12 
│   │ │ └── find-index@0.1.1 
│   │ ├── minimatch@2.0.10 
│   │ ├── ordered-read-streams@0.1.0 
│   │ ├─┬ through2@0.6.5 
│   │ │ └── readable-stream@1.0.34 
│   │ └── unique-stream@1.0.0 
│   ├─┬ glob-watcher@0.0.6 
│   │ └─┬ gaze@0.5.2 
│   │   └─┬ globule@0.1.0 
│   │     ├─┬ glob@3.1.21 
│   │     │ ├── graceful-fs@1.2.3 
│   │     │ └── inherits@1.0.2 
│   │     ├── lodash@1.0.2 
│   │     └─┬ minimatch@0.2.14 
│   │       └── sigmund@1.0.1 
│   ├─┬ graceful-fs@3.0.11 
│   │ └── natives@1.1.0 
│   ├─┬ strip-bom@1.0.0 
│   │ ├── first-chunk-stream@1.0.0 
│   │ └── is-utf8@0.2.1 
│   ├─┬ through2@0.6.5 
│   │ └── readable-stream@1.0.34 
│   └─┬ vinyl@0.4.6 
│     └── clone@0.2.0 
├─┬ gulp-eslint@0.7.0 
│ ├─┬ bufferstreams@1.0.1 
│ │ └─┬ readable-stream@1.1.14 
│ │   ├── core-util-is@1.0.2 
│ │   └── isarray@0.0.1 
│ ├─┬ eslint@0.17.1 
│ │ ├─┬ concat-stream@1.6.0 
│ │ │ ├─┬ readable-stream@2.3.3 
│ │ │ │ ├── isarray@1.0.0 
│ │ │ │ └── string_decoder@1.0.3 
│ │ │ └── typedarray@0.0.6 
│ │ ├─┬ doctrine@0.6.4 
│ │ │ └── esutils@1.1.6 
│ │ ├─┬ escope@2.0.6 
│ │ │ ├─┬ es6-map@0.1.5 
│ │ │ │ ├── d@1.0.0 
│ │ │ │ ├── es5-ext@0.10.23 
│ │ │ │ ├── es6-iterator@2.0.1 
│ │ │ │ ├── es6-set@0.1.5 
│ │ │ │ ├── es6-symbol@3.1.1 
│ │ │ │ └── event-emitter@0.3.5 
│ │ │ ├─┬ es6-weak-map@0.1.4 
│ │ │ │ ├── d@0.1.1 
│ │ │ │ ├── es6-iterator@0.1.3 
│ │ │ │ └── es6-symbol@2.0.1 
│ │ │ ├── esrecurse@1.2.0 
│ │ │ └── util-extend@1.0.3 
│ │ ├── espree@1.12.3 
│ │ ├── estraverse@2.0.0 
│ │ ├── estraverse-fb@1.3.2 
│ │ ├── globals@6.4.1 
│ │ ├─┬ js-yaml@3.8.4 
│ │ │ ├─┬ argparse@1.0.9 
│ │ │ │ └── sprintf-js@1.0.3 
│ │ │ └── esprima@3.1.3 
│ │ ├── minimatch@2.0.10 
│ │ ├── object-assign@2.1.1 
│ │ ├─┬ optionator@0.5.0 
│ │ │ ├── deep-is@0.1.3 
│ │ │ ├── fast-levenshtein@1.0.7 
│ │ │ ├── levn@0.2.5 
│ │ │ ├── prelude-ls@1.1.2 
│ │ │ └── type-check@0.3.2 
│ │ ├── strip-json-comments@1.0.4 
│ │ ├── text-table@0.2.0 
│ │ └── xml-escape@1.0.0 
│ ├── object-assign@2.1.1 
│ ├── optional@0.1.3 
│ └─┬ through2@0.6.5 
│   ├── readable-stream@1.0.34 
│   └── xtend@4.0.1 
├─┬ gulp-header@1.8.8 
│ ├── concat-with-sourcemaps@1.0.4 
│ └─┬ through2@2.0.3 
│   └─┬ readable-stream@2.3.3 
│     ├── isarray@1.0.0 
│     ├── process-nextick-args@1.0.7 
│     ├── string_decoder@1.0.3 
│     └── util-deprecate@1.0.2 
├─┬ gulp-less@3.3.2 
│ ├─┬ accord@0.27.3 
│ │ ├─┬ glob@7.1.2 
│ │ │ └── fs.realpath@1.0.0 
│ │ ├── indx@0.2.3 
│ │ ├── lodash.clone@4.5.0 
│ │ ├── lodash.defaults@4.2.0 
│ │ ├── lodash.flatten@4.4.0 
│ │ ├── lodash.merge@4.6.0 
│ │ ├── lodash.partialright@4.2.1 
│ │ ├── lodash.pick@4.4.0 
│ │ ├── lodash.uniq@4.5.0 
│ │ ├── semver@5.3.0 
│ │ ├── uglify-js@2.8.29 
│ │ └── when@3.7.8 
│ └── vinyl-sourcemaps-apply@0.2.1 
├── gulp-plumber@1.1.0 
├── gulp-rename@1.2.2 
├─┬ gulp-util@3.0.8 
│ ├── array-differ@1.0.0 
│ ├── array-uniq@1.0.3 
│ ├── beeper@1.1.1 
│ ├── dateformat@2.0.0 
│ ├─┬ fancy-log@1.3.0 
│ │ └── time-stamp@1.1.0 
│ ├─┬ gulplog@1.0.0 
│ │ └── glogg@1.0.0 
│ ├─┬ has-gulplog@0.1.0 
│ │ └── sparkles@1.0.0 
│ ├── lodash._reescape@3.0.0 
│ ├── lodash._reevaluate@3.0.0 
│ ├── lodash._reinterpolate@3.0.0 
│ ├─┬ lodash.template@3.6.2 
│ │ ├── lodash._basecopy@3.0.1 
│ │ ├── lodash._basetostring@3.0.1 
│ │ ├── lodash._basevalues@3.0.0 
│ │ ├── lodash._isiterateecall@3.0.9 
│ │ ├─┬ lodash.escape@3.2.0 
│ │ │ └── lodash._root@3.0.1 
│ │ ├─┬ lodash.keys@3.1.2 
│ │ │ ├── lodash._getnative@3.9.1 
│ │ │ ├── lodash.isarguments@3.1.0 
│ │ │ └── lodash.isarray@3.0.4 
│ │ ├── lodash.restparam@3.6.1 
│ │ └── lodash.templatesettings@3.1.1 
│ ├── minimist@1.2.0 
│ ├─┬ multipipe@0.1.2 
│ │ └── duplexer2@0.0.2 
│ ├── object-assign@3.0.0 
│ ├── replace-ext@0.0.1 
│ └─┬ vinyl@0.5.3 
│   └── clone-stats@0.0.1 
├── json-loader@0.5.4 
├─┬ less@2.7.2 
│ ├─┬ errno@0.1.4 
│ │ └── prr@0.0.0 
│ ├── image-size@0.5.5 
│ ├── mime@1.3.6 
│ ├─┬ promise@7.3.1 
│ │ └── asap@2.0.5 
│ └─┬ request@2.81.0 
│   ├── aws-sign2@0.6.0 
│   ├── aws4@1.6.0 
│   ├── caseless@0.12.0 
│   ├─┬ combined-stream@1.0.5 
│   │ └── delayed-stream@1.0.0 
│   ├── forever-agent@0.6.1 
│   ├─┬ form-data@2.1.4 
│   │ └── asynckit@0.4.0 
│   ├─┬ har-validator@4.2.1 
│   │ ├─┬ ajv@4.11.8 
│   │ │ ├── co@4.6.0 
│   │ │ └─┬ json-stable-stringify@1.0.1 
│   │ │   └── jsonify@0.0.0 
│   │ └── har-schema@1.0.5 
│   ├─┬ hawk@3.1.3 
│   │ ├── boom@2.10.1 
│   │ ├── cryptiles@2.0.5 
│   │ ├── hoek@2.16.3 
│   │ └── sntp@1.0.9 
│   ├─┬ http-signature@1.1.1 
│   │ ├── assert-plus@0.2.0 
│   │ ├─┬ jsprim@1.4.0 
│   │ │ ├── assert-plus@1.0.0 
│   │ │ ├── extsprintf@1.0.2 
│   │ │ ├── json-schema@0.2.3 
│   │ │ └── verror@1.3.6 
│   │ └─┬ sshpk@1.13.1 
│   │   ├── asn1@0.2.3 
│   │   ├── assert-plus@1.0.0 
│   │   ├── bcrypt-pbkdf@1.0.1 
│   │   ├─┬ dashdash@1.14.1 
│   │   │ └── assert-plus@1.0.0 
│   │   ├── ecc-jsbn@0.1.1 
│   │   ├─┬ getpass@0.1.7 
│   │   │ └── assert-plus@1.0.0 
│   │   ├── jsbn@0.1.1 
│   │   └── tweetnacl@0.14.5 
│   ├── is-typedarray@1.0.0 
│   ├── isstream@0.1.2 
│   ├── json-stringify-safe@5.0.1 
│   ├─┬ mime-types@2.1.15 
│   │ └── mime-db@1.27.0 
│   ├── oauth-sign@0.8.2 
│   ├── performance-now@0.2.0 
│   ├── qs@6.4.0 
│   ├── safe-buffer@5.1.1 
│   ├── stringstream@0.0.5 
│   ├── tough-cookie@2.3.2 
│   ├── tunnel-agent@0.6.0 
│   └── uuid@3.1.0 
├── lodash@3.10.1 
├─┬ merge-stream@0.1.8 
│ └─┬ through2@0.6.5 
│   └── readable-stream@1.0.34 
├── vue-hot-reload-api@1.3.3 
├─┬ vue-html-loader@1.2.4 
│ ├─┬ es6-templates@0.2.3 
│ │ ├─┬ recast@0.11.23 
│ │ │ ├── ast-types@0.9.6 
│ │ │ └── esprima@3.1.3 
│ │ └── through@2.3.8 
│ ├── fastparse@1.1.1 
│ ├─┬ html-minifier@2.1.7 
│ │ ├─┬ change-case@3.0.1 
│ │ │ ├── camel-case@3.0.0 
│ │ │ ├── constant-case@2.0.0 
│ │ │ ├── dot-case@2.1.1 
│ │ │ ├── header-case@1.0.1 
│ │ │ ├── is-lower-case@1.1.3 
│ │ │ ├── is-upper-case@1.1.2 
│ │ │ ├── lower-case@1.1.4 
│ │ │ ├── lower-case-first@1.0.2 
│ │ │ ├── no-case@2.3.1 
│ │ │ ├── param-case@2.1.1 
│ │ │ ├── pascal-case@2.0.1 
│ │ │ ├── path-case@2.1.1 
│ │ │ ├── sentence-case@2.1.1 
│ │ │ ├── snake-case@2.1.0 
│ │ │ ├── swap-case@1.1.2 
│ │ │ ├── title-case@2.1.1 
│ │ │ ├── upper-case@1.1.3 
│ │ │ └── upper-case-first@1.1.2 
│ │ ├─┬ clean-css@3.4.27 
│ │ │ ├── commander@2.8.1 
│ │ │ └── source-map@0.4.4 
│ │ ├─┬ commander@2.9.0 
│ │ │ └── graceful-readlink@1.0.1 
│ │ ├── he@1.1.1 
│ │ ├─┬ ncname@1.0.0 
│ │ │ └── xml-char-classes@1.0.0 
│ │ ├── relateurl@0.2.7 
│ │ └─┬ uglify-js@2.6.4 
│ │   └── async@0.2.10 
│ └── loader-utils@1.1.0 
├─┬ vue-loader@8.7.0 
│ ├─┬ autoprefixer@6.7.7 
│ │ ├─┬ browserslist@1.7.7 
│ │ │ └── electron-to-chromium@1.3.15 
│ │ ├── caniuse-db@1.0.30000697 
│ │ ├── normalize-range@0.1.2 
│ │ ├── num2fraction@1.2.2 
│ │ └── postcss-value-parser@3.3.0 
│ ├─┬ consolidate@0.14.5 
│ │ └── bluebird@3.5.0 
│ ├── de-indent@1.0.2 
│ ├── hash-sum@1.0.2 
│ ├── lru-cache@2.7.3 
│ ├── parse5@2.2.3 
│ ├─┬ postcss@5.2.17 
│ │ ├── js-base64@2.1.9 
│ │ └── supports-color@3.2.3 
│ ├─┬ postcss-selector-parser@1.3.3 
│ │ ├── flatten@1.0.2 
│ │ ├── indexes-of@1.0.1 
│ │ └── uniq@1.0.1 
│ └── vue-template-validator@1.1.5 
├── vue-style-loader@1.0.0 
└─┬ webpack@1.15.0 
  ├── acorn@3.3.0 
  ├── async@1.5.2 
  ├── clone@1.0.2 
  ├─┬ enhanced-resolve@0.9.1 
  │ └── memory-fs@0.2.0 
  ├── interpret@0.6.6 
  ├─┬ memory-fs@0.3.0 
  │ └─┬ readable-stream@2.3.3 
  │   ├── isarray@1.0.0 
  │   └── string_decoder@1.0.3 
  ├─┬ node-libs-browser@0.7.0 
  │ ├── assert@1.4.1 
  │ ├─┬ browserify-zlib@0.1.4 
  │ │ └── pako@0.2.9 
  │ ├─┬ buffer@4.9.1 
  │ │ ├── base64-js@1.2.1 
  │ │ ├── ieee754@1.1.8 
  │ │ └── isarray@1.0.0 
  │ ├─┬ console-browserify@1.1.0 
  │ │ └── date-now@0.1.4 
  │ ├── constants-browserify@1.0.0 
  │ ├─┬ crypto-browserify@3.3.0 
  │ │ ├── browserify-aes@0.4.0 
  │ │ ├── pbkdf2-compat@2.0.1 
  │ │ ├── ripemd160@0.2.0 
  │ │ └── sha.js@2.2.6 
  │ ├── domain-browser@1.1.7 
  │ ├── events@1.1.1 
  │ ├── https-browserify@0.0.1 
  │ ├── os-browserify@0.2.1 
  │ ├── path-browserify@0.0.0 
  │ ├── process@0.11.10 
  │ ├── punycode@1.4.1 
  │ ├── querystring-es3@0.2.1 
  │ ├─┬ readable-stream@2.3.3 
  │ │ ├── isarray@1.0.0 
  │ │ └── string_decoder@1.0.3 
  │ ├─┬ stream-browserify@2.0.1 
  │ │ └─┬ readable-stream@2.3.3 
  │ │   ├── isarray@1.0.0 
  │ │   └── string_decoder@1.0.3 
  │ ├─┬ stream-http@2.7.2 
  │ │ ├── builtin-status-codes@3.0.0 
  │ │ ├─┬ readable-stream@2.3.3 
  │ │ │ ├── isarray@1.0.0 
  │ │ │ └── string_decoder@1.0.3 
  │ │ └── to-arraybuffer@1.0.1 
  │ ├── string_decoder@0.10.31 
  │ ├─┬ timers-browserify@2.0.2 
  │ │ └── setimmediate@1.0.5 
  │ ├── tty-browserify@0.0.0 
  │ ├─┬ url@0.11.0 
  │ │ ├── punycode@1.3.2 
  │ │ └── querystring@0.2.0 
  │ ├─┬ util@0.10.3 
  │ │ └── inherits@2.0.1 
  │ └─┬ vm-browserify@0.0.4 
  │   └── indexof@0.0.1 
  ├─┬ optimist@0.6.1 
  │ └── wordwrap@0.0.3 
  ├─┬ supports-color@3.2.3 
  │ └── has-flag@1.0.0 
  ├── tapable@0.1.10 
  ├─┬ uglify-js@2.7.5 
  │ ├── async@0.2.10 
  │ ├── uglify-to-browserify@1.0.2 
  │ └─┬ yargs@3.10.0 
  │   ├── camelcase@1.2.1 
  │   ├─┬ cliui@2.1.0 
  │   │ ├─┬ center-align@0.1.3 
  │   │ │ ├─┬ align-text@0.1.4 
  │   │ │ │ ├── longest@1.0.1 
  │   │ │ │ └── repeat-string@1.6.1 
  │   │ │ └── lazy-cache@1.0.4 
  │   │ ├── right-align@0.1.3 
  │   │ └── wordwrap@0.0.2 
  │   ├── decamelize@1.2.0 
  │   └── window-size@0.1.0 
  ├─┬ watchpack@0.2.9 
  │ ├── async@0.9.2 
  │ └─┬ chokidar@1.7.0 
  │   ├─┬ anymatch@1.3.0 
  │   │ └── arrify@1.0.1 
  │   ├── async-each@1.0.1 
  │   ├── glob-parent@2.0.0 
  │   ├─┬ is-binary-path@1.0.1 
  │   │ └── binary-extensions@1.8.0 
  │   └─┬ readdirp@2.1.0 
  │     ├─┬ readable-stream@2.3.3 
  │     │ ├── isarray@1.0.0 
  │     │ └── string_decoder@1.0.3 
  │     └── set-immediate-shim@1.0.1 
  └─┬ webpack-core@0.6.9 
    ├── source-list-map@0.1.8 
    └─┬ source-map@0.4.4 
      └── amdefine@1.0.1 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
npm WARN vue-loader@8.7.0 requires a peer of css-loader@* but none was installed.
npm WARN pagekit@ No repository field.
npm WARN pagekit@ No license field.`

**Comment by SPQRInc** [comment]
I would recommend you to download the installer (https://pagekit.com/docs/getting-started/installation#step-1-download-and-open-the-installer) .

You can run a full-featured Pagekit installation this way. In my opinion there are no disadvantages installing Pagekit this way.

**Comment by MalteScharenberg** [comment]
@mhsabbagh fsevents and css-loader are optional. It should be possible to compile Pagekit anyway with `bower install && webpack && gulp`.

**Comment by mhsabbagh** [comment]
Things got a little bit better when I downloaded the release from http://pagekit.com/api/download/latest: 
![screenshot_2017-07-06_14-48-45](https://user-images.githubusercontent.com/1293003/27909634-4ca097f8-625a-11e7-9400-f23fb46eddc7.png)

However as you can see, looks like some modules are still not present: 
![screenshot_2017-07-06_14-50-40](https://user-images.githubusercontent.com/1293003/27909683-8282cdfa-625a-11e7-9770-b6d42f46a654.png)

@MalteScharenberg All the commands you gave are not found.

**Comment by SPQRInc** [comment]
Did you run `composer install` and/or `npm install` after downloading the release?

If you did: Do not ;)

**Comment by mhsabbagh** [comment]
Well, I downloaded the release and immediately checked the results. Was just like the first image. Then I ran `npm install` to see if things could change. Still the same. I didn't run `composer install` yet.

**Comment by SPQRInc** [comment]
Do not. Just follow https://pagekit.com/docs/getting-started/installation#step-1-download-and-open-the-installer .

If you download the release you must not run `npm install` and/or `composer install` .

Just download, unzip, move to your web hosting document root and run the web based installation.

**Comment by mhsabbagh** [comment]
Which I did, and as I told you, the results are in the attached images.

**Comment by SPQRInc** [comment]
That's strange. I am going to reconstruct this here on an ESX VM. Which browser are you using?

**Comment by mhsabbagh** [comment]
Hmm, it seems to be a weird browser issue here. On Firefox 54, now it works great (I ran both composer and node btw). On chromium 59. It shows just like the images. All browser add-ons are disabled.

**Comment by mhsabbagh** [comment]
Since I am the only one who was facing this, it's probably hardware-limited or caused by my installation. I am closing this issue.

Thank you all, your CMS is amazing indeed!
