### ISSUE TITLE
Maintenance Offline Message don't work

### ISSUE THREAD

**Issue by uziel200** [pagekit/pagekit#846]
## Problem

When you activate the Maintenance Offline nothing change in the Site, the site still available and no offline message is display it.

## Technical Details

- Pagekit version: 1.0.12
- Webserver: Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/5.6.18
- Database: mysql / 5.7.10-log
- PHP Version: 5.6.18

**Comment by SPQRInc** [comment]
Please go to the admin panel of your site and log out.

If you are logged out the frontend of your page should be unavailable.

**Comment by SPQRInc** [comment]
Please reopen if the problem persists
