### ISSUE TITLE
If meta title is set - overwrite <title>

### ISSUE THREAD

**Issue by SPQRInc** [pagekit/pagekit#858]
## Problem

I figured out, that the `title` Pagekit defines is always just like the Item's title, even if the user defines a custom title in the meta-tab (which is only used for open graph).

I think the user should be able to overwrite the title.

## Technical Details

- Pagekit version: 1.0.12
- Webserver: Apache 2.4
- Database: SQLIte
- PHP Version: 7

**Comment by unckleg** [comment]
I'm in process of creating SEO Extension that is similar to wordpress Yoast plugin.
It will be released soon.

**Comment by SPQRInc** [comment]
It's great that you are going to provide an extension for this. But I think this should be fixed in the core as it's some basic stuff :)

**Comment by SPQRInc** [comment]
As it's not solved in the core yet, I created [spqr/seo](https://spqr.wtf/projects/seo), which solves the problem. It's free and can be downloaded from the marketplace.
