### ISSUE TITLE
webpack not compiling correctly

### ISSUE THREAD

**Issue by thatdanski** [pagekit/pagekit#861]
## Problem

I'm new to Pagekit and trying to create my first theme. Following the documentation on the Pagekit website, it looks as though I have to use "vue-loader" instead of "vue". I'm wondering if the documentation needs updating?

Webpack does seem to compile the "site-theme.js" file, but this does not render in the settings page in the site. 
The actual rendering of the "site-theme.js" file seems different to that of the sample themes also.

## Technical Details

- Pagekit version: 1.0.12
- Webserver: Apache/2.4.10 (Unix) OpenSSL/1.0.1j PHP/5.6.3 mod_perl/2.0.8-dev Perl/v5.16.3
- Database: sqlite 3.8.4.3
- PHP Version: 5.6.3

**Comment by SPQRInc** [comment]
For me it does not seem like a bug. Seems like something you should discuss on the forum or on the gitter chat.

If you do not agree, please feel free to reopen.
