### ISSUE TITLE
Post preview shows <post-preview> when I add brackets to my text

### ISSUE THREAD

**Issue by SPQRInc** [pagekit/pagekit#863]
## Problem

Post preview shows `<post-preview>` when I add brackets in a `<pre>` tag.

So if I write 

```
` ` `
'config' => [],
` ` `
```

in my text, the preview shows `'config' => <link-preview index="7"></link-preview>,`

Escaping with backslash does not work.

In the frontend the text is shown correctly.

  
## Technical Details

- Pagekit version: 1.0.12
- Webserver: Apache 2.4
- Database: SQLite
- PHP Version: 7.1.2

**Comment by tobbexiv** [comment]
Isn't this exactly the same as #787?

**Comment by SPQRInc** [comment]
Right. I am closing this.
