### ISSUE TITLE
Rich pins

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [pagekit/pagekit#864]
## Feature request

I would like to use rich pins (https://developers.pinterest.com/docs/rich-pins/products/)

**Comment by SPQRInc** [comment]
Pagekit supports Open Graph properties like `og:title`, `og:description` etc.

`product:price:amount` and other properties that are attached to a product should not be implemented in Pagekit's core. In my opinion this is something an extension could do.

**Comment by SPQRInc** [comment]
Closed, as this should be done by an extensions; if you think, this feature should be implemented in the core, please reopen :)
