### ISSUE TITLE
Acess denied

### ISSUE THREAD

**Issue by gtbu** [pagekit/pagekit#876]
## Problem
After installation on Xampp 7.18 i just get the  error (debug=true set) :
Access denied!  
Access to the requested object is not possible. Either it can not be read by the server or it is access-protected.

Other CMSses like typesetter start without problem

## Technical Details

- Pagekit version: 1.013
- Webserver: xampp php 7.18
- Database: - sqlite
- PHP Version: 7.18

**Comment by SPQRInc** [comment]
Where did you get the error? On every page?

Please show us the content of .htaccess and file permissions.

**Comment by gtbu** [comment]
I got the error direct after localhost/pagekit    ( all other cmssses work)
P.S After deleting .htaccess it startet with error of missing htacces.
After renaming it i could continue the installation.
