### ISSUE TITLE
Stored XSS Security Vulnerability

### ISSUE THREAD

**Issue by ProDigySML** [pagekit/pagekit#877]
## Problem
I found that anyone who can write a post (like an author type role), can perform cross-site scripting on the application. This implies they can run arbitrary JS code on the victim's browser. 

Make a post with 
```html
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.<img src=x onerror="alert(1)">
```
as the text and notice an alert box pop up. 

## Technical Details

- Pagekit version: latest
- Webserver: Apache
- Database: MySQL
- PHP Version: 7.0

**Comment by SPQRInc** [comment]
Duplicate of https://github.com/pagekit/pagekit/issues/815 .

If you are convinced that this is no duplication or needs more discussion, feel free to reopen.
