### ISSUE TITLE
Themes uninstallable

### ISSUE THREAD

**Issue by gtbu** [pagekit/pagekit#878]
Exept ONE and Hello has the installation of themes the error
JSON aus dem Paket kann nicht geladen werden. The same is with tinymce 1.02 and other extensions
## Technical Details
- Pagekit version: 1.013
- Webserver:
- Database: sqlite
- PHP Version: 7.18 xampp

**Comment by SPQRInc** [comment]
Are you installing from marketplace?

**Comment by SPQRInc** [comment]
If you are not installing from marketplace, please have a look at https://pagekit-forum.org/forum/thread/144-can-t-load-json-file-from-package/ .

**Comment by gtbu** [comment]
I have a PC  and am not quite clear what to do : There is no pagekit-test in my installation and what sense does it make to put the root-.files together with app-directory into a zip. Could You please add some explaining lines to the forum

**Comment by SPQRInc** [comment]
Please answer to my question: Are you installing the theme/extension from marketplace or do you upload them from local?

**Comment by gtbu** [comment]
My PC does not zip  or unzip. Firefox just downloads it into a directory which i before made k:\cmsflat\pagekit - not into a whatever 'extension/theme' directory. The zips are untouched. 
From within the system i tried to install these untouched zips and got the error while uploading from the directory. 
The solution for the themes was to unzip the themes into the folder of the installed zips (which is fiddly to find). Then they appeared within the installed themes. But installing it from within the system is impossibe - dont You have a PC ?

**Comment by SPQRInc** [comment]
Hello,

well - I guess we are not talking about the same thing:

- You are downloading to `k:\cmsflat\pagekit` and try to upload the untouched zip via *System -> Extensions -> Upload*, correct?
-  Who was talking about a `extension/theme` directory?

Your solution works, but it's not the correct way. If you do so on extensions that are running `scripts.php`, e.g. for database migration, the extension will not work this way.

> But installing it from within the system is impossible - dont You have a PC ?

I am using Pagekit on macOS, Fedora, CentOS, RedHat. On all systems working fine.
 

> With the bootstrapkit for pagekit from github this does not function either

You mean if you clone it? Did you follow the instruction? The preferred way is to download the archive from pagekit.com, as if you clone it from GitHub, you need to run `npm install` and so on before.

But I got one more question: Why aren't you using the built-in marketplace?

**Comment by SPQRInc** [comment]
I just downloaded Pagekit `1.0.13` from pagekit.com and installed it on an emulated Windows 10.

Works without problems. 

As your installation did not work without problems I guess there is an issue with your web server config and/or the file permissions on your system.

Please check whether your system fits the requirements (https://pagekit.com/docs/getting-started/requirements) and follow the installation guide (https://pagekit.com/docs/getting-started/installation) again.

We need a clean install, that works without "hacking" the installation process.

I'm sure that we will find a solution for your issue.

As I don't think this is a Pagekit issue, I would recommend to close this issue and open a topic on https://pagekit-forum.org (you don't need to register again - you can use your GitHub credentials to use the forum).

**Comment by gtbu** [comment]
Perhaps it has something to to with xampp - i have hacked nothing - and did not have these problems with other CMSses - but thank You for Your support - i hope that in future will come a version of ckeditor and the possibility to add a theme to a site while generating the site
