### ISSUE TITLE
 Only saves static files locally

### ISSUE THREAD

**Issue by GHBI** [pagekit/pagekit#879]
How to set the default storage to Azure blob

**Comment by SPQRInc** [comment]
Isn't it possible to mount azure blob (https://docs.microsoft.com/en-gb/azure/storage/files/storage-how-to-use-files-linux)?

Given this, you can mount it to `/storage` and use it with Pagekit?

**Comment by SPQRInc** [comment]
Closed as no more information provided.

Feel free to reopen :)
