### ISSUE TITLE
No themes or extensions found but site is working normally

### ISSUE THREAD

**Issue by JamesWoodford** [pagekit/pagekit#891]
## Problem

Admin -> Settings reports "No theme found." and "No extension found." but site has themes and extensions working fine.
No errors reported in php logs or browser consoles (with or without debug mode).

I use develop -> staging -> production environments and wonder if that might have affected something? Although the develop and staging are working fine and have not had problems before.

I am about to sync latest changes from staging but I am a bit hesitant because, with something obviously wrong somewhere, it might break the live site. And I'm not sure about installing anything over the top of something that I know is installed.

Thanks.

## Technical Details

- Pagekit version: 1.0.13
- Webserver: Apache 2.4.7
- Database: 5.5.58
- PHP Version: 5.5.9

**Comment by SPQRInc** [comment]
Is it possible to upload a new theme or extension? Did you check the file permissions?

**Comment by JamesWoodford** [comment]
Directory / File permissions are all 2775 / 0664.
I've just installed, enabled and uninstalled the "Highlight" extension with no errors.
I'm not able to upload a new theme as it is a live site with a (working!) custom theme.

Thanks.

**Comment by JamesWoodford** [comment]
Being under some time pressure, I ended up reverting to a previous version of the site, re-applied my changes and it is working now.
Would have been good to know what the problem was but I guess I'll just close this now. 
Thanks anyway.
