### ISSUE TITLE
One Pager Theme

### ISSUE THREAD

**Issue by gokkstudio** [pagekit/pagekit#892]
Hi, new to Pagekit, but it's great.

Anyone has an idea of how could I make one page navigation theme, to actually link pages as ID's and show all pages on one page?

**Comment by SPQRInc** [comment]
Closed, as it is no issue but a help request. Please consider asking on https://gitter.im/pagekit/pagekit or https://pagekit-forum.org .

If you consider this an issue, feel free to reopen.

**Comment by gokkstudio** [comment]
Sorry, my bad, will post elsewhere.

**Comment by SPQRInc** [comment]
No problem :)
