### ISSUE TITLE
Stored XSS issue in Blog title 

### ISSUE THREAD

**Issue by fvi-att** [pagekit/pagekit#894]
## Problem
Hello, I found stored XSS security issue in the blog title.
I have no good idea where is the best to post this issue, so I will post it here.
When Authenticated attacker post crafted the blog post. Any kind of Javascript is executed on browsers of users who access to crafted blog post page.

Let me show how to reproduce it.
 1.  Acces to 「/admin/blog/post/edit」
 2. set blog  title as following 

```html
stub-title<script>alert(0);</script>
```
<img width="1080" alt="image1" src="https://user-images.githubusercontent.com/1528031/37154873-af790fa0-2324-11e8-889a-0519ddd2f978.png">

3. Save the blog and publish it.
4. Back to Blog list page 「/Pagekit/admin/blog/post?page=0」
5. Access to the blog url 「/blog/1」　as following image
<img width="1027" alt="image2" src="https://user-images.githubusercontent.com/1528031/37185107-1844ad5c-2382-11e8-85f7-b7c48a2b1271.png">

6. dialog appears and says as 「XSS」
<img width="1078" alt="2018-03-08 20 53 53" src="https://user-images.githubusercontent.com/1528031/37186550-7cb8fdcc-2389-11e8-816f-1db76ae58433.png">

Then you reproduce Stored XSS issue is in the blog title.

## Consideration
When an attacker uses this security issue for an attack, he is required to be authorized. So this issue is not so serious. But if another security issue is discovered and this security issue might be getting serious.

## Technical Details

- Pagekit version: 1.0.13
- Web server: Apache
- Database: not related this issue
- PHP Version: 5.6.31

**Comment by tobbexiv** [comment]
Dupe of #814

**Comment by fvi-att** [comment]
@tobbexiv Thanks. I close this issue.
