### ISSUE TITLE
Search problems

### ISSUE THREAD

**Issue by vkysnota** [pagekit/pagekit#901]
Hello! 

**I have trouble with the search. I don't know if it can be somehow connected to the fact that I installed my template design on the site.**

For some reason it can't find new post in blog. I write in the query the existing name of the material - entry in blog, and the search gives results "Total: Nothing found." By news is understood-the material, that is, added entry to the blog. That is, I have a problem that when you enter a request in the search, it does not give any results.

The screenshot shows everything, that is, I enter a query - phrase, the name of an existing and published in blog entry, and click find. But the search displays nothing, there are no results!

![screen](https://user-images.githubusercontent.com/34855920/41226101-828892fc-6d81-11e8-84c9-747d10603b36.png)

**Comment by vkysnota** [comment]
I enter into the search not only the names of existing blog posts, but also the usual statistical pages. For example, about the site, reviews, support - search also does not display them in the query results.

**Comment by SPQRInc** [comment]
Pagekit does not come with any kind of search function. If you are using a third-party-extension, please contact the developer of that extension.

I am closing this issue now. If you think this is a problem related to the Pagekit core, feel free to reopen.
