### ISSUE TITLE
Front page "Whoops..." error

### ISSUE THREAD

**Issue by tborychowski** [pagekit/pagekit#902]
## Problem

If I set a site as "front page" (little home icon) - this page will not show up, but it will show this:
<img width="440" alt="screen shot 2018-06-12 at 18 32 05" src="https://user-images.githubusercontent.com/392513/41306715-ee7f6182-6e6e-11e8-9ee1-463bc4b95862.png">
And the "Network" in dev-tools shows 403 (Forbidden).

Every other page works.
If I change the "front page" to any other - it's the same: the new front page doesn't show up, and the one that used to be the front page (but isn't any more) - works fine.

It was setting some pages to be visible only for authenticated users and suddenly this happened.
I tried everything (except reinstalling). I changed all pages to not be restricted, but no luck.
Also - enabling debug mode doesn't do anything.

## Technical Details

- Pagekit version: 1.0.13
- Webserver: Apache
- Database: MySQL
- PHP Version: 7

**Comment by SPQRInc** [comment]
Hi,

how did you install Pagekit? Did you use the download-package or did you clone the repo?

And how did you enable debug mode?

Please notice that there are two `debug` options in `config.php`:

```
<?php return array (
  'application' => 
  array (
    'debug' => true,
  ),
  'locale' => 'en_GB',
  'database' => 
  array (
    'default' => 'sqlite',
    'connections' => 
    array (
      'sqlite' => 
      array (
        'dbname' => NULL,
        'host' => NULL,
        'user' => NULL,
        'password' => NULL,
        'prefix' => 'pagekit_',
      ),
    ),
  ),
  'system' => 
  array (
    'secret' => '...',
  ),
  'system/cache' => 
  array (
    'caches' => 
    array (
      'cache' => 
      array (
        'storage' => 'auto',
      ),
    ),
    'nocache' => true,
  ),
  'system/finder' => 
  array (
    'storage' => '',
  ),
  'debug' => 
  array (
    'enabled' => true,
  ),
);
```

**Comment by tborychowski** [comment]
Hi,

Thanks for a quick response.
I tried both of them (with no luck), but... it's fixed now.
Must have been some sort of a caching problem, as I have left this for couple of hours and it started working again!
Sorry for bothering you :-)
