### ISSUE TITLE
page add panel in cross site scripting vulnerability

### ISSUE THREAD

**Issue by ismailtasdelen** [pagekit/pagekit#906]
Hello Development Team,

When I was a security researcher and student, I wanted to discover and report "XSS" vulnerability.

Version : Pagekit 1.0.14

Vuln url address : https://demos5.softaculous.com/Pagekit/admin/site/page/edit?id=page&menu=main

Screenshot : 

![screenshot from 2018-07-18 11-58-24](https://user-images.githubusercontent.com/15425071/42871202-6cd9ff90-8a82-11e8-9e9c-3e27e962c020.png)

Payload : "><img src=x onerror=alert('ismailtasdelen')>

Thanks

**Comment by tobbexiv** [comment]
I would assume it's a dupe of #814

There it is also explained how security issues should be reported.

**Comment by ismailtasdelen** [comment]
Thanks for the came back :+1:
