### ISSUE TITLE
user edit panel in cross site scripting vulenrabiltiy 

### ISSUE THREAD

**Issue by ismailtasdelen** [pagekit/pagekit#907]
Hello Development Team,

When I was a security researcher and student, I wanted to discover and report "XSS" vulnerability.

Version : Pagekit 1.0.14

Vuln url address : https://demos5.softaculous.com/Pagekit/admin/user/edit?id=1

Screenshot : 

![screenshot from 2018-07-18 12-03-58](https://user-images.githubusercontent.com/15425071/42871364-dcd42d98-8a82-11e8-9072-34348b66edd3.png)

Payload : "><img src=x onerror=alert('ismailtasdelen')>

Thanks

**Comment by tobbexiv** [comment]
I would assume it's a dupe of #814

There it is also explained how security issues should be reported.

**Comment by ismailtasdelen** [comment]
Thanks for the came back :+1:
