### ISSUE TITLE
blog add panel in  cross site scripting

### ISSUE THREAD

**Issue by ismailtasdelen** [pagekit/pagekit#908]
Hello Development Team,

When I was a security researcher and student, I wanted to discover and report "XSS" vulnerability.

Version : Pagekit 1.0.14

Vuln url address : http://localhost/Pagekit/blog

Screenshot : 

![screenshot from 2018-07-18 12-09-42](https://user-images.githubusercontent.com/15425071/42871715-b8ac9198-8a83-11e8-9522-931907fc85c4.png)

Payload : 

 "><img src=x onerror=alert('ismailtasdelen')>

Thanks

**Comment by tobbexiv** [comment]
I would assume it's a dupe of #814

There it is also explained how security issues should be reported.

**Comment by ismailtasdelen** [comment]
Thanks for the came back :+1:
