### ISSUE TITLE
Is This Project Dead?

### ISSUE THREAD

**Issue by vdanelia** [pagekit/pagekit#928]
Hello friends, I found this cms today and Installed, at first sight, I liked it, but found some minor bugs. I'm interested if this project is still supported because many users are also asking this question.
Thank you and please, answer us.

## Problem

Your problem description here...

## Technical Details

- Pagekit version:
- Webserver:
- Database:
- PHP Version:

**Comment by saschadube** [comment]
Pagekit is not in active development for a while now. However, we are maintaining it with bug fixes and important issues will be fixed immediately.
