### ISSUE TITLE
Feature request: Menu - add "File" menu item type

### ISSUE THREAD

**Issue by ericbrissette** [pagekit/pagekit#96]
I'd like to see a new menu item type called **File** or something similar.  Selecting it would allow you to browse /storage for a file and link to an existing file or upload a new file using the already existing File Manager.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
