### ISSUE TITLE
Feature Request: Author Aliases and Multiple Authors

### ISSUE THREAD

**Issue by newlocalmedia** [pagekit/pagekit#98]
__Author Aliases:__ Allow arbitrary names to be assigned to content pages for use as alternative content author names. This allows the public credit for an "author" of a content page to be different from the User who created or who owns the content in the CMS. Typically these aliases would be displayed in article bylines.

__Multiple Authors/Co-Authors:__ Allow more than one User and/or Aliases to be assigned to a Page as its Authors.

**Comment by emanuelebrivio** [comment]
*+1* for **Multiple Authors**. Many customers have asked me about that feature on their website / blog!

**Comment by azappa** [comment]
+1 for this feature! I need it a lot!

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
