### ISSUE TITLE
Feature Request: Distinguish Users from Authors

### ISSUE THREAD

**Issue by newlocalmedia** [pagekit/pagekit#99]
How should CMS Users relate to Content Authors? Currently they are treated as one and the same. This makes it difficult to quickly handle content with multiple authors and authors who are not (and should not be) CMS Users.

IIRC, the Pagekit backend interface for the Page Manager refers to the Owner of a Page (a User) as the Page's "Author." This indicates an assumption that is often false -- someone other than the User/Owner actually authored the content and needs public credit for it. Must they have a User account to give them credit, an author page, and to be able to list everything they have contributed? __It may be best to distinguish between Authors and Owners/people with technical responsibility for the content.__

One way to do this is to treat "Authors" as a separate taxonomy where author names work like a special kind of Tag.

**Comment by saschadube** [comment]
We released the [Pagekit Beta](http://www.pagekit.com/blog/2015/09/10/pagekit-beta-released) today. I close this issue because the code base completely changed. Please open a new issue if it still exists.
